<template>
  <div class="student-teaching-tasks">
    <template v-if="!assignment">
      <div class="student-task-filter"><label>班级<select v-model="classId"><option value="">全部班级</option><option v-for="c in classes" :key="c.id" :value="String(c.id)">{{c.name}}</option></select></label><label>任务进度<select v-model="status"><option value="">全部进度</option><option value="incomplete">待完成</option><option value="completed">已完成要求</option><option value="failed">报告生成失败</option></select></label><label>搜索任务<input v-model="search" type="search" placeholder="任务名称或岗位"/></label></div>
      <div class="student-task-summary"><strong>{{visible.length}} 项教学任务</strong><span>按任务分别记录进度，自主训练不会抵扣教学次数。</span></div>
      <div v-if="visible.length" class="student-task-list"><article v-for="a in visible" :key="a.id" class="student-task-card"><header><span>{{a.task.className}}</span><span class="status-tag" :class="a.completionStatus==='COMPLETED'?'positive':'neutral'">{{progressLabel(a)}}</span></header><h2><RouterLink :to="taskLink(a)">{{a.task.title}}</RouterLink></h2><p>{{a.task.jobName}} · {{a.task.durationSeconds/60}} 分钟 / 次</p><p class="student-task-description">{{a.task.description||'按照教师指定问题完成训练，提交后查看报告与反馈。'}}</p><div class="student-task-progress"><div><strong>有效 {{a.validCount}} / {{a.task.minAttempts}} 次</strong><span>{{a.completionStatus==='COMPLETED'?'训练次数要求已完成':'尚需 '+Math.max(0,a.task.minAttempts-a.validCount)+' 次有效训练'}}</span></div><progress :value="a.validCount" :max="a.task.minAttempts" :aria-label="a.task.title+'有效训练进度'"/></div><footer><div><span>{{lifeLabel(a.task,a.effectiveDeadline)}}</span><small>截止 {{time(a.effectiveDeadline||a.task.deadline)}}</small></div><RouterLink :to="taskLink(a)" class="primary">{{a.attempts.some(p=>p.state==='ONGOING')?'继续任务':'查看任务'}} →</RouterLink></footer></article></div>
      <section v-else class="live-empty live-empty-bordered"><h3>{{tasks.length?'没有符合筛选的任务':'等待教师发布你的第一项任务'}}</h3><p>{{tasks.length?'尝试其他班级或任务关键词。':'加入教学班并通过审核后，分配给你的任务会显示在这里。'}}</p><button v-if="tasks.length" @click="classId='';status='';search=''">清除筛选</button><RouterLink v-else class="primary" to="/my/classes">查看我的班级 →</RouterLink></section>
    </template>
    <template v-else>
      <section class="live-panel student-task-intro"><div><span class="task-context">{{assignment.task.className}} · 教学任务</span><h2>{{assignment.task.title}}</h2><p>{{assignment.task.jobName}} · {{lifeLabel(assignment.task,assignment.effectiveDeadline)}}</p><p class="student-task-description">{{assignment.task.description||'完成教师指定问题，结合报告和反馈继续改进。'}}</p></div><span class="status-tag" :class="assignment.completionStatus==='COMPLETED'?'positive':'neutral'">{{progressLabel(assignment)}}</span></section>
      <div class="student-task-detail-grid"><div>
        <section class="live-panel student-task-requirements"><header><h2>训练安排</h2></header><dl><div><dt>开始时间</dt><dd>{{time(assignment.task.startTime)}}</dd></div><div><dt>截止时间</dt><dd>{{time(assignment.effectiveDeadline||assignment.task.deadline)}}</dd></div><div><dt>单次时长</dt><dd>{{assignment.task.durationSeconds/60}} 分钟</dd></div><div><dt>训练次数</dt><dd>至少 {{assignment.task.minAttempts}} 次有效 · 最多 {{assignment.effectiveMaxAttempts||assignment.task.maxAttempts}} 次尝试</dd></div><div><dt>补交规则</dt><dd>{{assignment.task.allowLate?'截止后允许补交，仍需在任务结束前提交':'不允许截止后提交；请预留回答与提交时间'}}</dd></div></dl><h3>教师指定问题</h3><ol class="student-task-questions"><li v-for="(q,i) in assignment.task.questions" :key="i"><span>{{i+1}}</span><p>{{q}}</p></li></ol></section>
        <section class="live-panel"><TeachingScorePlan :plan="assignment.task.scorePlan"/></section>
      </div><aside>
        <section class="live-panel student-task-action"><h2>你的任务进度</h2><p class="student-progress-number">{{assignment.validCount}}<span> / {{assignment.task.minAttempts}} 次有效训练</span></p><progress :value="assignment.validCount" :max="assignment.task.minAttempts" aria-label="任务次数完成进度"/><p>已尝试 {{assignment.attempts.length}} 次 · 剩余 {{Math.max(0,(assignment.effectiveMaxAttempts||assignment.task.maxAttempts)-assignment.attempts.length)}} 次</p><p class="student-task-rule">完整回答指定问题并按任务时效规则提交，报告生成成功后才计入有效次数。次数完成不等同于评分目标达成。</p><RouterLink v-if="eligibility.allowed" class="primary" :to="{path:'/interview',query:{assignmentId:assignment.id,jobId:assignment.task.jobId,durationSeconds:assignment.task.durationSeconds}}">{{assignment.attempts.some(p=>p.state==='ONGOING')?'继续任务训练':assignment.completionStatus==='COMPLETED'?'继续巩固训练':'开始任务训练'}} →</RouterLink><p v-else class="student-task-blocked">{{eligibility.reason}}</p></section>
        <section class="live-panel student-feedback-panel"><h2>报告与教师反馈</h2><p>选择一份报告查看教师已经发布的点评。</p><select v-if="reportAttempts.length" v-model="feedbackReport" aria-label="选择点评报告"><option v-for="(p,i) in reportAttempts" :key="p.reportId" :value="String(p.reportId)">{{time(p.submittedAt)}} · {{attemptLabel(p.state)}}</option></select><TeachingFeedback v-if="feedbackReport" :report-id="feedbackReport" show-empty/><p v-else class="student-feedback-empty">完成训练并生成报告后，教师反馈会显示在这里。</p></section>
      </aside></div>
      <section class="live-panel student-task-results"><header><div><h2>每次训练的结果</h2><p>保留全部尝试，明确说明哪些结果计入任务次数。</p></div><span>{{assignment.attempts.length}} 次尝试</span></header><article v-for="(p,i) in assignment.attempts" :key="p.id" class="student-attempt-row"><div><strong>第 {{assignment.attempts.length-i}} 次训练</strong><small>{{time(p.submittedAt||p.startedAt)}}</small></div><div><span class="status-tag" :class="p.state==='READY'?'positive':p.state==='INVALID'||p.state==='FAILED'?'warning':'neutral'">{{attemptLabel(p.state)}}</span><p>{{p.state==='READY'?'已计入有效训练次数':p.failureReason||attemptNote(p.state)}}</p></div><div><RouterLink v-if="p.reportId" :to="{path:'/history/'+p.reportId,query:{assignmentId:assignment.id}}">查看报告与点评 →</RouterLink><button v-if="p.state==='FAILED'" :disabled="working" @click="$emit('retry',p.sessionId)">重试报告生成</button></div></article><div v-if="!assignment.attempts.length" class="live-empty"><h3>尚未开始训练</h3><p>从上方进入任务训练。每次提交都会保留结果与进度。</p></div></section>
    </template>
  </div>
</template>
<script setup>
import {computed,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import TeachingFeedback from './TeachingFeedback.vue'
import TeachingScorePlan from './TeachingScorePlan.vue'
const props=defineProps({tasks:{type:Array,default:()=>[]},classes:{type:Array,default:()=>[]},assignment:Object,working:Boolean})
defineEmits(['retry'])
const route=useRoute(),classId=ref(String(route.query.classId||'')),status=ref(String(route.query.status||'')),search=ref(String(route.query.search||'')),feedbackReport=ref('')
const visible=computed(()=>props.tasks.filter(a=>(!classId.value||String(a.task.classId)===classId.value)&&(!status.value||status.value==='completed'&&a.completionStatus==='COMPLETED'||status.value==='incomplete'&&a.completionStatus!=='COMPLETED'||status.value==='failed'&&a.attempts.some(p=>p.state==='FAILED'))&&`${a.task.title} ${a.task.jobName}`.includes(search.value.trim())))
const returnTo=computed(()=>'/my/tasks?'+new URLSearchParams({...(classId.value?{classId:classId.value}:{}),...(status.value?{status:status.value}:{}),...(search.value?{search:search.value}:{})}))
const taskLink=a=>({path:'/my/tasks/'+a.id,query:{returnTo:returnTo.value}})
const timestamp=v=>Date.parse(v&&/[Z+]/.test(v)?v:v+'+08:00'),time=v=>v?new Date(timestamp(v)).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'尚未提交'
const lifeLabel=(t,personalDeadline)=>t.archived?'班级已归档':t.endedAt?'任务已结束':t.lifecycle==='CLOSED'?(personalDeadline&&timestamp(personalDeadline)>Date.now()?'个人延期中':t.allowLate?'已截止，可补交':'已截止'):t.lifecycle==='SCHEDULED'?'待开始':'进行中'
const progressLabel=a=>a.exempt?'教师已减免':a.completionStatus==='COMPLETED'?'已完成次数要求':a.attempts.some(p=>p.state==='FAILED')?'报告生成失败':a.completionStatus==='PENDING_VALIDATION'?'等待报告生成':a.attempts.some(p=>p.state==='ONGOING')?'训练进行中':a.attempts.length?'待补充有效训练':'尚未开始'
const attemptLabel=s=>({ONGOING:'训练进行中',GENERATING:'报告生成中',READY:'有效结果',INVALID:'未计入有效次数',FAILED:'报告生成失败'}[s]||s)
const attemptNote=s=>({ONGOING:'继续当前训练后提交。',GENERATING:'报告生成完成后更新有效次数，请稍后刷新。',INVALID:'请查看未计入原因，按要求重新训练。',FAILED:'重试生成同一份报告，不增加训练尝试次数。'}[s]||'')
const reportAttempts=computed(()=>props.assignment?.attempts.filter(p=>p.reportId)||[])
watch(reportAttempts,rows=>{if(!rows.some(p=>String(p.reportId)===feedbackReport.value))feedbackReport.value=rows[0]?String(rows[0].reportId):''},{immediate:true})
const eligibility=computed(()=>{const a=props.assignment;if(!a)return {allowed:false};if(a.startEligibility)return a.startEligibility;const t=a.task;if(a.memberState!=='JOINED')return {allowed:false,reason:'你已不属于这个班级，历史报告与反馈仍可查看。'};if(t.archived||t.endedAt)return {allowed:false,reason:'任务已结束，历史训练与报告保留。'};if(timestamp(t.startTime)>Date.now())return {allowed:false,reason:'尚未到任务开始时间。'};if(a.attempts.some(p=>p.state==='ONGOING'))return {allowed:true};if(!t.allowLate&&timestamp(t.deadline)<=Date.now())return {allowed:false,reason:'任务已截止，当前不允许补交。'};if(a.attempts.some(p=>p.state==='GENERATING'))return {allowed:false,reason:'上一份报告正在生成，请等待结果。'};if(a.attempts.length>=t.maxAttempts)return {allowed:false,reason:'训练次数已用完，可联系教师安排补练。'};return {allowed:true}})
</script>
