<template>
 <div class="analytics-page live-analytics">
  <header class="analytics-header"><div><h1>数据分析</h1><p>从更长时间和更大范围观察训练趋势、班级差异与能力结构</p></div><div><button @click="definitionsOpen=true">指标说明</button><button class="analytics-primary" @click="exportOpen=true">导出分析</button></div></header>
  <nav class="analytics-tabs" aria-label="分析类型"><button v-for="t in tabs" :key="t.id" :class="{active:tab===t.id}" :aria-current="tab===t.id?'page':undefined" @click="set({tab:t.id})">{{t.name}}</button></nav>
  <form class="analytics-filters" @submit.prevent>
   <label>时间范围<select aria-label="时间范围" :value="timeRange" @change="set({timeRange:$event.target.value,from:undefined,to:undefined})"><option value="30d">近30天</option><option value="90d">近90天</option><option value="semester">本学期</option><option value="custom">自定义</option></select></label>
   <template v-if="timeRange==='custom'"><label>开始日期<input type="date" aria-label="开始日期" :value="from" @change="set({from:$event.target.value})"/></label><label>结束日期<input type="date" aria-label="结束日期" :value="to" :max="today" @change="set({to:$event.target.value})"/></label></template>
   <div class="analytics-class-filter"><span class="class-picker-label">班级范围</span><details ref="classPicker" class="analytics-class-picker" @keydown.esc.prevent="closeClassPicker" @toggle="onClassPickerToggle"><summary><strong>{{classIds.length===1?classes.find(c=>String(c.id)===classIds[0])?.name||'1个班级':classIds.length?classIds.length+'个班级':'全部班级'}}</strong><span aria-hidden="true" class="class-picker-chevron">⌄</span></summary>
    <div class="analytics-class-popover"><header><strong>{{tab==='classes'?'选择对比班级':'统计班级范围'}}</strong><span>{{tab==='classes'?pendingClassIds.length+'/4 已选':pendingClassIds.length?'已选 '+pendingClassIds.length+' 个':'全部 '+classes.length+' 个'}}</span></header>
     <p>{{tab==='classes'?'选择 2–4 个班级，查看同一周期的差异。':'选择班级后点击应用，跨班学生按人去重。'}}</p>
     <input v-model="classSearch" type="search" aria-label="搜索统计班级" placeholder="搜索班级名称或学期"/>
     <button v-if="tab!=='classes'" type="button" class="class-picker-all" :aria-pressed="!pendingClassIds.length" @click="pendingClassIds=[]"><span>全部班级</span><span>{{!pendingClassIds.length?'已选':classes.length+' 个'}}</span></button>
     <fieldset><legend class="class-picker-sr">选择指定班级</legend><label v-for="c in filteredPickerClasses" :key="c.id" :class="{'is-selected':pendingClassIds.includes(String(c.id))}"><input type="checkbox" :checked="pendingClassIds.includes(String(c.id))" :disabled="tab==='classes'&&((pendingClassIds.length>=4&&!pendingClassIds.includes(String(c.id))))" @change="toggleClass(c.id)"/><span>{{c.name}}<small v-if="c.semester||c.archived">{{c.semester}}{{c.archived?' · 已归档':''}}</small></span></label><p v-if="!filteredPickerClasses.length" class="class-picker-empty">{{classes.length?'没有匹配的班级':'暂无可统计的班级'}}</p></fieldset>
     <footer><button type="button" @click="resetPendingClasses">{{tab==='classes'?'恢复默认':'重置范围'}}</button><button type="button" :disabled="tab==='classes'&&(pendingClassIds.length<2||pendingClassIds.length>4)" @click="applyClasses">应用</button></footer>
    </div></details></div>
   <label>教学任务<select aria-label="筛选教学任务" :value="q.taskId||''" @change="set({taskId:$event.target.value||undefined})"><option value="">全部已发布任务</option><option v-for="t in taskOptions" :key="t.id" :value="String(t.id)">{{t.title}}</option></select></label>
   <label v-if="tab==='overview'||tab==='intervention'">评价维度<select aria-label="分析评价维度" :value="ability.id" @change="set({abilityId:$event.target.value})"><option v-if="!options.length" value="">暂无完整评分</option><option v-for="a in options" :key="a.id" :value="a.id">{{a.name}}</option></select></label>
   <label v-if="tab==='roles'">训练岗位<select aria-label="分析训练岗位" :value="q.roleId||''" @change="set({roleId:$event.target.value||undefined})"><option value="">全部岗位</option><option v-for="j in jobs" :key="j.id" :value="String(j.id)">{{j.name}}</option></select></label>
  </form>
  <div class="analytics-context"><span>{{from}} ～ {{to}} · 当前有效成员 {{students.length}}人（跨班去重）</span><button class="analytics-link" @click="set({classIds:undefined,classId:undefined,taskId:undefined,roleId:undefined,abilityId:undefined})">重置范围</button></div>
  <p class="analytics-data-note">仅统计所带班级的教学训练；自主训练与求职意向暂不纳入。不同评分方案分别分析。</p>
  <p v-if="reportLoadError" class="analytics-warning" role="alert">部分报告评分加载失败，能力分析可能不完整。<button @click="$emit('reload')">重新读取报告</button></p>
  <p v-if="rangeError" class="analytics-empty" role="alert">{{rangeError}}</p>
  <template v-else>
   <div v-if="tab==='overview'" class="analytics-grid">
    <section><h2>训练覆盖趋势</h2><p>每周至少1次有效教学训练的当前成员 / 当前成员。未还原历史入班名单。</p><AnalyticsChart :points="trend" :series="[{key:'coverage',name:'教学训练覆盖率'}]" percent label="每周教学训练覆盖率" @select="openRecords"/></section>
    <section><h2>有效训练量趋势</h2><p>按周展示获授权的有效教学训练量；自主训练数据尚未开放。</p><AnalyticsChart :points="trend" :series="[{key:'teacherTask',name:'教师任务训练'}]" stack label="每周有效教学训练量" @select="openRecords"/></section>
    <section><h2>到期任务按期完成率</h2><p>按期满足次数要求的分配 / 对应周已到期分配，排除减免与手动结束。</p><AnalyticsChart :points="trend" :series="[{key:'onTime',name:'按期完成率'}]" percent label="每周到期任务按期完成率" @select="openTasks"/></section>
    <section><h2>{{ability.name||'评价维度'}}目标达成趋势</h2><p>学生等权，采用每人截至当周最近一次有效评分；最大同方案组不足5人不绘制。版本变化断线。</p><AnalyticsChart :points="trend" :series="[{key:'achievement',name:'目标达成率'}]" percent sample label="评分维度目标达成趋势" @select="openRecords"/></section>
   </div>
   <template v-if="tab==='classes'"><p v-if="comparison.length<2||comparison.length>4" class="analytics-empty">班级对比至少选择2个、最多4个班级。</p><div v-else class="analytics-grid">
    <section><h2>班级训练参与率</h2><p>当前成员在所选周期参与有效教学训练的比例，按班级自然顺序展示。</p><div v-for="c in comparison" :key="c.id" class="analytics-bar-row"><RouterLink :to="classLink(c.id)">{{c.name}}</RouterLink><div class="analytics-track"><i :style="{width:(c.participation||0)+'%'}"/></div><span>{{c.participation==null?'数据不足':fmt(c.participation)+'%'}}</span></div><div class="analytics-table-scroll"><table><thead><tr><th>班级</th><th>当前成员</th><th>人均有效训练</th></tr></thead><tbody><tr v-for="c in comparison" :key="c.id"><td>{{c.name}}</td><td>{{c.n}}人</td><td>{{fmt(c.frequency)}}次</td></tr></tbody></table></div></section>
    <section><h2>班级任务执行结构</h2><p>所选周期内到期任务，按个人实际截止时间统计。</p><div v-for="c in comparison" :key="c.id" class="analytics-execution"><RouterLink :to="classLink(c.id)">{{c.name}}</RouterLink><ExecutionBar :stats="c.execution"/></div></section>
    <section><h2>评价维度目标差距矩阵</h2><p>同方案当前分－目标分；不混合不同岗位与权重。未选维度或样本不足保留缺失。</p><div class="analytics-table-scroll"><table><thead><tr><th>班级</th><th v-for="a in options" :key="a.id">{{a.name}}</th></tr></thead><tbody><tr v-for="c in comparison" :key="c.id"><td>{{c.name}}</td><td v-for="a in c.abilities" :key="a.id">{{signed(a.gap)}}<small>{{sampleNote(a)}}</small></td></tr></tbody></table></div></section>
    <section><h2>自主 / 教师任务训练结构</h2><p>当前接口仅提供教学任务记录，不能据此推算自主训练为0或教学占比100%。</p><div v-for="c in comparison" :key="c.id" class="analytics-execution"><strong>{{c.name}}</strong><p>教学有效训练 {{c.valid}}次 · 自主训练：未授权</p><div class="analytics-track"><i :style="{width:(maxClassValid?c.valid/maxClassValid*100:0)+'%'}"/></div></div></section>
   </div></template>
   <div v-if="tab==='intervention'" class="analytics-grid">
    <section><h2>训练来源变化</h2><p>教学训练按周展示；缺少自主训练数据，暂不生成来源比例。</p><AnalyticsChart :points="trend" :series="[{key:'teacherTask',name:'教师任务训练'}]" stack label="教学训练来源时间趋势" @select="openRecords"/></section>
    <section><h2>到期任务执行结构</h2><ExecutionBar :stats="due"/><p>只包含所选周期内已经到期的分配，不等于所有任务的当前完成率。</p></section>
    <section><h2>任务完成前后可比表现</h2><p>任务开始前最近一次与满足次数要求后14天内最近一次同岗位、同模型、同评分方案的 {{ability.name||'所选维度'}} 评分。</p><p>完成学生 {{pairs.completed}}人 · 同口径可比 {{pairs.n}}人</p><dl v-if="pairs.n>=5" class="analytics-values"><dt>完成前可比值</dt><dd>{{fmt(pairs.before)}}</dd><dt>完成后可比值</dt><dd>{{fmt(pairs.after)}}</dd><dt>前后统计差值</dt><dd>{{signed(pairs.diff)}}</dd></dl><p v-else class="analytics-empty">暂无足够数据生成聚合差值（至少5人）。</p><p v-if="pairs.n>=5&&pairs.n<10" class="analytics-warning">样本较少，仅供参考</p><p class="analytics-warning">该变化为任务完成前后可比训练记录的统计差值，不代表任务本身造成该变化。</p></section>
    <section><h2>后续表现变化分布</h2><p>沿用成长判定：同方案至少6次有效训练，不能凭前后两次评分判断成长。</p><dl class="analytics-values"><template v-for="x in outcomes" :key="x.label"><dt>{{x.label}}</dt><dd>{{x.count}}人</dd></template></dl></section>
    <section class="analytics-wide"><div class="analytics-section-head"><h2>相关训练任务</h2><button class="analytics-link" @click="openTasks()">查看全部任务 →</button></div><div class="analytics-table-scroll"><table><thead><tr><th>任务</th><th>班级</th><th>截止时间</th><th>当前已完成分配</th><th>操作</th></tr></thead><tbody><tr v-for="t in tasksInRange" :key="t.id"><td>{{t.title}}</td><td>{{t.className}}</td><td>{{t.deadline?.slice(0,10)}}</td><td>{{(t.assignments||[]).filter(a=>!a.exempt&&a.completionStatus==='COMPLETED').length}}</td><td><RouterLink :to="taskLink(t.id)">查看任务 →</RouterLink></td></tr></tbody></table></div><p v-if="!tasksInRange.length" class="analytics-empty">所选范围暂无相关训练任务。</p></section>
   </div>
   <div v-if="tab==='roles'" class="analytics-grid">
    <section><h2>训练岗位样本分布</h2><p>按每位学生在所选周期最近一次教学训练岗位去重。学生目标岗位未开放，不能将此图解释为求职意向。</p><div v-for="j in (showAllRoles?roleRows:roleRows.slice(0,5))" :key="j.id" class="analytics-bar-row"><button class="analytics-link" @click="set({roleId:String(j.id)})">{{j.name}}</button><div class="analytics-track"><i :style="{width:pct(j.count,roleRows.reduce((n,r)=>n+r.count,0))+'%'}"/></div><span>{{j.count}}人</span></div><button v-if="roleRows.length>5" @click="showAllRoles=!showAllRoles">{{showAllRoles?'收起':'展开全部岗位'}}</button><p v-if="!roleRows.length" class="analytics-empty">所选周期暂无训练岗位样本。</p></section>
    <section><h2>评价维度整体目标差距</h2><AbilityTable :rows="roleAbilities"/><p>各维度按最大同岗位、同方案组展示，学生等权；不同岗位不混合为全局平均。</p></section>
    <section><h2>岗位能力结构</h2><p v-if="!q.roleId" class="analytics-empty">请选择具体训练岗位，再查看其实际评分维度。</p><template v-else><AbilityTable :rows="roleAbilities"/><p>只展示报告真实记录的模块，不补造 Java / Spring 等细项。</p><RouterLink :to="{path:'/teacher/training-records',query:{...baseQuery(),jobId:q.roleId}}">查看该岗位记录 →</RouterLink></template></section>
    <section><h2>岗位 × 评价维度差距矩阵</h2><div class="analytics-table-scroll"><table><thead><tr><th>岗位</th><th v-for="a in options" :key="a.id">{{a.name}}</th></tr></thead><tbody><tr v-for="j in jobs" :key="j.id"><td>{{j.name}}</td><td v-for="a in abilityRows(history.filter(r=>r.jobId===j.id))" :key="a.id">{{signed(a.gap)}}<small>{{sampleNote(a)}}</small></td></tr></tbody></table></div></section>
   </div>
  </template>
  <TeacherDrawer :open="definitionsOpen" title="指标与计算口径" @close="definitionsOpen=false"><dl class="analysis-definitions"><template v-for="d in definitions" :key="d[0]"><dt>{{d[0]}}</dt><dd>{{d[1]}}</dd></template></dl></TeacherDrawer>
  <TeacherDrawer :open="exportOpen" title="导出分析数据" @close="exportOpen=false"><form class="analytics-export-form" @submit.prevent="download"><p>{{tabs.find(t=>t.id===tab).name}} · {{from}}～{{to}}</p><label>导出范围<select v-model="exportScope"><option value="view">当前分析视图</option><option value="tab">当前 Tab 全部数据</option><option value="scope">当前筛选范围数据</option></select></label><label>文件格式<select v-model="exportFormat"><option value="xlsx">Excel (.xlsx)</option><option value="csv">CSV (.csv)</option></select></label><fieldset><legend>包含内容</legend><label><input v-model="includeSummary" type="checkbox"/>汇总数据</label><label><input v-model="includeDetails" type="checkbox"/>训练明细</label><p>筛选范围、统计口径与缺失信息始终附带。</p></fieldset><label>文件名<input v-model="fileName" required maxlength="100"/></label><p v-if="exportError" role="alert">{{exportError}}</p><p v-if="exportSuccess" role="status">文件已生成并开始下载。</p><button class="analytics-primary" :disabled="rangeError||(!includeSummary&&!includeDetails)">导出文件</button></form></TeacherDrawer>
 </div>
</template>
<script setup>
import {computed,ref,watch,h,defineComponent,onMounted,onUnmounted} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import AnalyticsChart from './AnalyticsChart.vue'
import TeacherDrawer from './TeacherDrawer.vue'
import {stamp,dayKey,pct,allocations,completionAt,execution,abilityAggregate,moduleOptions,weekly,versionKey,studentGrowth} from '../../services/teachingAnalysis.js'
import {workbook,csv} from '../../services/analyticsExport.js'
import '../../assets/styles/analytics.css'
const props=defineProps({classes:Array,tasks:Array,reports:Array,people:Array,reportLoadError:Boolean});defineEmits(['reload'])
const route=useRoute(),router=useRouter(),q=computed(()=>route.query),tabs=[{id:'overview',name:'趋势总览'},{id:'classes',name:'班级对比'},{id:'intervention',name:'训练与干预'},{id:'roles',name:'岗位与能力结构'}],tab=computed(()=>tabs.some(t=>t.id===q.value.tab)?q.value.tab:'overview'),timeRange=computed(()=>['30d','90d','semester','custom'].includes(q.value.timeRange)?q.value.timeRange:'30d'),today=dayKey(Date.now()),from=computed(()=>timeRange.value==='custom'?q.value.from||dayKey(Date.now()-29*86400000):timeRange.value==='semester'?today.slice(0,4)+(Number(today.slice(5,7))>=8?'-09-01':'-02-01'):dayKey(Date.now()-(timeRange.value==='90d'?89:29)*86400000)),to=computed(()=>timeRange.value==='custom'?q.value.to||today:today),start=computed(()=>stamp(from.value+'T00:00:00')),end=computed(()=>Math.min(Date.now(),stamp(to.value+'T23:59:59'))),rangeError=computed(()=>!Number.isFinite(start.value)||!Number.isFinite(end.value)||start.value>end.value?'请选择有效起止日期。':end.value-start.value>366*86400000?'单次分析最多366天。':''),classIds=computed(()=>q.value.classIds||q.value.classId?String(q.value.classIds||q.value.classId).split(',').filter(Boolean):tab.value==='classes'?props.classes.filter(c=>!c.archived).slice(0,4).map(c=>String(c.id)):[]),taskOptions=computed(()=>props.tasks.filter(t=>!classIds.value.length||classIds.value.includes(String(t.classId)))),scopedTasks=computed(()=>taskOptions.value.filter(t=>!q.value.taskId||String(t.id)===String(q.value.taskId)))
const students=computed(()=>[...new Map(props.people.filter(s=>!classIds.value.length||classIds.value.includes(String(s.classId))).map(s=>[s.id,s])).values()]),history=computed(()=>props.reports.filter(r=>scopedTasks.value.some(t=>t.id===r.taskId)&&r.state==='READY'&&stamp(r.submittedAt)>=start.value&&stamp(r.submittedAt)<=end.value)),options=computed(()=>moduleOptions(history.value)),ability=computed(()=>options.value.find(a=>a.id===q.value.abilityId)||options.value[0]||{id:'',name:''}),trend=computed(()=>rangeError.value?[]:weekly(history.value,scopedTasks.value,students.value,start.value,end.value,ability.value.id)),due=computed(()=>execution(scopedTasks.value,start.value,end.value)),tasksInRange=computed(()=>scopedTasks.value.filter(t=>stamp(t.startTime)<=end.value&&stamp(t.deadline)>=start.value)),jobs=computed(()=>[...new Map(history.value.map(r=>[r.jobId,{id:r.jobId,name:r.jobName}])).values()])
const abilityRows=reports=>options.value.map(a=>({...a,...abilityAggregate(reports,a.id)})),comparison=computed(()=>props.classes.filter(c=>classIds.value.length?classIds.value.includes(String(c.id)):!c.archived).map(c=>{const people=[...new Set(props.people.filter(s=>s.classId===c.id).map(s=>s.id))],records=history.value.filter(r=>r.classId===c.id);return {...c,n:people.length,valid:records.length,participation:pct(new Set(records.filter(r=>people.includes(r.studentId)).map(r=>r.studentId)).size,people.length),frequency:people.length?records.length/people.length:null,execution:execution(scopedTasks.value.filter(t=>t.classId===c.id),start.value,end.value),abilities:abilityRows(records)}})),maxClassValid=computed(()=>Math.max(0,...comparison.value.map(c=>c.valid)))
const roleRows=computed(()=>{const latest=new Map();for(const r of [...history.value].sort((a,b)=>stamp(a.submittedAt)-stamp(b.submittedAt)))latest.set(r.studentId,r);return jobs.value.map(j=>({...j,count:[...latest.values()].filter(r=>r.jobId===j.id).length})).filter(j=>j.count)}),showAllRoles=ref(false),roleAbilities=computed(()=>abilityRows(history.value.filter(r=>!q.value.roleId||String(r.jobId)===q.value.roleId)))
const comparisonHistory=computed(()=>props.reports.filter(r=>r.state==='READY'&&(!classIds.value.length||classIds.value.includes(String(r.classId)))&&stamp(r.submittedAt)<=end.value))
function pairData(){const completed=new Map();for(const a of allocations(scopedTasks.value)){const at=stamp(completionAt(a));if(a.completionStatus==='COMPLETED'&&at>=start.value&&at<=end.value&&(!completed.has(a.studentId)||at>completed.get(a.studentId).at))completed.set(a.studentId,{a,at})}const groups=new Map();for(const [studentId,{a,at}] of completed){const own=comparisonHistory.value.filter(r=>r.studentId===studentId&&r.jobId===a.task.jobId).sort((a,b)=>stamp(a.submittedAt)-stamp(b.submittedAt)),before=own.filter(r=>stamp(r.submittedAt)<stamp(a.task.startTime)).at(-1),after=own.filter(r=>stamp(r.submittedAt)>at&&stamp(r.submittedAt)<=at+14*86400000).at(-1),bm=before?.detailReport?.moduleScores?.find(m=>m.moduleCode===ability.value.id),am=after?.detailReport?.moduleScores?.find(m=>m.moduleCode===ability.value.id);if(!bm||!am||!Number.isFinite(bm.rawScore)||!Number.isFinite(am.rawScore))continue;const key=versionKey(before,bm);if(!key||key!==versionKey(after,am))continue;const group=groups.get(key)||[];group.push({before:bm.rawScore,after:am.rawScore,studentId});groups.set(key,group)}const chosen=[...groups.values()].sort((a,b)=>b.length-a.length)[0]||[],n=chosen.length,before=n>=5?chosen.reduce((n,p)=>n+p.before,0)/n:null,after=n>=5?chosen.reduce((n,p)=>n+p.after,0)/n:null;return {completed:completed.size,n,before,after,diff:n>=5?after-before:null,students:[...completed].map(([id,{at}])=>({id,at}))}}
const pairs=computed(pairData),outcomes=computed(()=>{const states=pairs.value.students.map(s=>studentGrowth(comparisonHistory.value.filter(r=>r.studentId===s.id&&stamp(r.submittedAt)>s.at&&stamp(r.submittedAt)<=s.at+14*86400000)).status);return [{label:'有效提升',count:states.filter(s=>s==='有效提升').length},{label:'基本稳定',count:states.filter(s=>s==='基本稳定').length},{label:'下降',count:states.filter(s=>['轻微下降','持续下降'].includes(s)).length},{label:'数据不足',count:states.filter(s=>s==='数据不足').length}]})
const fmt=v=>v==null?'数据不足':v.toFixed(1),signed=v=>v==null?'数据不足':(v>0?'+':'')+v.toFixed(1),sampleNote=a=>a.n+'人 · '+(a.versionLabel||'暂无可比版本')+(a.excluded?' · '+a.excluded+'人版本缺失或不同':'')
function set(values){router.replace({path:route.path,query:{...q.value,...values}})}
const classSearch=ref(''),classPicker=ref(null),pendingClassIds=ref([])
const filteredPickerClasses=computed(()=>props.classes.filter(c=>(c.name+' '+(c.semester||'')).toLowerCase().includes(classSearch.value.trim().toLowerCase())))
function closeClassPicker(){if(classPicker.value){classPicker.value.open=false;classPicker.value.querySelector('summary')?.focus()}}
function onClassPickerToggle(){if(classPicker.value?.open){pendingClassIds.value=[...classIds.value];classSearch.value=''}}
function onClassPickerOutside(event){if(classPicker.value&&!classPicker.value.contains(event.target))classPicker.value.open=false}
function resetPendingClasses(){pendingClassIds.value=tab.value==='classes'?props.classes.filter(c=>!c.archived).slice(0,4).map(c=>String(c.id)):[];classSearch.value=''}
function applyClasses(){if(tab.value==='classes'&&(pendingClassIds.value.length<2||pendingClassIds.value.length>4))return;set({classIds:pendingClassIds.value.join(',')||undefined,classId:undefined,taskId:undefined});closeClassPicker()}
onMounted(()=>document.addEventListener('pointerdown',onClassPickerOutside))
onUnmounted(()=>document.removeEventListener('pointerdown',onClassPickerOutside))
function toggleClass(id){const value=String(id);if(tab.value==='classes'&&pendingClassIds.value.length>=4&&!pendingClassIds.value.includes(value))return;pendingClassIds.value=pendingClassIds.value.includes(value)?pendingClassIds.value.filter(i=>i!==value):[...pendingClassIds.value,value]}
const baseQuery=()=>({classIds:classIds.value.join(',')||undefined,taskId:q.value.taskId,from:from.value,to:to.value,returnTo:route.fullPath}),classLink=id=>({path:'/teacher/classes/'+id,query:baseQuery()}),taskLink=id=>({path:'/teacher/tasks/'+id,query:baseQuery()})
function openRecords(p){router.push({path:'/teacher/training-records',query:{...baseQuery(),from:p?.date||from.value,to:p?.to||to.value}})}
function openTasks(p){router.push({path:'/teacher/tasks',query:{...baseQuery(),analyticsDue:p?'1':undefined,from:p?.date||from.value,to:p?.to||to.value}})}
const ExecutionBar=defineComponent({props:['stats'],setup:p=>()=>h('div',{class:'analytics-execution-bar'},[p.stats.total?h('div',{class:'analytics-stack'},['onTime','late','unfinished'].map((k,i)=>h('span',{style:{width:pct(p.stats[k],p.stats.total)+'%',background:['#177b57','#bd7428','#b54f48'][i]},title:['按期完成','逾期完成','未完成'][i]+'：'+p.stats[k]},p.stats[k]?Math.round(pct(p.stats[k],p.stats.total))+'%':''))):h('p','暂无可统计的已到期分配'),h('p',`按期完成 ${p.stats.onTime} · 逾期完成 ${p.stats.late} · 未完成 ${p.stats.unfinished}（人次）`),p.stats.unknown?h('p',`${p.stats.unknown}条完成时间缺失，未参与比例`):null])})
const AbilityTable=defineComponent({props:['rows'],setup:p=>()=>h('div',{class:'analytics-table-scroll'},h('table',[h('thead',h('tr',['评价维度','当前均值','目标均值','差距','可比样本'].map(t=>h('th',t)))),h('tbody',p.rows.map(a=>h('tr',[h('td',a.name),h('td',fmt(a.current)),h('td',fmt(a.target)),h('td',signed(a.gap)),h('td',sampleNote(a))])))]))})
const definitions=[['训练范围','只使用教师可访问的有效教学报告。自主训练缺少授权数据，不补0。'],['覆盖率','每周有有效教学训练的当前成员人数 / 当前有效成员；跨班去重，历史成员不冒充当前成员。'],['到期执行','按个人实际截止时间归周，排除减免与手动结束。第 minAttempts 次有效提交作为次数完成时间。'],['能力口径','每个学生最近一次实际选中维度的有效评分，按岗位、模型、规则、提示版本、权重和目标分组；取最大组，至少5人。'],['目标达成','同方案可比学生中原始分达到实际目标的人数占比；缺失目标不补75或80。'],['前后变化','任务开始前及次数完成后14天内最近一次同口径评分，无因果推断。'],['资料缺失','当前接口没有学生目标岗位、年级、专业筛选资料，暂不提供这些筛选项。']]
const definitionsOpen=ref(false),exportOpen=ref(false),exportScope=ref('view'),exportFormat=ref('xlsx'),includeSummary=ref(true),includeDetails=ref(false),fileName=ref('OfferPilot_数据分析'),exportError=ref(''),exportSuccess=ref(false)
watch(exportOpen,open=>{if(open){fileName.value='OfferPilot_'+tabs.find(t=>t.id===tab.value).name+'_'+from.value+'_'+to.value;exportSuccess.value=false;exportError.value=''}})
function download(){try{const all=exportScope.value==='scope',full=exportScope.value!=='view',rows=[['OfferPilot 教学分析'],['数据类型','真实教学记录'],['时间范围',from.value,to.value],['班级',classIds.value.join(',')||'全部'],['任务',q.value.taskId||'全部'],['导出范围',exportScope.value],['当前视图',tab.value],['口径','仅授权教学记录，自主记录及学生目标岗位未开放']];if(includeSummary.value){if(all||tab.value==='overview')for(const a of full?options.value:[ability.value]){rows.push(['趋势',a.name],['周开始','周结束','教学覆盖率%','有效教学次数','到期按期完成率%','能力达成率%','可比人数']);rows.push(...weekly(history.value,scopedTasks.value,students.value,start.value,end.value,a.id).map(p=>[p.date,p.to,p.coverage,p.teacherTask,p.onTime,p.achievement,p.n]))}if(all||tab.value==='classes'){rows.push(['班级','成员','参与率%','人均训练','有效教学次数','按期','逾期','未完成']);rows.push(...comparison.value.map(c=>[c.name,c.n,c.participation,c.frequency,c.valid,c.execution.onTime,c.execution.late,c.execution.unfinished]));for(const c of comparison.value){rows.push(['班级维度',c.name,'当前','目标','差距','样本']);rows.push(...c.abilities.map(a=>[a.name,c.name,a.current,a.target,a.gap,a.n]))}}if(all||tab.value==='intervention'){rows.push(['到期分配','按期','逾期','未完成','时间缺失'],[due.value.total,due.value.onTime,due.value.late,due.value.unfinished,due.value.unknown],['相关任务','班级','截止时间']);rows.push(...tasksInRange.value.map(t=>[t.title,t.className,t.deadline]));rows.push(['可比维度','人数','前值','后值','统计差值'],[ability.value.name,pairs.value.n,pairs.value.before,pairs.value.after,pairs.value.diff]);rows.push(...outcomes.value.map(o=>[o.label,o.count]))}if(all||tab.value==='roles'){rows.push(['训练岗位','最近训练样本人数']);rows.push(...roleRows.value.map(j=>[j.name,j.count]));for(const j of jobs.value.filter(j=>full||!q.value.roleId||String(j.id)===q.value.roleId)){rows.push(['岗位维度',j.name,'当前','目标','差距','样本']);rows.push(...abilityRows(history.value.filter(r=>r.jobId===j.id)).map(a=>[a.name,j.name,a.current,a.target,a.gap,a.n]))}}}if(includeDetails.value){rows.push(['报告ID','学生ID','学生','班级','任务','训练岗位','提交时间','规则版本']);rows.push(...history.value.filter(r=>full||tab.value!=='roles'||!q.value.roleId||String(r.jobId)===q.value.roleId).map(r=>[r.reportId,r.studentId,r.name,r.className,r.title,r.jobName,r.submittedAt,r.detailReport?.trainingContext?.provenance?.ruleVersion||'旧版未知']))}rows.push(['指标说明'],...definitions);const xlsx=exportFormat.value==='xlsx',blob=new Blob([xlsx?workbook(rows):csv(rows)],{type:xlsx?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=fileName.value.replace(/[\\/:*?"<>|]/g,'_')+'.'+exportFormat.value;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);exportSuccess.value=true}catch(e){exportError.value='导出失败：'+e.message}}
</script>
<style scoped>
.live-analytics{padding:0;max-width:none}.live-analytics .analytics-header{margin:0 0 24px}.live-analytics .analytics-tabs button{border:0;border-bottom:2px solid transparent;border-radius:0;background:none;padding:14px 8px;min-width:0;color:#52525b}.live-analytics .analytics-tabs button.active{border-bottom-color:#10b981;color:#047857}.analytics-grid>section{background:white;border-radius:12px}.analytics-data-note{font-size:13px;padding:12px 16px;background:#f0f5f1;margin-bottom:24px!important}.analytics-class-picker fieldset{max-width:calc(100vw - 48px)}.analysis-definitions dt{font-weight:600;margin:24px 0 8px}.analysis-definitions dd{margin:0;line-height:1.8;color:#52525b}.analytics-export-form input[type=checkbox]{min-height:20px;width:20px}.analytics-bar-row{grid-template-columns:minmax(80px,1fr) minmax(40px,2fr) auto}.analytics-bar-row>a,.analytics-bar-row>button{overflow-wrap:anywhere;min-width:0}
</style>
