<template><section class="assignment-tools"><h2>参与名单与补练安排</h2><p>补充分配给已加入学生；额外次数、个人截止或减免只影响所选学生，保留调整原因并通知学生。</p><form @submit.prevent="supplement"><label>尚未分配的学生<select v-model="studentId" required><option value="">选择学生</option><option v-for="m in unassigned" :key="m.studentId" :value="m.studentId">{{m.name}}</option></select></label><label>分配原因<input v-model.trim="supplementReason" required maxlength="500"/></label><button :disabled="saving||!unassigned.length">补充分配</button></form><form @submit.prevent="override"><label>调整学生<select v-model="assignmentId" required><option value="">选择任务参与者</option><option v-for="a in task.assignments" :key="a.id" :value="a.id">{{a.name}} · 有效 {{a.validCount}} 次</option></select></label><label>额外尝试次数<input v-model.number="extra" type="number" min="0" max="20" required/></label><label>个人截止（留空沿用任务截止）<input v-model="deadline" type="datetime-local"/></label><label class="check"><input v-model="exempt" type="checkbox"/>减免此学生的训练要求（不计完成率分母）</label><label>调整原因<input v-model.trim="reason" required maxlength="500"/></label><button :disabled="saving">保存补练安排</button></form><p v-if="error" class="notice error" role="alert">{{error}}</p></section></template>
<script setup>
import {computed,ref,onMounted,watch} from 'vue'
import {teaching} from '../../services/teachingApi'
const props=defineProps({task:Object,selectedAssignmentId:[String,Number]}),emit=defineEmits(['saved']),members=ref([]),studentId=ref(''),assignmentId=ref(''),extra=ref(0),deadline=ref(''),exempt=ref(false),reason=ref(''),supplementReason=ref(''),saving=ref(false),error=ref('')
const unassigned=computed(()=>members.value.filter(m=>m.state==='JOINED'&&m.accountStatus===1&&!props.task.assignments.some(a=>a.studentId===m.studentId)))
onMounted(async()=>{try{members.value=await teaching.members(props.task.classId)}catch(e){error.value=e.message}})
watch(()=>props.selectedAssignmentId,id=>{if(id)assignmentId.value=String(id)},{immediate:true})
watch(assignmentId,id=>{const a=props.task.assignments.find(a=>String(a.id)===String(id));extra.value=a?.extraAttempts||0;exempt.value=!!a?.exempt;deadline.value=a?.extraAttempts!=null&&a.effectiveDeadline!==props.task.deadline?String(a.effectiveDeadline).slice(0,16):'';reason.value=a?.overrideReason||''},{immediate:true})
async function save(action){saving.value=true;error.value='';try{await action();emit('saved')}catch(e){error.value=e.response?.data?.message||e.message}finally{saving.value=false}}
function supplement(){save(()=>teaching.supplement(props.task.id,{studentIds:[Number(studentId.value)],reason:supplementReason.value}))}
function override(){save(()=>teaching.override(props.task.id,assignmentId.value,{extraAttempts:extra.value,deadline:deadline.value||null,exempt:exempt.value,reason:reason.value}))}
</script>
