<template><section v-if="canReview||reviews.length||showEmpty||error" class="teaching-feedback"><h2>教师点评</h2><p v-if="loading">正在读取点评…</p><p v-if="error" role="alert">{{error}} <button @click="load">重试读取</button></p><article v-for="r in reviews" :key="r.id"><p>{{r.text}}</p><small>{{r.teacherName}} · {{String(r.createdAt).replace('T',' ')}}</small></article><p v-if="!loading&&!error&&!reviews.length">尚无已发布的教师点评。</p><form v-if="canReview" @submit.prevent="save"><label>发布给学生的点评<textarea v-model.trim="text" rows="4" maxlength="5000" required/></label><button :disabled="saving||!text">{{saving?'正在发布…':'发布点评'}}</button><p v-if="saved" role="status">点评已发布，学生会收到站内消息。</p></form></section></template>
<script setup>
import {ref,watch} from 'vue'
import {teaching} from '../../services/teachingApi'
const props=defineProps({reportId:[String,Number],canReview:Boolean,showEmpty:Boolean}),reviews=ref([]),loading=ref(false),saving=ref(false),text=ref(''),error=ref(''),saved=ref(false)
async function load(){loading.value=true;error.value='';try{reviews.value=await teaching.reviews(props.reportId)}catch(e){error.value=e.response?.data?.message||e.message}finally{loading.value=false}}
watch(()=>props.reportId,load,{immediate:true})
async function save(){saving.value=true;error.value='';try{await teaching.review(props.reportId,text.value);text.value='';await load();saved.value=true}catch(e){error.value=e.response?.data?.message||e.message}finally{saving.value=false}}
</script>
<style scoped>.teaching-feedback{padding:24px 0;border-top:1px solid #dde5df}.teaching-feedback h2{font-size:20px}.teaching-feedback p{line-height:1.8;white-space:pre-wrap}.teaching-feedback article{padding:18px 0;border-bottom:1px solid #dde5df}.teaching-feedback small{color:#647468}.teaching-feedback textarea{display:block;width:100%;font:inherit;padding:12px;border:1px solid #cbd8d0;border-radius:6px;margin:12px 0}.teaching-feedback button{min-height:44px;padding:10px 16px;background:#147b57;border:0;border-radius:6px;color:white;font:inherit;cursor:pointer}.teaching-feedback button:disabled{opacity:.5}.teaching-feedback :focus-visible{outline:2px solid #147b57;outline-offset:3px}</style>
