<template><div class="class-insights-route">
  <template v-if="route.query.demo!=='1'"><LiveClassInsights v-if="route.params.classId"/><TeachingPortal v-else/></template><AppLayout v-else><div class="ci">
    <RouterLink v-if="typeof q.returnTo==='string' &amp;&amp; /^\/teacher\/analytics(\?|$)/.test(q.returnTo)" :to="q.returnTo" class="back">← 返回数据分析</RouterLink><RouterLink v-else-if="!isList" :to="localLink('/teacher/classes')" class="back">← 返回班级列表</RouterLink>
    <header class="ci-header"><div><h1>{{ isList ? '班级洞察' : currentClass?.name || '班级详情' }}</h1><p>{{ isList ? '查看所带班级的训练参与、任务执行与近期学生状态' : currentClass ? `${summary.students.length}名已加入学生 · ${currentClass.grade} · ${currentClass.major}` : '查看班级分析与教学事务' }}</p><p v-if="isList && demo" class="scope-note">{{ semesterName }} · 共{{ cards.length }}个教学班 · {{ cards.reduce((n,c) => n + c.summary.students.length, 0) }}名已加入学生</p></div>
      <div class="controls"><label>学期<select :disabled="!demo" :value="q.semester || '2026-1'" @change="set('semester',$event.target.value)"><option v-for="s in semesters" :key="s.id" :value="s.id">{{ s.name }}</option></select></label><template v-if="isList"><label>排序<select :disabled="!demo" :value="q.sort || 'attention'" @change="set('sort',$event.target.value)"><option value="attention">需要关注优先</option><option value="name">班级名称</option><option value="participation">训练参与率</option></select></label><label>搜索<input :disabled="!demo" :value="q.search || ''" @input="set('search',$event.target.value)" placeholder="搜索班级名称" aria-label="搜索班级名称" /></label></template><template v-else><RouterLink :to="localLink(`/teacher/classes/${route.params.classId}/members`)">成员管理</RouterLink><RouterLink class="primary" :to="destination('/teacher/tasks/create')">发布训练任务</RouterLink></template></div>
    </header>
    <div class="mode-notice" role="status"><span>{{ demo ? `演示模式 · 示例截至${referenceDate}，操作只保存在本机，不写入真实系统。` : '真实模式 · 当前服务尚未提供班级、评分明细及成员管理接口。' }}</span><button @click="switchMode">{{ demo ? '切换真实数据' : '查看演示效果' }}</button></div>
    <section v-if="!demo" class="empty-panel"><h2>班级洞察尚未接入真实数据</h2><p>现有教师总览接口无法区分班级与成员关系，暂不能生成班级分析或执行成员修改。</p><button class="primary" @click="switchMode">查看完整演示流程</button><RouterLink to="/teacher/dashboard">返回教学总览</RouterLink></section>
    <section v-else-if="loadError" class="empty-panel" role="alert"><h2>班级数据读取失败</h2><p>{{loadError}}</p><button @click="load">重试读取</button></section><template v-else-if="isList">
      <div class="class-grid"><article v-for="c in cards" :key="c.id" class="class-card"><div class="card-title"><h2>{{ c.name }}</h2><span class="tag" :class="{ danger: c.summary.declining > 0 }">{{ c.summary.declining || c.summary.insufficient ? '需要关注' : '当前无重点关注' }}</span></div><p class="muted">{{ c.summary.students.length }}名已加入 · {{ c.grade }} · {{ c.major }}</p><div class="card-metrics"><div><span>训练参与率</span><strong>{{ c.summary.participation }}%</strong><small>{{ c.summary.trained }} / {{ c.summary.students.length }}人</small></div><div><span>任务完成率</span><strong>{{ c.summary.completion === null ? '—' : c.summary.completion + '%' }}</strong><small>{{ c.summary.done }} / {{ c.summary.total }}人次</small></div><div><span>训练不足</span><strong class="warm">{{ c.summary.insufficient }}人</strong><small>{{periodLabel}}0～1次训练</small></div><div><span>持续下降</span><strong :class="{ red: c.summary.declining > 0 }">{{ c.summary.declining }}人</strong><small>复用同岗位成长规则</small></div></div><div class="class-focus"><div><small>当前最大目标差距 · {{abilityPeriodLabel}}</small><strong>{{ c.summary.ability[0]?.value === null ? '暂无完整能力数据' : c.summary.ability[0]?.name }} <span v-if="c.summary.ability[0]?.value !== null" class="warm">{{ signed(c.summary.ability[0]?.value - 80) }}</span></strong></div><p>{{ c.summary.declining ? `${c.summary.declining}名学生持续下降，建议查看成长证据` : `${c.summary.insufficient}名学生训练不足，建议关注参与情况` }}</p></div><div class="card-actions"><RouterLink class="primary" :to="localLink(`/teacher/classes/${c.id}`, { search: undefined, sort: undefined })">查看班级</RouterLink><RouterLink :to="localLink(`/teacher/classes/${c.id}/members`, { search: undefined, sort: undefined })">成员管理</RouterLink></div></article></div><div v-if="!cards.length" class="empty-panel"><h2>没有符合条件的班级</h2><p>可清除搜索，或切换学期。</p><button @click="clearList">重置筛选</button></div>
    </template>
    <section v-else-if="!currentClass" class="empty-panel"><h2>未找到该班级</h2><p>班级标识不存在，请从班级列表重新选择。</p><RouterLink :to="localLink('/teacher/classes')">返回班级列表</RouterLink></section>
    <template v-else>
      <nav class="analysis-tabs" aria-label="班级分析"><RouterLink v-for="item in tabs" :key="item.id" :class="{ active: tab === item.id }" :to="localLink(route.path,{tab:item.id,page:undefined,search:undefined,quadrant:undefined,range:undefined})">{{ item.name }}</RouterLink></nav>
      <div class="section-heading"><div><h2>{{ tabs.find(t=>t.id===tab).name }}</h2><p v-if="tab==='ability'">同版本样本{{ comparableAbilityStudents.length }} / {{ summary.students.length }}人 · 每名学生最近最多3次有效评分等权计算</p><p v-else-if="tab==='students'">训练{{ periodLabel }} · 能力{{ abilityPeriodLabel }} · 散点{{ summary.samples }}人 / 表格{{ summary.students.length }}人</p><p v-else>训练{{ periodLabel }} · {{ summary.trained }}名学生参与 · {{ summary.records.length }}条有效训练记录</p></div><div class="controls"><label>{{ tab==='ability' ? '能力周期' : '训练周期' }}<select :value="tab==='ability' ? q.abilityPeriod || q.period || '30d' : q.period || '30d'" @change="set(tab==='ability' ? 'abilityPeriod' : 'period',$event.target.value)"><option value="7d">近7天</option><option value="30d">近30天</option><option value="90d">近90天</option><option value="semester">本学期</option></select></label><label v-if="tab==='training'">训练形式<select :value="q.trainingType || ''" @change="set('trainingType',$event.target.value)"><option value="">全部训练形式</option><option>AI虚拟面试</option><option>专项训练</option></select></label><label v-if="tab!=='training'">岗位<select :value="q.position || ''" @change="set('position',$event.target.value)"><option value="">全部岗位</option><option v-for="p in positions" :key="p">{{ p }}</option></select></label><button class="text" @click="drawer={type:'rules'}">数据口径</button></div></div>
      <template v-if="tab==='overview'">
        <div class="summary-grid"><RouterLink v-for="m in overviewMetrics" :key="m.title" :to="m.link" class="summary-card"><h3>{{ m.title }}</h3><strong :class="m.tone">{{ m.value }}</strong><p>{{ m.note }}</p><span>{{ m.action }}</span></RouterLink></div>
        <div class="analysis-grid"><section class="panel"><div class="panel-head"><div><h3>班级训练参与趋势</h3><p>{{ periodLabel }}每日参与训练的学生人数</p></div><RouterLink :to="destination('/teacher/training-records')">查看训练记录</RouterLink></div><ClassChart :points="trend" label="班级每日训练参与学生数" @select="date=>goRecords({date})" /></section><section class="panel"><div class="panel-head"><div><h3>当前能力表现</h3><p>通用能力 · {{ abilityPeriodLabel }} · {{ summary.samples }}名同版本有效样本 · {{summary.abilityVersion}}</p></div><RouterLink :to="localLink(route.path,{tab:'ability'})">完整能力分析</RouterLink></div><template v-if="summary.samples"><p>当前最大目标差距：{{summary.ability[0]?.name}} {{signed(summary.ability[0]?.value-80)}}分（演示目标80）。</p><button @click="setAbility(summary.ability[0]?.name)">查看能力依据 →</button></template><p v-if="!summary.samples" class="empty">当前周期暂无完整能力数据</p></section>
          <section class="panel"><div class="panel-head"><h3>任务执行情况</h3><RouterLink :to="localLink(route.path,{tab:'training'})">全部任务</RouterLink></div><div class="table-scroll"><table><thead><tr><th>任务名称</th><th>完成率</th><th>已完成 / 应完成</th><th>逾期人数</th><th>截止时间</th><th>操作</th></tr></thead><tbody><tr v-for="t in summary.rows.slice(0,4)" :key="t.id"><td>{{ t.name }}</td><td>{{ t.rate }}%</td><td>{{ t.completed }} / {{ t.total }}</td><td :class="{red:t.overdue}">{{ t.overdue }}</td><td>{{ t.deadline.slice(5) }}</td><td><RouterLink :to="destination(`/teacher/tasks/${t.id}`)">详情</RouterLink></td></tr></tbody></table></div><p v-if="!summary.rows.length" class="empty">当前周期暂无任务</p></section>
          <section class="panel"><div class="panel-head"><h3>岗位分布</h3><RouterLink :to="localLink(route.path,{tab:'students'})">查看学生</RouterLink></div><button v-for="p in positionDistribution" :key="p.name" class="position-row" @click="setPositionStudents(p.name)"><span>{{ p.name }}</span><div class="bar-track"><i :style="{width:`${pct(p.count,summary.students.length)}%`}"></i></div><span>{{ p.count }}人</span><small>{{ pct(p.count,summary.students.length) }}%</small></button><p v-if="!positionDistribution.length" class="empty">当前范围暂无学生</p></section></div>
      </template>
      <template v-else-if="tab==='ability'">
        <div class="ability-scope"><button :class="{chosen:abilityScope==='common'}" @click="set('scope','common')">通用能力</button><button :disabled="!q.position" :class="{chosen:abilityScope==='specialty'}" @click="set('scope','specialty')">岗位专项能力</button><span v-if="!q.position">选择具体岗位后可查看专项能力</span></div>
        <div class="analysis-grid"><section class="panel"><h3>能力差距排行</h3><p class="muted">班级当前平均与目标80分的差距</p><button v-for="a in abilityMetrics" :key="a.name" class="ability-bar" :class="{selected:selectedAbility===a.name}" @click="selectAbility(a.name)"><span>{{ a.name }}</span><div class="bar-track"><i :style="{width:`${a.value||0}%`}"></i><b style="left:80%"></b></div><span>{{ decimal(a.value) }} / 80</span><small class="warm">{{ signed(a.value===null?null:a.value-80) }}</small></button></section><section class="panel"><h3>{{ selectedAbility }} · 学生分布</h3><p class="muted">有效样本{{ scoredForAbility.length }}人 · 点击区间筛选矩阵</p><button v-for="b in scoreBuckets" :key="b.key" class="distribution-row" :class="{selected:q.range===b.key}" @click="set('range',q.range===b.key?'':b.key)"><span>{{ b.label }}</span><div class="bar-track"><i :style="{width:`${pct(bucketCount(b),scoredForAbility.length)}%`}"></i></div><span>{{ bucketCount(b) }}人</span><small>{{ pct(bucketCount(b),scoredForAbility.length) }}%</small></button><p v-if="!scoredForAbility.length" class="empty">该能力暂无有效评分</p></section></div>
        <section class="panel"><div class="panel-head"><div><h3>学生能力矩阵</h3><p>{{ matrixRows.length }}名符合条件的学生 · 未评分显示“—”</p></div><div class="controls"><label>关注状态<select :value="q.focus||''" @change="set('focus',$event.target.value)"><option value="">全部学生</option><option value="below">明显短板</option><option value="near">接近目标</option><option value="reached">已达标</option><option value="missing">暂无数据</option></select></label><label>排序<select :value="q.sort||'attention'" @change="set('sort',$event.target.value)"><option value="attention">需要关注优先</option><option value="ability">选中能力由低到高</option><option value="name">姓名</option></select></label><input :value="q.search||''" @input="set('search',$event.target.value)" aria-label="搜索姓名或学号" placeholder="搜索姓名或学号" /></div></div><div class="selection-bar" v-if="selected.length"><span>已选择{{ selected.length }}名学生</span><RouterLink class="primary" :to="destination('/teacher/tasks/create',{students:selected.join(','),ability:selectedAbility})">发布针对性训练</RouterLink></div><div class="table-scroll"><table class="matrix"><thead><tr><th><input type="checkbox" aria-label="选择本页学生" :checked="allSelected" @change="selectPage($event.target.checked)" /></th><th>学生</th><th>学号</th><th>目标岗位</th><th v-for="a in abilityNames" :key="a" :class="{selected:selectedAbility===a}">{{ a }}<small>目标80</small></th><th>主要短板</th><th>最近训练</th><th>操作</th></tr></thead><tbody><tr v-for="s in pagedRows" :key="s.id"><td><input v-model="selected" type="checkbox" :value="s.id" :aria-label="`选择${s.name}`" /></td><td>{{ s.name }}</td><td>{{ s.number }}</td><td>{{ s.position }}</td><td v-for="a in abilityNames" :key="a" :class="['score-cell',tone(s[abilityScope]?.[a]),{selected:selectedAbility===a}]"><button class="text" @click="drawer={type:'ability',student:s,ability:a}">{{ decimal(s[abilityScope]?.[a]) }}</button></td><td>{{ weakest(s) }}</td><td>{{ shortDate(s.last) }}</td><td><button class="text" @click="drawer={type:'ability',student:s,ability:selectedAbility}">详情</button></td></tr></tbody></table></div><p v-if="!matrixRows.length" class="empty">没有符合当前区间与筛选的学生 <button @click="clearStudentFilters">清除筛选</button></p><div class="pagination"><span>共{{ matrixRows.length }}人</span><button :disabled="page===1" @click="set('page',page-1)">上一页</button><span>{{ page }}/{{ pages }}</span><button :disabled="page===pages" @click="set('page',page+1)">下一页</button></div></section>
      </template>
      <template v-else-if="tab==='training'">
        <div class="analysis-grid training-top"><section class="panel"><h3>学生训练频次分布</h3><p class="muted">{{ periodLabel }} · 共{{ summary.students.length }}名已加入学生</p><div class="ring-layout"><ClassChart kind="ring" :items="frequency" label="学生训练频次分布" unit="名学生" @select="frequencyDestination"/><div><button v-for="f in frequency" :key="f.key" class="ring-legend" @click="frequencyDestination(f.key)"><span>{{ f.name }}</span><strong>{{ f.value }}人</strong><small>{{ pct(f.value,summary.students.length) }}%</small></button></div></div></section><section class="panel"><h3>训练来源结构</h3><p class="muted">{{ summary.records.length }}条有效记录 · 点击来源查看明细</p><div class="source-layout"><button @click="goRecords({source:'学生自主'})"><span>学生自主训练</span><strong>{{ selfRecords }}次</strong><small>{{ pct(selfRecords,summary.records.length) }}%</small></button><ClassChart kind="semi" :items="sources" label="自主与教师任务训练来源比例" unit="条训练记录" @select="key=>goRecords({source:key==='self'?'学生自主':'教师任务'})"/><button @click="goRecords({source:'教师任务'})"><span>教师任务训练</span><strong>{{ teacherRecords }}次</strong><small>{{ pct(teacherRecords,summary.records.length) }}%</small></button></div></section></div>
        <div class="task-layout"><section class="panel"><div class="panel-head"><h3>任务执行情况</h3><div class="controls"><label>任务类型<select :value="q.taskType||''" @change="set('taskType',$event.target.value)"><option value="">全部任务类型</option><option>通用能力</option><option>岗位专项</option><option>综合训练</option></select></label><label>完成情况<select :value="q.taskState||''" @change="set('taskState',$event.target.value)"><option value="">全部任务</option><option value="overdue">存在逾期</option><option value="unfinished">尚未全部完成</option><option value="completed">已全部完成</option></select></label><input :value="q.search||''" @input="set('search',$event.target.value)" aria-label="搜索任务名称" placeholder="搜索任务名称" /></div></div><div class="table-scroll"><table><thead><tr><th><button class="text" @click="set('sort',q.sort==='name'?'':'name')">任务名称</button></th><th>类型</th><th><button class="text" @click="set('sort',q.sort==='rate'?'':'rate')">完成率</button></th><th>已完成</th><th>进行中</th><th>未开始</th><th>逾期人数</th><th>截止时间</th><th>操作</th></tr></thead><tbody><tr v-for="t in visibleTasks" :key="t.id"><td>{{ t.name }}</td><td>{{ t.type }}</td><td>{{ t.rate }}%</td><td>{{ t.completed }}</td><td>{{ t.ongoing }}</td><td>{{ t.notStarted }}</td><td><RouterLink v-if="t.overdue" class="red" :to="destination('/teacher/reviews',{tab:'overdue',taskId:t.id})">{{ t.overdue }}</RouterLink><span v-else>0</span></td><td>{{ t.deadline }}</td><td><RouterLink :to="destination(`/teacher/tasks/${t.id}`)">详情</RouterLink></td></tr></tbody></table></div><p class="scope-note">逾期人数是进行中或未开始的附加属性，不能重复加入应完成人数。</p><p v-if="!visibleTasks.length" class="empty">没有符合条件的任务 <button @click="clearTasks">清除筛选</button></p></section><section class="panel task-summary"><h3>任务执行总览</h3><p class="muted">当前筛选任务 · {{ executionTotal }}人次</p><div v-for="s in taskStates" :key="s.key" class="execution-stat"><span>{{ s.name }}</span><strong :class="{red:s.key==='overdue'}">{{ executionSummary[s.key] }}人次</strong><small>{{ pct(executionSummary[s.key],executionTotal) }}%</small></div><p class="scope-note">四类互斥，合计等于应完成人次。</p></section></div>
      </template>
      <template v-else>
        <div class="student-layout"><section class="panel"><div class="panel-head"><div><h3>训练投入 × 通用能力目标达成度</h3><p>训练{{ periodLabel }} / 能力{{ abilityPeriodLabel }} · 当前散点{{ scatterStudents.length }}人 · 重叠点横向错开，次数以提示为准</p></div><span class="scope-note">2次训练 / 100%目标分界</span></div><ClassChart kind="scatter" :points="scatterStudents" :selected="highlight" label="训练次数与通用能力目标达成度" @select="highlightStudent" /></section><section class="panel"><h3>学生分布概览</h3><p class="muted">以{{ summary.completeSamples }}名完整能力样本计算</p><div class="quadrants"><button v-for="item in quadrants" :key="item.key" :class="{selected:q.quadrant===item.key}" @click="set('quadrant',q.quadrant===item.key?'':item.key)"><span>{{ item.name }}</span><strong>{{ summary.students.filter(s=>s.quadrant===item.key).length }}人</strong><small>{{ pct(summary.students.filter(s=>s.quadrant===item.key).length,summary.completeSamples) }}%</small></button></div><p class="scope-note">缺少完整能力评分的{{ summary.students.length-summary.completeSamples }}人仍保留在明细表。</p></section></div>
        <section class="panel"><div class="panel-head"><h3>学生明细</h3><div class="controls"><label>关注状态<select :value="q.concern||''" @change="set('concern',$event.target.value)"><option value="">全部学生</option><option value="持续下降">持续下降</option><option value="当前任务逾期">任务逾期</option><option value="当前周期未训练">未训练</option><option value="当前周期仅1次训练">仅1次训练</option><option value="暂无完整能力数据">暂无能力数据</option></select></label><label>排序<select :value="q.sort||'attention'" @change="set('sort',$event.target.value)"><option value="attention">需要关注优先</option><option value="count">训练次数由少到多</option><option value="name">姓名</option></select></label><input :value="q.search||''" @input="set('search',$event.target.value)" aria-label="搜索姓名或学号" placeholder="搜索姓名或学号" /></div></div><div class="selection-bar"><span>共{{ studentRows.length }}名学生 · 已选择{{ selected.length }}名</span><RouterLink v-if="selected.length" class="primary" :to="destination('/teacher/tasks/create',{students:selected.join(',')})">为已选学生发布训练</RouterLink><button v-else disabled>为已选学生发布训练</button></div><div class="table-scroll"><table><thead><tr><th><input type="checkbox" aria-label="选择本页学生" :checked="allSelected" @change="selectPage($event.target.checked)"/></th><th>学生</th><th>学号</th><th>目标岗位</th><th>训练次数</th><th>通用能力达成度</th><th>近期变化</th><th>任务执行</th><th>主要关注点</th><th>最近训练</th><th>操作</th></tr></thead><tbody><tr v-for="s in pagedRows" :key="s.id" :data-student="s.id" :class="{highlight:s.id===highlight}" @mouseenter="highlight=s.id"><td><input v-model="selected" type="checkbox" :value="s.id" :aria-label="`选择${s.name}`"/></td><td>{{ s.name }}</td><td>{{ s.number }}</td><td>{{ s.position }}</td><td>{{ s.count }}次</td><td>{{ s.attainment===null?'—':s.attainment.toFixed(1)+'%' }}</td><td :class="{red:s.growth.status==='持续下降'}">{{ s.growth.status }}</td><td>{{ s.execution.filter(e=>e.state==='completed').length }} / {{ s.execution.length }}完成<span v-if="s.overdue" class="red"> · {{ s.overdue }}项逾期</span></td><td :title="s.reasons.join('；')">{{ s.concern }}</td><td>{{ shortDate(s.last) }}</td><td><button class="text" @click="drawer={type:'student',student:s}">详情</button></td></tr></tbody></table></div><p v-if="!studentRows.length" class="empty">没有符合条件的学生 <button @click="clearStudentFilters">清除筛选</button></p><div class="pagination"><span>共{{ studentRows.length }}人</span><button :disabled="page===1" @click="set('page',page-1)">上一页</button><span>{{ page }}/{{ pages }}</span><button :disabled="page===pages" @click="set('page',page+1)">下一页</button></div></section>
      </template>
    </template>
    <TeacherDrawer modal class="class-detail-window" :open="!!drawer" :title="drawer?.type==='rules'?'班级洞察数据口径':drawer?.student?.name || '学生详情'" @close="drawer=null"><template v-if="drawer?.type==='rules'"><section class="ci-rule-section"><h3>成员范围</h3><p>分析只统计已加入成员，待加入名单不参与训练与能力分母。</p></section><section class="ci-rule-section"><h3>能力统计方式</h3><p>训练与能力默认近30天，使用来源指定周期。每名学生按所选能力周期内最近最多3次当前有效模型评分计算，再按学生等权平均。班级均值和评分分布仅采用样本最多的同模型、同版本组，其他版本保留在学生明细中。</p></section><section class="ci-rule-section"><h3>训练与短板标准</h3><p>训练不足定义为当前周期0～1次。散点分界为2次训练及100%目标达成度。演示配置：四项通用能力目标均为80分。</p></section><section class="ci-rule-section"><h3>成长判定</h3><p>成长复用D03同岗位、同模型、同版本规则。能力样本不足与成长数据不足是不同概念。</p></section><section class="ci-rule-section"><h3>任务与数据边界</h3><p>任务逾期覆盖未完成人群；执行总览使用互斥状态。真实服务未接入时不采用示例数据补齐。</p></section></template><template v-else-if="drawer?.student"><p>学号{{ drawer.student.number }} · {{ drawer.student.position }}</p><p>当前周期{{ drawer.student.count }}次训练 · {{ drawer.student.growth.status }}</p><h3>完整关注原因</h3><p v-for="r in drawer.student.reasons" :key="r">{{ r }}</p><p v-if="!drawer.student.reasons.length">无明显问题</p><template v-if="drawer.type==='ability'"><h3>{{ drawer.ability }}</h3><p>当前值{{ decimal(drawer.student[abilityScope]?.[drawer.ability]) }} / 目标80</p><p>所选周期{{ abilityPeriodLabel }}，采用最近最多3次有效评分。</p></template><div class="drawer-actions"><RouterLink :to="destination(`/teacher/students/${drawer.student.id}`,drawer.type==='ability'?{tab:'ability',ability:drawer.ability,scope:abilityScope==='specialty'?'role':'common',period:q.abilityPeriod||q.period||'30d'}:{tab:'overview'})">学生详情</RouterLink><RouterLink :to="destination('/teacher/training-records',{student:drawer.student.id})">训练记录</RouterLink><RouterLink :to="destination('/teacher/growth',{student:drawer.student.id,period:q.abilityPeriod||q.period||'30d'})">成长证据</RouterLink></div></template></TeacherDrawer>
  </div></AppLayout>
</div></template>
<script setup>
import LiveClassInsights from './LiveClassInsights.vue'
import TeachingPortal from '../TeachingPortal.vue'
import {dailyTrend} from '../../services/teacherModel.js'
import {normalizeTeacherQuery,teacherContext,safeTeacherReturn} from '../../services/teacherContext.js'
import { computed, ref, watch, nextTick } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AppLayout from '../../components/layout/AppLayout.vue'
import TeacherDrawer from '../../components/teacher/TeacherDrawer.vue'
import ClassChart from '../../components/teacher/ClassChart.vue'
import { getClassDemo, classSummary, classStudents, commonAbilities, semesters, pct, inRange } from '../../services/classInsights'
import { positions, referenceDate } from '../../services/teacherModel'
import '../../assets/styles/class-insights.css'
const route=useRoute(), router=useRouter(), q=computed(()=>normalizeTeacherQuery(route.query)), demo=computed(()=>q.value.demo==='1'), isList=computed(()=>!route.params.classId)
const data=ref(null),loadError=ref(''), drawer=ref(null), selected=ref([]), highlight=ref('')
function load(){loadError.value='';try{data.value=demo.value?getClassDemo():null}catch(e){data.value=null;loadError.value=e.message}}
watch(demo,load,{immediate:true})
watch(()=>route.fullPath,()=>{drawer.value=null})
watch(()=>[route.params.classId,q.value.position,q.value.period,q.value.abilityPeriod,q.value.semester,q.value.search,q.value.focus,q.value.concern,q.value.quadrant,q.value.range,q.value.trainingType,q.value.scope,q.value.tab].join('|'),()=>{selected.value=[];highlight.value=''})
const tabs=[{id:'overview',name:'概览'},{id:'ability',name:'能力表现'},{id:'training',name:'训练与任务'},{id:'students',name:'学生表现'}]
const tab=computed(()=>tabs.some(t=>t.id===q.value.tab)?q.value.tab:'overview')
const currentClass=computed(()=>data.value?.classes.find(c=>c.id===route.params.classId))
const summary=computed(()=>data.value&&currentClass.value?classSummary(data.value,currentClass.value.id,q.value):{students:[],records:[],rows:[],ability:[],samples:0})
const semesterName=computed(()=>semesters.find(s=>s.id===(q.value.semester||'2026-1'))?.name||'')
const periodLabel=computed(()=>q.value.from?`${q.value.from}～${q.value.to}`:q.value.period==='7d'?'近7天':q.value.period==='90d'?'近90天':q.value.period==='semester'?'本学期':'近30天'),abilityPeriodLabel=computed(()=>(q.value.abilityPeriod||q.value.period)==='90d'?'近90天':(q.value.abilityPeriod||q.value.period)==='7d'?'近7天':q.value.from?`${q.value.from}～${q.value.to}`:(q.value.abilityPeriod||q.value.period)==='semester'?'本学期':'近30天')
const cards=computed(()=>{const rows=(data.value?.classes||[]).filter(c=>(!q.value.semester||c.semester===q.value.semester)&&(!q.value.search||c.name.includes(q.value.search))).map(c=>({...c,summary:classSummary(data.value,c.id,q.value)}));return rows.sort((a,b)=>q.value.sort==='name'?a.name.localeCompare(b.name):q.value.sort==='participation'?a.summary.participation-b.summary.participation:b.summary.declining-a.summary.declining||b.summary.insufficient-a.summary.insufficient)})
function localLink(path,extra={}){return{path,query:{...teacherContext(q.value),trainingType:q.value.trainingType,...extra}}}
function destination(path,extra={}){return{path,query:{...teacherContext(q.value),insights:'1',classId:currentClass.value?.id,class:currentClass.value?.name,returnClass:currentClass.value?.id,sourceTab:tab.value,returnTo:route.fullPath,type:q.value.trainingType||undefined,...extra}}}
function set(key,value){const query={...q.value,[key]:value||undefined};if(key!=='page')delete query.page;if(key==='period'||key==='abilityPeriod'){for(const k of ['from','to','analyticsFrom','analyticsTo','timeRange'])delete query[k]}router.replace({query})}
function switchMode(){router.replace({query:{demo:demo.value?undefined:'1'}})}
function clearList(){router.replace({query:{demo:'1'}})}
function clearStudentFilters(){router.replace({query:{...localLink(route.path).query,tab:tab.value}})}
const decimal=v=>Number.isFinite(v)?v.toFixed(1):'—',signed=v=>Number.isFinite(v)?`${v>0?'+':''}${v.toFixed(1)}`:'—',shortDate=v=>v?v.slice(0,10):'—'
const overviewMetrics=computed(()=>[{title:'训练参与率',value:summary.value.participation+'%',note:`${summary.value.trained} / ${summary.value.students.length}人 · ${periodLabel.value}`,action:'查看活跃情况',link:destination('/teacher/activity')},{title:'任务完成率',value:summary.value.completion===null?'—':summary.value.completion+'%',note:`${summary.value.done} / ${summary.value.total}人次`,action:'查看任务执行',link:localLink(route.path,{tab:'training'})},{title:'训练不足学生',value:summary.value.insufficient+'人',note:'当前训练周期内0～1次',tone:'warm',action:'查看这些学生',link:localLink(route.path,{tab:'students',concern:'训练不足'})},{title:'持续下降学生',value:summary.value.declining+'人',note:`同岗位成长 · ${abilityPeriodLabel.value}`,tone:summary.value.declining?'red':'',action:'查看成长情况',link:destination('/teacher/growth',{growth:'持续下降',period:q.value.abilityPeriod||q.value.period||'30d'})}])
const trend=computed(()=>dailyTrend(data.value,summary.value.records,q.value))
const positionDistribution=computed(()=>positions.map(name=>({name,count:summary.value.students.filter(s=>s.position===name).length})).filter(p=>p.count))
function setAbility(ability){router.replace({query:{...q.value,tab:'ability',ability,range:undefined,page:undefined}})}
function setPositionStudents(position){router.replace({query:{...q.value,tab:'students',position,page:undefined}})}
const abilityScope=computed(()=>q.value.scope==='specialty'&&q.value.position?'specialty':'common'),abilityNames=computed(()=>abilityScope.value==='common'?commonAbilities:['专业知识','岗位实践'])
const abilityStudents=computed(()=>summary.value.students)
const comparableAbilityStudents=computed(()=>{const groups=new Map();for(const s of abilityStudents.value.filter(s=>s[abilityScope.value])){const key=abilityScope.value==='common'?s.abilityVersion:s.specialtyVersion,rows=groups.get(key)||[];rows.push(s);groups.set(key,rows)}return [...groups.values()].sort((a,b)=>b.length-a.length)[0]||[]})
const abilityMetrics=computed(()=>abilityNames.value.map(name=>{const values=comparableAbilityStudents.value.filter(s=>Number.isFinite(s[abilityScope.value]?.[name])).map(s=>s[abilityScope.value][name]);return{name,value:values.length?values.reduce((a,b)=>a+b,0)/values.length:null}}).sort((a,b)=>(a.value??100)-(b.value??100)))
const selectedAbility=computed(()=>abilityNames.value.includes(q.value.ability)?q.value.ability:abilityMetrics.value[0]?.name||abilityNames.value[0])
function selectAbility(ability){router.replace({query:{...q.value,ability,range:undefined,page:undefined}})}
const scoreBuckets=[{key:'low',label:'低于60',min:0,max:60},{key:'medium',label:'60–69',min:60,max:70},{key:'near',label:'70–79',min:70,max:80},{key:'target',label:'80及以上',min:80,max:Infinity}]
const scoredForAbility=computed(()=>comparableAbilityStudents.value.filter(s=>Number.isFinite(s[abilityScope.value]?.[selectedAbility.value])))
const bucketCount=b=>scoredForAbility.value.filter(s=>s[abilityScope.value][selectedAbility.value]>=b.min&&s[abilityScope.value][selectedAbility.value]<b.max).length
const matchesSearch=s=>!q.value.search||`${s.name}${s.number}`.includes(q.value.search)
const priority=s=>['持续下降','当前任务逾期','当前周期未训练','当前周期仅1次训练','通用能力距目标至少10个百分点','暂无完整能力数据','无明显问题'].indexOf(s.concern)
const sortStudents=rows=>rows.sort((a,b)=>q.value.sort==='name'?a.name.localeCompare(b.name):q.value.sort==='count'?a.count-b.count:q.value.sort==='ability'?(a[abilityScope.value]?.[selectedAbility.value]??Infinity)-(b[abilityScope.value]?.[selectedAbility.value]??Infinity):priority(a)-priority(b))
const matrixRows=computed(()=>sortStudents(abilityStudents.value.filter(s=>{const values=s[abilityScope.value],v=values?.[selectedAbility.value],bucket=scoreBuckets.find(b=>b.key===q.value.range);return matchesSearch(s)&&(!bucket||Number.isFinite(v)&&v>=bucket.min&&v<bucket.max)&&(!q.value.focus||(q.value.focus==='missing'?!values:q.value.focus==='below'?values&&Object.values(values).some(v=>v<70):q.value.focus==='reached'?values&&Object.values(values).every(v=>v>=80):values&&Object.values(values).every(v=>v>=70)&&Object.values(values).some(v=>v<80)))})))
function weakest(s){const values=s[abilityScope.value];if(!values)return'暂无数据';const a=Object.entries(values).sort((a,b)=>a[1]-b[1])[0];return a[1]>=80?'—':`${a[0]}（${signed(a[1]-80)}）`}
const tone=v=>!Number.isFinite(v)?'missing':v<70?'below':v<80?'near':'reached'
const frequency=computed(()=>[{key:'0',name:'0次',value:summary.value.students.filter(s=>s.count===0).length},{key:'1',name:'1次',value:summary.value.students.filter(s=>s.count===1).length},{key:'2',name:'2次',value:summary.value.students.filter(s=>s.count===2).length},{key:'3-4',name:'3–4次',value:summary.value.students.filter(s=>s.count>=3&&s.count<=4).length},{key:'5+',name:'5次及以上',value:summary.value.students.filter(s=>s.count>=5).length}])
const selfRecords=computed(()=>summary.value.records.filter(r=>r.source==='self').length),teacherRecords=computed(()=>summary.value.records.filter(r=>r.source==='teacher').length),sources=computed(()=>[{key:'self',name:'学生自主',value:selfRecords.value},{key:'teacher',name:'教师任务',value:teacherRecords.value}])
function frequencyDestination(key){router.push(key==='0'?destination('/teacher/activity',{activity:'未训练'}):destination('/teacher/training-records',{frequency:key}))}
function clearTasks(){router.replace({query:{...q.value,search:undefined,taskState:undefined,taskType:undefined,page:undefined}})}
function goRecords(extra){router.push(destination('/teacher/training-records',extra))}
const visibleTasks=computed(()=>summary.value.rows.filter(t=>(!q.value.taskType||t.type===q.value.taskType)&&(!q.value.search||t.name.includes(q.value.search))&&(!q.value.taskState||(q.value.taskState==='overdue'?t.overdue>0:q.value.taskState==='completed'?t.total>0&&t.completed===t.total:t.completed<t.total))).sort((a,b)=>q.value.sort==='name'?a.name.localeCompare(b.name):q.value.sort==='rate'?a.rate-b.rate:0))
const taskStates=[{key:'completed',name:'已完成'},{key:'overdue',name:'已逾期'},{key:'ongoing',name:'进行中且未逾期'},{key:'notStarted',name:'未开始且未逾期'}]
const executionSummary=computed(()=>Object.fromEntries(taskStates.map(s=>[s.key,visibleTasks.value.reduce((n,t)=>n+t.mutual[s.key],0)]))),executionTotal=computed(()=>Object.values(executionSummary.value).reduce((a,b)=>a+b,0))
const quadrants=[{key:'low-below',name:'低训练 · 未达目标'},{key:'trained-below',name:'有训练 · 未达目标'},{key:'low-reached',name:'低训练 · 已达目标'},{key:'trained-reached',name:'有训练 · 已达目标'}]
const studentRows=computed(()=>sortStudents(summary.value.students.filter(s=>matchesSearch(s)&&(!q.value.quadrant||s.quadrant===q.value.quadrant)&&(!q.value.concern||(q.value.concern==='训练不足'?s.count<2:s.reasons.includes(q.value.concern))))))
const scatterStudents=computed(()=>studentRows.value.filter(s=>s.common))
const rows=computed(()=>tab.value==='ability'?matrixRows.value:studentRows.value),pages=computed(()=>Math.max(1,Math.ceil(rows.value.length/10))),page=computed(()=>Math.min(pages.value,Math.max(1,Number(q.value.page)||1))),pagedRows=computed(()=>rows.value.slice((page.value-1)*10,page.value*10)),allSelected=computed(()=>pagedRows.value.length>0&&pagedRows.value.every(s=>selected.value.includes(s.id)))
function selectPage(checked){selected.value=checked?[...new Set([...selected.value,...pagedRows.value.map(s=>s.id)])]:selected.value.filter(id=>!pagedRows.value.some(s=>s.id===id))}
watch(() => q.value.search, async value => { await nextTick(); if (tab.value === 'students' && value) highlight.value = studentRows.value[0]?.id || '' })
async function highlightStudent(id){highlight.value=id;const i=studentRows.value.findIndex(s=>s.id===id);if(i<0)return;await router.replace({query:{...q.value,page:Math.floor(i/10)+1}});await nextTick();document.querySelector(`[data-student="${id}"]`)?.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
</script>
