<template>
  <TeachingPortal v-if="route.query.demo!=='1'"/><AppLayout v-else><div class="ci">
    <RouterLink :to="backLink" class="back">← 返回{{ currentClass?.name || '班级列表' }}</RouterLink>
    <header class="ci-header"><div><h1>班级成员管理</h1><p>{{ currentClass?.name || '班级成员关系' }} · 仅管理加入与移出，不修改学生账号或目标岗位</p></div></header>
    <div class="mode-notice" role="status"><span>{{ demo ? '演示模式 · 添加、导入与移出只修改本机示例名单，不影响真实账号和历史资料。' : '真实模式 · 成员关系与导入接口尚未开放，未执行成员修改。' }}</span><button @click="switchMode">{{ demo ? '切换真实数据' : '查看演示效果' }}</button></div>
    <p v-if="message" class="feedback" role="status">{{ message }}</p>
    <section v-if="!demo" class="empty-panel"><h2>成员管理尚未接入真实服务</h2><p>添加、导入、加入处理与移出需要后端成员关系接口。演示模式可查看完整流程。</p><button class="primary" @click="switchMode">查看演示效果</button></section>
    <section v-else-if="!currentClass" class="empty-panel"><h2>未找到该班级</h2><RouterLink :to="{path:'/teacher/classes',query:{demo:'1'}}">返回班级列表</RouterLink></section>
    <template v-else>
      <div class="members-heading"><p>已加入 <strong>{{ joinedCount }}</strong> · 待加入 <strong class="warm">{{ pendingCount }}</strong> · 账号异常 <strong :class="{red:abnormalCount}">{{ abnormalCount }}</strong></p><div class="controls"><button @click="drawer={type:'history'}">查看导入记录</button><button @click="openAdd">添加成员</button><button class="primary" @click="openImport">批量导入</button></div></div>
      <section class="panel"><div class="controls member-filters"><label>加入状态<select :value="q.state||''" @change="set('state',$event.target.value)"><option value="">全部成员状态</option><option value="joined">已加入</option><option value="pending">待加入</option></select></label><label>岗位<select :value="q.position||''" @change="set('position',$event.target.value)"><option value="">全部岗位</option><option v-for="p in positions" :key="p">{{ p }}</option></select></label><label>账号状态<select :value="q.account||''" @change="set('account',$event.target.value)"><option value="">全部账号状态</option><option value="normal">正常</option><option value="inactive">未激活</option><option value="disabled">已停用</option></select></label><label>排序<select :value="q.sort||'name'" @change="set('sort',$event.target.value)"><option value="name">姓名</option><option value="recent">最近加入</option></select></label><input :value="q.search||''" @input="set('search',$event.target.value)" placeholder="搜索姓名或学号" aria-label="搜索姓名或学号" /></div>
      <div class="selection-bar" v-if="selected.length"><span>已选择{{ selected.length }}名成员</span><button class="danger-button" @click="confirmIds=[...selected]">批量移出名单</button><button @click="selected=[]">取消选择</button></div>
      <div class="table-scroll"><table><thead><tr><th><input type="checkbox" aria-label="选择本页成员" :checked="allSelected" @change="selectPage($event.target.checked)"/></th><th>学生</th><th>学号</th><th>目标岗位</th><th>加入状态</th><th>账号状态</th><th>加入方式</th><th>加入时间</th><th>操作</th></tr></thead><tbody><tr v-for="m in paged" :key="m.id"><td><input v-model="selected" type="checkbox" :value="m.id" :aria-label="`选择${m.student.name}`"/></td><td>{{ m.student.name }}</td><td>{{ m.student.number }}</td><td>{{ m.student.position }}</td><td :class="m.state==='pending'?'warm':'green'">{{ m.state==='joined'?'已加入':'待加入' }}</td><td :class="{red:m.account==='disabled',warm:m.account==='inactive'}">{{ accountNames[m.account] || '未知' }}</td><td>{{ m.method }}</td><td>{{ m.joinedAt || '—' }}</td><td><div class="member-actions"><button class="text" @click="drawer={type:'info',member:m}">{{ m.state==='pending'?'查看信息':'详情' }}</button><details><summary aria-label="更多成员操作">更多</summary><div class="member-menu"><RouterLink v-if="m.state==='joined'" :to="studentLink(m.student.id)">查看学生详情</RouterLink><button v-if="m.state==='pending'" @click="confirmJoin=m">重新处理加入状态</button><button class="red" @click="confirmIds=[m.id]">{{ m.state==='pending'?'移出待加入名单':'移出班级' }}</button></div></details></div></td></tr></tbody></table></div><p v-if="!filtered.length" class="empty">没有符合条件的成员 <button @click="reset">清除筛选</button></p><div class="pagination"><span>共{{ filtered.length }}名成员，当前显示{{ filtered.length?(page-1)*pageSize+1:0 }}–{{ Math.min(page*pageSize,filtered.length) }}条</span><label>每页<select v-model.number="pageSize"><option :value="12">12条</option><option :value="24">24条</option></select></label><button :disabled="page===1" @click="set('page',page-1)">上一页</button><span>{{ page }}/{{ pages }}</span><button :disabled="page===pages" @click="set('page',page+1)">下一页</button></div></section>
    </template>
    <TeacherDrawer modal class="member-detail-window" :open="!!drawer" :title="drawerTitle" @close="closeDrawer"><div class="ci ci-drawer">
      <template v-if="drawer?.type==='add'"><p>选择已有学生账号加入本班级待加入名单；不创建或修改学生账号。</p><label class="field">搜索已有学生<input v-model="directorySearch" placeholder="姓名或学号" aria-label="搜索已有学生"/></label><div class="directory-list"><label v-for="s in available.slice(0,20)" :key="s.id"><input v-model="toAdd" type="checkbox" :value="s.id"/><span>{{ s.name }} · {{ s.number }}<small>{{ s.position }}</small></span></label><p v-if="!available.length">没有符合条件的已有学生</p></div><p>当前显示最多20名，已选择{{ toAdd.length }}名。</p><footer class="member-dialog-actions"><button @click="closeDrawer">取消</button><button class="primary" :disabled="!toAdd.length" @click="saveAdd">添加到待加入名单</button></footer></template>
      <template v-else-if="drawer?.type==='import'"><p v-if="importError" class="red" role="alert">{{ importError }}</p><ol class="import-steps"><li :class="{active:importStep===1}">选择文件</li><li :class="{active:importStep===2}">预检查</li><li :class="{active:importStep===3}">结果</li></ol>
        <template v-if="importStep===1"><p>支持XLSX和CSV，最多1000行、2MB。只读取第一张工作表，前两列为姓名、学号；不接受公式。</p><div class="controls"><button @click="downloadCsv('班级成员导入模板.csv',[['姓名','学号']])">下载空白模板</button><button @click="downloadExample">下载可用演示示例</button></div><label class="field">选择文件<input type="file" accept=".xlsx,.csv" @change="readFile" aria-label="选择成员导入文件" :disabled="reading"/></label><p v-if="reading" role="status">正在解析文件…</p></template>
        <template v-else-if="importStep===2"><p>{{ filename }} · 可导入{{ validRows.length }}行，异常{{ badRows.length }}行。</p><p>检查通过后才会写入本机演示名单，异常行不会导入。</p><div class="table-scroll"><table><thead><tr><th>行</th><th>姓名</th><th>学号</th><th>检查结果</th></tr></thead><tbody><tr v-for="r in preview.slice(0,100)" :key="r.row"><td>{{ r.row }}</td><td>{{ r.name }}</td><td>{{ r.number }}</td><td :class="r.error?'red':'green'">{{ r.error || '可导入' }}</td></tr></tbody></table></div><p v-if="preview.length>100">预览前100行；确认与异常下载包含全部检查行。</p><div class="controls"><button @click="importStep=1;importError=''">重新选择</button><button v-if="badRows.length" @click="downloadErrors">下载异常名单</button><button class="primary" :disabled="!validRows.length || writing" @click="confirmImport">确认导入{{ validRows.length }}行</button></div></template>
        <template v-else><h3>演示导入已完成</h3><p>新增{{ importedCount }}名待加入成员，结果保存在本机，未修改真实系统。</p><p v-if="badRows.length">{{ badRows.length }}行异常未导入，可下载后更正。</p><button v-if="badRows.length" @click="downloadErrors">下载异常名单</button><button ref="importReturnButton" @click="closeDrawer">返回成员名单</button></template>
      </template>
      <template v-else-if="drawer?.type==='history'"><p>仅显示本机演示导入记录。</p><div v-for="item in imports" :key="item.id" class="history-row"><strong>{{ item.filename }}</strong><p>{{ item.count }}名待加入成员 · {{ item.at }}</p></div><p v-if="!imports.length">暂无导入记录</p></template>
      <template v-else-if="drawer?.type==='info'"><h3>{{ drawer.member.student.name }}</h3><dl><dt>学号</dt><dd>{{ drawer.member.student.number }}</dd><dt>目标岗位</dt><dd>{{ drawer.member.student.position }}</dd><dt>加入状态</dt><dd>{{ drawer.member.state==='joined'?'已加入':'待加入' }}</dd><dt>账号状态</dt><dd>{{ accountNames[drawer.member.account] }}</dd><dt>加入方式</dt><dd>{{ drawer.member.method }}</dd><dt>加入时间</dt><dd>{{ drawer.member.joinedAt||'尚未加入' }}</dd></dl><p>目标岗位由学生资料提供，此页不修改。</p></template>
    </div></TeacherDrawer>
    <TeacherDrawer class="member-detail-window member-confirm-window" :open="confirmIds.length>0 || !!confirmJoin" modal :title="confirmJoin?'确认处理加入状态':'确认移出成员名单'" @close="confirmIds=[];confirmJoin=null"><div class="ci ci-drawer"><template v-if="confirmJoin"><p>将{{ confirmJoin.student.name }}标记为已加入，仅改变本机演示成员关系。</p><p>真实流程需要后端验证邀请与账号权限，演示不会激活真实账号。</p><div class="controls"><button @click="confirmJoin=null">取消</button><button class="primary" @click="processJoin">确认演示加入</button></div></template><template v-else><p>即将移出{{ confirmIds.length }}名成员：{{ confirmNames }}。</p><p>只解除本班级成员关系或待加入状态，保留学生账号、训练记录、历史任务及报告。</p><div class="controls"><button @click="confirmIds=[]">取消</button><button class="danger-button" @click="processRemove">确认移出演示名单</button></div></template><p v-if="operationError" class="red" role="alert">{{ operationError }}</p></div></TeacherDrawer>
  </div></AppLayout>
</template>
<script setup>
import TeachingPortal from '../TeachingPortal.vue'
import {normalizeTeacherQuery,teacherContext,safeTeacherReturn} from '../../services/teacherContext.js'
import { computed, ref, watch, nextTick } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import AppLayout from '../../components/layout/AppLayout.vue'
import TeacherDrawer from '../../components/teacher/TeacherDrawer.vue'
import { addMembers, removeMembers, joinMember, validateImport } from '../../services/classInsights'
import {getClassDemo} from '../../services/teacherRoster.js'
import { readMemberFile, downloadCsv } from '../../services/classImport'
import { positions } from '../../services/teacherModel'
import '../../assets/styles/class-insights.css'
const route=useRoute(),router=useRouter(),q=computed(()=>normalizeTeacherQuery(route.query)),demo=computed(()=>q.value.demo==='1'),data=ref(null),drawer=ref(null),message=ref(''),selected=ref([]),pageSize=ref(12),confirmIds=ref([]),confirmJoin=ref(null),operationError=ref('')
watch(demo,()=>{data.value=demo.value?getClassDemo():null},{immediate:true})
watch(()=>[route.params.classId,q.value.search,q.value.state,q.value.position,q.value.account,q.value.sort].join('|'),()=>{selected.value=[]})
watch(()=>route.fullPath,()=>{closeDrawer();confirmIds.value=[];confirmJoin.value=null})
watch(()=>[confirmIds.value.length,confirmJoin.value],()=>{operationError.value=''})
const currentClass=computed(()=>data.value?.classes.find(c=>c.id===route.params.classId))
const allMembers=computed(()=>data.value?.members.filter(m=>m.classId===route.params.classId).map(m=>({...m,student:data.value.students.find(s=>s.id===m.studentId)})).filter(m=>m.student)||[])
const joinedCount=computed(()=>allMembers.value.filter(m=>m.state==='joined').length),pendingCount=computed(()=>allMembers.value.filter(m=>m.state==='pending').length),abnormalCount=computed(()=>allMembers.value.filter(m=>m.account==='disabled').length)
const accountNames={normal:'正常',inactive:'未激活',disabled:'已停用'}
const backLink=computed(()=>({path:demo.value&&currentClass.value?`/teacher/classes/${route.params.classId}`:'/teacher/classes',query:teacherContext(q.value)}))
function studentLink(id){return{path:`/teacher/students/${id}`,query:{...teacherContext(q.value),demo:'1',classId:route.params.classId,class:currentClass.value.name,returnTo:route.fullPath}}}
const filtered=computed(()=>allMembers.value.filter(m=>(!q.value.state||m.state===q.value.state)&&(!q.value.position||m.student.position===q.value.position)&&(!q.value.account||m.account===q.value.account)&&(!q.value.search||`${m.student.name}${m.student.number}`.includes(q.value.search))).sort((a,b)=>q.value.sort==='recent'?(b.joinedAt||'').localeCompare(a.joinedAt||''):a.student.name.localeCompare(b.student.name)))
const pages=computed(()=>Math.max(1,Math.ceil(filtered.value.length/pageSize.value))),page=computed(()=>Math.min(pages.value,Math.max(1,Number(q.value.page)||1))),paged=computed(()=>filtered.value.slice((page.value-1)*pageSize.value,page.value*pageSize.value)),allSelected=computed(()=>paged.value.length>0&&paged.value.every(m=>selected.value.includes(m.id)))
function set(key,value){router.replace({query:{...q.value,[key]:value||undefined,page:key==='page'?value:undefined}})}
function reset(){router.replace({query:{demo:q.value.demo}})}
function switchMode(){router.replace({query:{demo:demo.value?undefined:'1'}})}
function selectPage(checked){selected.value=checked?[...new Set([...selected.value,...paged.value.map(m=>m.id)])]:selected.value.filter(id=>!paged.value.some(m=>m.id===id))}
const directorySearch=ref(''),toAdd=ref([]),available=computed(()=>{const ids=new Set(allMembers.value.map(m=>m.studentId));return(data.value?.students||[]).filter(s=>!ids.has(s.id)&&(!directorySearch.value||`${s.name}${s.number}`.includes(directorySearch.value)))})
function openAdd(){directorySearch.value='';toAdd.value=[];drawer.value={type:'add'}}
function saveAdd(){try{const count=toAdd.value.length;data.value=addMembers(route.params.classId,toAdd.value);message.value=`已添加${count}名待加入成员，仅保存在本机演示名单。`;closeDrawer()}catch{message.value='本机存储失败，名单未确认保存，请检查浏览器存储空间。'}}
const importStep=ref(1),preview=ref([]),filename=ref(''),reading=ref(false),writing=ref(false),importError=ref(''),importedCount=ref(0)
let readGeneration=0
function closeDrawer(){drawer.value=null;readGeneration++;reading.value=false}
function openImport(){importStep.value=1;preview.value=[];filename.value='';importError.value='';drawer.value={type:'import'}}
const validRows=computed(()=>preview.value.filter(r=>!r.error)),badRows=computed(()=>preview.value.filter(r=>r.error)),imports=computed(()=>data.value?.imports.filter(i=>i.classId===route.params.classId)||[])
async function readFile(event){const file=event.target.files?.[0];if(!file)return;const own=++readGeneration;reading.value=true;importError.value='';try{const rows=await readMemberFile(file);if(own!==readGeneration)return;preview.value=validateImport(rows,data.value,route.params.classId);filename.value=file.name;importStep.value=2}catch(e){if(own===readGeneration)importError.value=e.message||'文件读取失败'}finally{if(own===readGeneration)reading.value=false}}
function downloadExample(){downloadCsv('成员导入演示示例.csv',[['姓名','学号'],...available.value.slice(0,3).map(s=>[s.name,s.number])])}
function downloadErrors(){downloadCsv('成员导入异常名单.csv',[['行号','姓名','学号','异常原因'],...badRows.value.map(r=>[r.row,r.name,r.number,r.error])])}
const importReturnButton=ref(null)
watch(importStep,async step=>{if(step===3){await nextTick();importReturnButton.value?.focus()}})
function confirmImport(){if(writing.value)return;writing.value=true;try{const fresh=getClassDemo();preview.value=validateImport(preview.value.map(r=>[r.name,r.number]),fresh,route.params.classId);if(!validRows.value.length){importError.value='名单发生变化，当前没有可导入行';return}importedCount.value=validRows.value.length;data.value=addMembers(route.params.classId,validRows.value.map(r=>r.studentId),'Excel导入',filename.value);importStep.value=3;message.value=`演示导入${importedCount.value}名待加入成员。`}catch(e){importError.value=e.message||'导入保存失败，未确认写入名单'}finally{writing.value=false}}
const drawerTitle=computed(()=>({add:'添加班级成员',import:'批量导入成员',history:'导入记录',info:'成员信息'})[drawer.value?.type]||'成员管理')
const confirmNames=computed(()=>allMembers.value.filter(m=>confirmIds.value.includes(m.id)).map(m=>m.student.name).join('、'))
function processRemove(){try{const count=confirmIds.value.length;data.value=removeMembers(confirmIds.value);selected.value=selected.value.filter(id=>!confirmIds.value.includes(id));confirmIds.value=[];message.value=`已从演示名单移出${count}名成员，账号与历史资料保留。`}catch{operationError.value='本机名单保存失败，未确认移出，请重试。'}}
function processJoin(){try{data.value=joinMember(confirmJoin.value.id);confirmJoin.value=null;message.value='演示成员已标记为加入，未激活或修改真实账号。'}catch{operationError.value='本机名单保存失败，请重试。'}}
</script>
