<template><AppLayout><main class="student-support">
 <header class="support-heading"><div><RouterLink v-if="source" :to="source">← 返回来源页面</RouterLink><h1>{{detail?'个人问题档案':'学生支持工作台'}}</h1><p>按支持需求发现学生，核查证据，再安排针对性的训练。</p></div><button :disabled="loading" @click="load">刷新数据</button></header>
 <p v-if="route.query.from" class="scope-line">分析来源日期：{{route.query.from}}～{{route.query.to}} · 限定来源班级集合。<button @click="router.replace({query:{...route.query,from:undefined,to:undefined,classIds:undefined}})">清除来源范围</button></p><p class="scope-line">仅查看教师授权的教学记录 · 人数按学生去重</p>
 <p v-if="loading" role="status">正在读取成员、任务分配与教学证据…</p><section v-else-if="error" role="alert"><p>{{error}}</p><button @click="load">重新加载</button></section>
 <template v-else><section class="support-filter-surface"><div class="support-filters"><SearchChoice v-model="classId" label="教学班" :options="[{value:'',label:'全部所带班级'},...classes.map(c=>({value:String(c.id),label:c.name+(c.archived?' · 已归档':'')}))]"/><SearchChoice v-model="jobId" label="训练岗位" placeholder="选择训练岗位" :options="jobs.map(j=>({value:String(j.id),label:j.name}))"/><label>训练周期<select v-model="days" :disabled="!!route.query.from"><option value="7">近7天</option><option value="30">近30天</option><option value="90">近90天</option></select></label><label>观察维度<select v-model="code" aria-label="能力维度"><option value="">暂无可用维度</option><option v-for="m in modules" :key="m.id" :value="m.id">{{m.name}}</option></select></label></div><div class="support-standard"><span>能力分析依据</span><span v-if="selectedVersion">{{moduleName}} · 目标 {{selectedVersion.target}} 分 · {{selectedVersion.count}}名可比学生</span><span v-else>暂无可比评价记录</span><button @click="standardOpen=!standardOpen" :aria-expanded="standardOpen">{{standardOpen?'收起评价标准':'查看评价标准'}}</button></div><div v-if="standardOpen" class="standard-details"><p>评价标准由任务设定的目标分、权重和报告评分版本共同决定。只有标准相同的学生才能一起比较；不符合当前标准的记录会显示为待补齐。</p><label v-if="versions.length">用于比较的评价标准<select v-model="version" aria-label="评价标准"><option v-for="(v,i) in versions" :key="v.key" :value="v.key">标准{{i+1}} · 目标{{v.target}}分 · {{v.count}}人</option></select></label><details v-if="selectedVersion"><summary>查看技术版本信息</summary><p>{{selectedVersion.label}}</p></details></div></section>
 <p v-if="failed" class="support-warning" role="status">{{failed}}份报告读取失败，受影响学生暂不判定能力。<button @click="load">重试读取</button></p>
 <template v-if="!detail"><div class="support-workspace"><aside class="support-panel support-groups"><header class="support-region-heading"><h2>学生人群</h2><p>按支持需求切换名单</p></header><button :aria-pressed="group==='all'" @click="chooseGroup('all')"><span>全部学生<b>{{rows.length}}</b></span></button><p>按当前支持需求查看</p><button v-for="g in supportGroups" :key="g.key" :aria-pressed="group===g.key" @click="chooseGroup(g.key)"><span>{{g.name}}<b>{{rows.filter(s=>s.groups.includes(g.key)).length}}</b></span></button><small>同一学生可属于多个人群，人数不能相加。</small></aside><div class="support-main support-panel"><header class="support-context support-region-heading"><div><h2>{{currentGroup.name}}</h2><p>{{currentGroup.note}}</p></div><span class="support-total"><b>{{visible.length}}</b><small>名学生</small></span></header>
 <div v-if="group==='short'" class="support-gap-filter"><span>按目标差距缩小名单</span><button :aria-pressed="!band" @click="band='';page=1">全部短板学生</button><button v-for="b in bands" :key="b.key" :aria-pressed="band===b.key" @click="band=band===b.key?'':b.key;page=1">{{b.name}} <b>{{shortRows.filter(b.test).length}}</b></button></div>
 <section v-if="group==='invest'" class="support-panel"><h3>有效训练次数与能力表现</h3><p>横轴为本周期有效训练次数，纵轴为最近可比评分。点击学生查看问题档案。</p><svg v-if="investRows.length" viewBox="0 0 440 250" class="support-scatter" aria-label="投入与能力散点图"><path d="M40 20V215H415" stroke="#d4ded9" fill="none"/><text x="4" y="25">100</text><text x="20" y="218">0</text><text x="40" y="242">0次</text><text x="370" y="242">{{maxCount}}次</text><circle v-for="s in investRows" :key="s.id" :cx="50+s.count/maxCount*350" :cy="215-s.score*1.9" r="7" fill="#10b981" tabindex="0" role="button" :aria-label="s.name+' '+s.count+'次 '+s.score+'分'" @click="openStudent(s.id)" @keydown.enter="openStudent(s.id)"/></svg><p v-else>暂无满足投入与可比评分条件的学生。</p></section>
 <section v-else-if="group==='blocked'" class="support-panel"><h3>先排除执行障碍</h3><p>报告失败、无效回答与次数耗尽需要不同处理。进入个人档案，定位原任务分配；生成中报告先等待。</p></section>
 <section class="support-panel"><header class="support-list-heading"><div><h2>{{group==='all'?'学生名单':'支持名单'}}</h2><p>{{visible.length}}名匹配学生 · 每页6人</p></div><input v-model="search" type="search" aria-label="搜索学生" placeholder="姓名或账号" @input="page=1"/></header><div class="support-actions"><span>已选择{{selected.length}}人</span><button class="support-primary" :disabled="!selected.length" @click="draftOpen=true">复核名单与目标班级</button><button @click="band='';search='';page=1">清除名单筛选</button></div><div class="support-table-scroll"><table><thead><tr><th>选择</th><th>学生与班级关系</th><th>当前支持需求</th><th>教学证据</th><th>下一步</th></tr></thead><tbody><tr v-for="s in paged" :key="s.id"><td><input v-model="selected" type="checkbox" :value="s.id" :aria-label="'选择'+s.name"/></td><td><b>{{s.name}}</b><small>{{s.username}}</small><small>{{s.classes.map(c=>c.name).join(' / ')}}</small></td><td><span v-for="g in s.groups" :key="g" :class="['support-tag','tag-'+g]">{{supportGroups.find(v=>v.key===g).name}}</span><small v-if="!s.groups.length">暂未命中当前规则</small></td><td>{{s.count}}次有效教学训练<small>{{s.score==null?s.evidence:s.score+'分 / 目标'+s.target}}</small></td><td><button @click="openStudent(s.id)">查看问题档案</button></td></tr></tbody></table></div><p v-if="!visible.length" class="support-empty">没有匹配学生，请调整班级、人群或搜索条件。</p><footer class="support-actions"><span>第{{safePage}} / {{pages}}页</span><button :disabled="safePage===1" @click="page=safePage-1">上一页</button><button :disabled="safePage===pages" @click="page=safePage+1">下一页</button></footer></section></div></div></template>
 <template v-else><RouterLink class="support-button" :to="{path:'/teacher/students',query:listQuery}">← 返回支持工作台</RouterLink><template v-if="student"><section class="support-cue support-person"><h2>{{student.name}}</h2><p>{{student.username}} · {{student.classes.map(c=>c.name).join(' / ')}}</p><span v-for="g in student.groups" :key="g" :class="['support-tag','tag-'+g]">{{supportGroups.find(v=>v.key===g).name}}</span><button @click="selected=[student.id];draftOpen=true">为该学生安排支持</button></section><div class="support-detail-grid"><section class="support-panel"><h2>当前问题与依据</h2><p>{{student.evidence}} · 本周期{{student.count}}次有效教学训练</p><p v-if="student.score!=null">{{moduleName}}：{{student.score}}分，实际目标{{student.target}}分。</p><RouterLink v-if="student.latest?.reportId" class="support-button" :to="reportLink(student.latest.reportId)">核查最近报告与点评</RouterLink><article v-for="r in student.reasons" :key="r.a.id+r.text" class="support-evidence"><h3>{{r.text}}</h3><p>{{r.a.task.title}} · {{r.a.task.className}}</p><RouterLink class="support-button" :to="taskLink(r.a)">处理原任务的个人分配</RouterLink></article><p v-if="!student.groups.length">当前规则没有识别到明确支持需求，请结合原始报告判断。</p></section><section class="support-panel"><h2>最近可比训练表现</h2><p>同岗位、同维度、同评分口径；最多展示最近6次。次数不足不判断持续变化。</p><RouterLink v-for="r in student.history.slice(-6)" :key="r.reportId" class="support-bar" :to="reportLink(r.reportId)"><span>{{date(r.submittedAt)}}</span><i class="support-track"><i :style="{width:r.detailReport.moduleScores.find(m=>m.moduleCode===code).rawScore+'%'}"/></i><b>{{r.detailReport.moduleScores.find(m=>m.moduleCode===code).rawScore}}</b></RouterLink><p v-if="!student.history.length">暂无可比维度记录。缺失评分不计为零分。</p></section></div><section class="support-panel"><h2>教学安排与个人调整</h2><article v-for="a in student.allocations" :key="a.id" class="support-evidence"><div><h3>{{a.task.title}}</h3><p>{{a.task.className}} · {{status(a.completionStatus)}} · 有效{{a.validCount??0}} / {{a.task.minAttempts}}次</p><small>个人截止：{{date(a.effectiveDeadline||a.task.deadline)}}{{a.overrideReason?' · 调整原因：'+a.overrideReason:''}}</small></div><RouterLink class="support-button" :to="taskLink(a)">查看分配与补练</RouterLink></article><p v-if="!student.allocations.length">暂无该范围教学分配。</p></section></template><p v-else class="support-empty">当前范围没有该学生，请调整班级筛选或返回名单。</p></template>
 </template>
 <TeacherDrawer v-if="draftOpen" modal class="support-drawer" title="复核支持名单与目标班级" @close="draftOpen=false">
  <p class="support-draft-intro">选择目标班级，核对学生后进入草稿配置。此处不会发布任务。</p>
  <label class="support-draft-class">目标班级<select v-model="targetClass" aria-label="目标班级"><option value="">选择班级</option><option v-for="c in eligibleClasses" :key="c.id" :value="String(c.id)">{{c.name}}</option></select></label>
  <div class="support-draft-summary" role="status"><span>已选 <b>{{selected.length}}</b> 人</span><span>可进入本班草稿 <b>{{draftStudents.length}}</b> 人</span></div>
  <p class="support-draft-hint">跨班学生仅进入所选班级的草稿，其余学生保留在支持名单，需另行安排。创建页会再次核对正常已加入成员。</p>
  <p v-if="!chosen.length" class="support-draft-empty" role="status">名单已清空，请关闭窗口后重新选择学生。</p><ul v-else class="support-draft-students" aria-label="已选学生"><li v-for="s in chosen" :key="s.id"><div><strong>{{s.name}}</strong><small>{{s.classes.map(c=>c.name).join(' / ')}}</small></div><button type="button" :aria-label="'移除'+s.name" @click="selected=selected.filter(id=>id!==s.id)">移除</button></li></ul>
  <div class="support-draft-note"><span>建议维度</span><strong>{{moduleName||'尚未选择'}}</strong><p>请在创建页核对岗位、题目、次数与完整评价方案。</p></div>
  <footer class="support-draft-footer"><button type="button" @click="draftOpen=false">取消</button><RouterLink v-if="draftStudents.length" class="support-button" :to="{path:'/teacher/tasks/create',query:{classId:targetClass,studentIds:draftStudents.map(s=>s.id).join(','),abilityCode:code||undefined,returnTo:route.fullPath}}">进入训练草稿配置</RouterLink><button v-else type="button" disabled>进入训练草稿配置</button></footer>
 </TeacherDrawer>
</main></AppLayout></template>
<script setup>
import {computed,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import AppLayout from '../../components/layout/AppLayout.vue'
import SearchChoice from '../../components/teacher/SearchChoice.vue'
import TeacherDrawer from '../../components/teacher/TeacherDrawer.vue'
import {teaching} from '../../services/teachingApi.js'
import {moduleOptions} from '../../services/teachingAnalysis.js'
import {supportGroups,supportRows} from '../../services/studentSupport.js'
import {safeTeacherReturn} from '../../services/teacherContext.js'
import '../../assets/styles/student-support.css'
const route=useRoute(),router=useRouter(),classes=ref([]),people=ref([]),tasks=ref([]),reports=ref([]),loading=ref(false),error=ref(''),failed=ref(0)
const classId=ref(String(route.query.classId||'')),jobId=ref(String(route.query.jobId||'')),days=ref(['7','30','90'].includes(String(route.query.period))?String(route.query.period):'30'),code=ref(String(route.query.abilityCode||'')),version=ref(String(route.query.version||'')),group=ref(({low:'short',reached:'near'}[route.query.group])||route.query.group||'all'),search=ref(String(route.query.search||'')),band=ref(['large','mid'].includes(route.query.band)?route.query.band:''),page=ref(Number(route.query.page)||1),selected=ref([]),draftOpen=ref(false),targetClass=ref(''),standardOpen=ref(false)
const detail=computed(()=>!!route.params.id),source=computed(()=>safeTeacherReturn(route.query.returnTo)),jobs=computed(()=>[...new Map(tasks.value.map(t=>[t.jobId,{id:t.jobId,name:t.jobName}])).values()]),scopedReports=computed(()=>reports.value.filter(r=>(!classId.value||String(r.classId)===classId.value)&&String(r.jobId)===jobId.value)),modules=computed(()=>moduleOptions(scopedReports.value)),moduleName=computed(()=>modules.value.find(m=>m.id===code.value)?.name)
const baseRows=computed(()=>supportRows(people.value,tasks.value,reports.value,{classId:classId.value,jobId:jobId.value,code:code.value,days:Number(days.value),classIds:String(route.query.classIds||'').split(',').filter(Boolean),from:route.query.from,to:route.query.to})),versions=computed(()=>{const map=new Map();for(const s of baseRows.value)if(s.key){const v=map.get(s.key)||{key:s.key,target:s.target,label:[s.latest.detailReport.trainingContext.provenance.ruleVersion,s.latest.detailReport.trainingContext.provenance.modelVersion,s.latest.detailReport.trainingContext.provenance.promptVersion,'目标'+s.target].join(' / '),count:0};v.count++;map.set(s.key,v)}return [...map.values()].sort((a,b)=>b.count-a.count)}),selectedVersion=computed(()=>versions.value.find(v=>v.key===version.value)),rows=computed(()=>supportRows(people.value,tasks.value,reports.value,{classId:classId.value,jobId:jobId.value,code:code.value,version:version.value,days:Number(days.value),classIds:String(route.query.classIds||'').split(',').filter(Boolean),from:route.query.from,to:route.query.to})),student=computed(()=>rows.value.find(s=>s.id===String(route.params.id))),currentGroup=computed(()=>supportGroups.find(g=>g.key===group.value)||{name:'全部学生',note:'查看当前范围的学生与教学证据'}),shortRows=computed(()=>rows.value.filter(s=>s.groups.includes('short'))),investRows=computed(()=>rows.value.filter(s=>s.groups.includes('invest'))),maxCount=computed(()=>Math.max(1,...investRows.value.map(s=>s.count)))
const bands=[{key:'large',name:'距目标超过20分',test:s=>s.gap>20},{key:'mid',name:'距目标10–20分',test:s=>s.gap>=10&&s.gap<=20}]
const visible=computed(()=>rows.value.filter(s=>(group.value==='all'||s.groups.includes(group.value))&&(!band.value||bands.find(b=>b.key===band.value)?.test(s))&&(s.name+' '+s.username).toLowerCase().includes(search.value.toLowerCase()))),pages=computed(()=>Math.max(1,Math.ceil(visible.value.length/6))),safePage=computed(()=>Math.min(page.value,pages.value)),paged=computed(()=>visible.value.slice((safePage.value-1)*6,safePage.value*6)),chosen=computed(()=>rows.value.filter(s=>selected.value.includes(s.id))),eligibleClasses=computed(()=>classes.value.filter(c=>!c.archived&&chosen.value.some(s=>s.classes.some(sc=>String(sc.id)===String(c.id))))),draftStudents=computed(()=>chosen.value.filter(s=>s.classes.some(c=>String(c.id)===targetClass.value))),listQuery=computed(()=>({classId:classId.value||undefined,classIds:route.query.classIds,from:route.query.from,to:route.query.to,jobId:jobId.value||undefined,abilityCode:code.value||undefined,period:days.value,version:version.value||undefined,group:group.value,band:band.value||undefined,search:search.value||undefined,page:page.value>1?page.value:undefined,returnTo:source.value||undefined}))
function chooseGroup(key){group.value=key;band.value='';page.value=1;selected.value=[]}function openStudent(id){router.push({path:'/teacher/students/'+id,query:listQuery.value})}function reportLink(id){return{path:'/teacher/reports/'+id,query:{returnTo:route.fullPath}}}function taskLink(a){return{path:'/teacher/tasks/'+a.task.id,query:{assignmentId:a.id,returnTo:route.fullPath}}}function date(v){return v?String(v).replace('T',' ').slice(0,16):'未提供'}function status(v){return {COMPLETED:'已完成',EXEMPT:'已减免',NOT_STARTED:'未开始',IN_PROGRESS:'进行中',PENDING_VALIDATION:'等待报告'}[v]||v}
let generation=0
async function load(){const own=++generation;loading.value=true;error.value='';failed.value=0;try{const [cs,ps,ts]=await Promise.all([teaching.classes(),teaching.people(),teaching.tasks({includeAssignments:true})]);const detail=[];for(let i=0;i<ts.length;i+=4){const batch=await Promise.all(ts.slice(i,i+4).filter(t=>t.publishedAt).map(t=>Array.isArray(t.assignments)?t:teaching.task(t.id)));if(own!==generation)return;detail.push(...batch)}const raw=[...new Map(detail.flatMap(t=>(t.assignments||[]).flatMap(a=>(a.attempts||[]).filter(p=>p.reportId).map(p=>({...p,studentId:a.studentId,taskId:t.id,classId:t.classId,jobId:t.jobId})))).map(r=>[r.reportId,r])).values()],loaded=[];let failures=0;for(let i=0;i<raw.length;i+=4){const result=await Promise.allSettled(raw.slice(i,i+4).map(async r=>({...r,detailReport:(await teaching.report(r.reportId)).report})));if(own!==generation)return;result.forEach((r,j)=>{loaded.push(r.status==='fulfilled'?r.value:{...raw[i+j],readFailed:true});if(r.status==='rejected')failures++})}if(own!==generation)return;classes.value=cs;people.value=ps;tasks.value=detail;reports.value=loaded;failed.value=failures;selected.value=[];if(!jobs.value.some(j=>String(j.id)===jobId.value))jobId.value=String(jobs.value[0]?.id||'')}catch(e){if(own===generation)error.value=e.response?.data?.message||e.message||'教学数据读取失败'}finally{if(own===generation)loading.value=false}}
watch(modules,ms=>{if(!ms.some(m=>m.id===code.value))code.value=ms[0]?.id||''});watch(versions,vs=>{if(!vs.some(v=>v.key===version.value))version.value=vs[0]?.key||''});watch([classId,jobId,days,code,version],()=>{band.value='';selected.value=[];page.value=1});watch(eligibleClasses,cs=>{if(!cs.some(c=>String(c.id)===targetClass.value))targetClass.value=cs.length===1?String(cs[0].id):''});watch(listQuery,q=>{if(!loading.value)router.replace({query:q})});load()
</script>
