<template><AppLayout><div class="class-manager">
 <RouterLink v-if="analysisReturn" class="cm-back" :to="analysisReturn">返回数据分析</RouterLink><p v-if="analysisReturn" class="cm-analysis-origin">来源范围：{{route.query.from}}～{{route.query.to}}。本页管理班级成员与任务；统计图及可比能力依据请返回数据分析查看。</p><RouterLink class="cm-back" to="/teacher/classes">返回班级列表</RouterLink>
 <p v-if="loading" role="status">正在读取班级资料…</p><section v-else-if="error" class="cm-panel" role="alert"><p>{{error}}</p><button class="secondary" @click="load">重新加载</button></section>
 <template v-else-if="current">
 <header class="cm-hero"><div><span class="cm-semester">{{current.semester||'未设置学期'}} · {{current.archived?'已归档':'使用中'}}</span><h1>{{current.name}}</h1><p>管理本班成员、加入申请和教学任务</p><label class="cm-switch">切换班级<select :value="id" aria-label="切换班级" @change="router.push('/teacher/classes/'+$event.target.value)"><option v-for="c in classes" :key="c.id" :value="c.id">{{c.name}}</option></select></label></div><div class="cm-hero-actions"><button class="secondary" :disabled="busy" @click="load">刷新</button><button class="secondary" :disabled="current.archived" @click="edit={name:current.name,semester:current.semester};editing=true">编辑班级</button><RouterLink v-if="!current.archived" class="primary" :to="{path:'/teacher/tasks/create',query:{classId:id}}">发布班级任务</RouterLink></div></header>
 <p v-if="feedback" role="status" class="cm-feedback">{{feedback}}</p><p v-if="actionError" role="alert" class="cm-action-error">{{actionError}}</p>
 <div class="cm-facts"><button @click="tab='members'"><strong>{{joined.length}}</strong><span>班级成员</span></button><button @click="tab='requests'"><strong>{{pending.length}}</strong><span>待审核申请</span></button><button @click="tab='tasks'"><strong>{{activeTasks.length}}</strong><span>进行中任务</span></button><div><strong>{{backlog.length}}</strong><span>有未完成任务的学生</span></div></div>
 <div class="cm-layout"><section class="cm-panel cm-main"><nav class="cm-tabs" aria-label="班级管理栏目"><button v-for="t in tabs" :key="t.id" :aria-pressed="tab===t.id" @click="tab=t.id;search='';page=1">{{t.name}} <span>{{t.id==='members'?joined.length:t.id==='requests'?pending.length:tasks.length}}</span></button></nav>
 <template v-if="tab!=='tasks'"><header class="cm-section-head"><div><h2>{{tab==='requests'?'加入申请':'班级成员名单'}}</h2><p>{{tab==='requests'?'核对学生身份，通过申请后学生可接收班级任务。':'仅管理本班成员关系，移出后保留历史任务与报告。'}}</p></div><input v-model="search" type="search" aria-label="搜索班级成员" placeholder="搜索姓名或账号" @input="page=1"/></header><div v-if="filtered.length" class="cm-table-scroll"><table><thead><tr><th>学生</th><th>账号状态</th><th>未完成任务</th><th>成员操作</th></tr></thead><tbody><tr v-for="m in paged" :key="m.id"><td><strong>{{m.name}}</strong><small>{{m.username}}</small></td><td><span class="cm-tag" :class="{'cm-warning':m.accountStatus!==1}">{{m.accountStatus===1?'正常':m.accountStatus===0?'已停用':'未激活'}}</span></td><td>{{backlog.find(s=>s.id===m.studentId)?.tasks.length||0}} 项</td><td><div class="cm-row-actions"><template v-if="tab==='requests'"><button class="primary" :disabled="busy||current.archived" @click="act(()=>teaching.membership(id,m.id,'JOINED'),'申请已通过')">通过</button><button class="secondary" :disabled="busy||current.archived" @click="confirm('拒绝 '+m.name+' 的加入申请？',()=>teaching.membership(id,m.id,'REJECTED'))">拒绝</button></template><template v-else><RouterLink class="cm-text" :to="{path:'/teacher/students/'+m.studentId,query:{classId:id,returnTo:route.fullPath}}">学生资料</RouterLink><button class="text" :disabled="busy||current.archived" @click="confirm('将 '+m.name+' 移出本班？历史任务与报告保留，学生将不能开始新的班级任务。',()=>teaching.membership(id,m.id,'REMOVED'))">移出班级</button></template></div></td></tr></tbody></table></div><div v-else class="cm-empty"><h3>{{search?'没有匹配的学生':tab==='requests'?'暂无待审核申请':'班级名单等待建立'}}</h3><p>{{search?'调整搜索关键词后重试。':'将右侧邀请码分享给学生，在这里审核加入申请。'}}</p></div><footer v-if="filtered.length" class="cm-pagination"><span>共 {{filtered.length}} 人 · 第 {{safePage}} / {{pages}} 页</span><button class="secondary" :disabled="safePage===1" @click="page=safePage-1">上一页</button><button class="secondary" :disabled="safePage===pages" @click="page=safePage+1">下一页</button></footer></template>
 <template v-else><header class="cm-section-head"><div><h2>本班教学任务</h2><p>查看任务安排、截止时间及未完成情况</p></div><RouterLink class="secondary" :to="{path:'/teacher/tasks',query:{classId:id}}">任务工作台</RouterLink></header><article v-for="t in tasks" :key="t.id" class="cm-task"><div><span class="cm-tag">{{taskLabels[t.lifecycle]||t.lifecycle}}</span><h3>{{t.title}}</h3><p>截止 {{t.deadline?.replace('T',' ').slice(0,16)||'未设置'}} · {{(t.assignments||[]).filter(a=>!a.exempt&&a.completionStatus!=='COMPLETED').length}} 人待完成</p></div><RouterLink class="secondary" :to="{path:'/teacher/tasks/'+t.id,query:{returnTo:route.fullPath}}">查看任务</RouterLink></article><div v-if="!tasks.length" class="cm-empty"><h3>还没有班级任务</h3><p>为本班发布训练任务后，可在这里查看执行情况。</p></div></template>
 </section><aside class="cm-side"><section class="cm-panel cm-invite"><h2>邀请学生加入</h2><p>{{current.archived?'班级已归档，不能接受新的加入申请。':'学生输入邀请码提交申请，由老师审核加入。'}}</p><template v-if="!current.archived"><span class="cm-code-label">班级邀请码</span><strong class="cm-code">{{current.inviteCode||'暂未生成'}}</strong><button class="primary" :disabled="!current.inviteCode" @click="copyInvite">复制邀请码</button><button class="text" :disabled="busy" @click="confirm('重置邀请码后，原邀请码立即失效。',()=>teaching.invite(id))">重置邀请码</button></template></section><section class="cm-panel"><h2>班级资料</h2><dl class="cm-info"><dt>学期</dt><dd>{{current.semester||'未设置'}}</dd><dt>状态</dt><dd>{{current.archived?'已归档':'使用中'}}</dd><dt>当前成员</dt><dd>{{joined.length}} 人</dd></dl><p>班级归档后保留历史资料，并结束已发布任务。</p><button v-if="!current.archived" class="danger" :disabled="busy" @click="confirm('归档本班将结束已发布任务，停止新成员加入，历史报告保留。确认归档？',()=>teaching.archive(id))">归档班级</button></section></aside></div>
 </template><section v-else-if="!loading" class="cm-panel cm-empty"><h2>未找到该班级</h2><RouterLink to="/teacher/classes">返回班级列表</RouterLink></section>
 <TeacherDrawer class="class-detail-window class-edit-window" :open="editing" title="编辑班级资料" modal @close="editing=false"><form class="cm-edit" @submit.prevent="act(()=>teaching.editClass(id,edit),'班级资料已更新',()=>editing=false)"><label>班级名称<input v-model.trim="edit.name" required maxlength="80"/></label><label>学期<input v-model.trim="edit.semester" required maxlength="80"/></label><p v-if="actionError" role="alert">{{actionError}}</p><footer class="cm-dialog-actions"><button type="button" :disabled="busy" @click="editing=false">取消</button><button class="primary" :disabled="busy">{{busy?'保存中…':'保存修改'}}</button></footer></form></TeacherDrawer>
 <TeacherDrawer class="class-detail-window class-confirm-window" :open="!!confirmation" title="确认班级操作" modal @close="confirmation=null"><p>{{confirmation?.text}}</p><p v-if="actionError" role="alert">{{actionError}}</p><div class="drawer-actions"><button class="danger" :disabled="busy" @click="act(confirmation.action,'操作已完成',()=>confirmation=null)">确认操作</button><button class="secondary" :disabled="busy" @click="confirmation=null">取消</button></div></TeacherDrawer>
</div></AppLayout></template>
<script setup>
import {safeTeacherReturn} from '../../services/teacherContext.js'
import {computed,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import AppLayout from '../../components/layout/AppLayout.vue'
import TeacherDrawer from '../../components/teacher/TeacherDrawer.vue'
import {teaching} from '../../services/teachingApi.js'
import {taskBacklog} from '../../services/taskBacklog.js'
import '../../assets/styles/class-manager.css'
const route=useRoute(),router=useRouter(),classes=ref([]),members=ref([]),tasks=ref([]),loading=ref(false),busy=ref(false),error=ref(''),actionError=ref(''),feedback=ref(''),tab=ref('members'),search=ref(''),page=ref(1),editing=ref(false),edit=ref({}),confirmation=ref(null)
const tabs=[{id:'members',name:'班级成员'},{id:'requests',name:'加入申请'},{id:'tasks',name:'班级任务'}],taskLabels={DRAFT:'草稿',SCHEDULED:'待开始',ACTIVE:'进行中',ENDED:'已结束',CLOSED:'已截止',ARCHIVED:'已归档'}
const analysisReturn=computed(()=>safeTeacherReturn(route.query.returnTo)),id=computed(()=>String(route.params.classId||'')),current=computed(()=>classes.value.find(c=>String(c.id)===id.value)),joined=computed(()=>members.value.filter(m=>m.state==='JOINED')),pending=computed(()=>members.value.filter(m=>m.state==='PENDING')),activeTasks=computed(()=>tasks.value.filter(t=>t.lifecycle==='ACTIVE')),backlog=computed(()=>taskBacklog(tasks.value)),filtered=computed(()=>(tab.value==='requests'?pending.value:joined.value).filter(m=>`${m.name} ${m.username}`.toLowerCase().includes(search.value.trim().toLowerCase()))),pages=computed(()=>Math.max(1,Math.ceil(filtered.value.length/10))),safePage=computed(()=>Math.min(page.value,pages.value)),paged=computed(()=>filtered.value.slice((safePage.value-1)*10,safePage.value*10))
let generation=0
async function load(){const own=++generation;loading.value=true;error.value='';try{const cs=await teaching.classes();if(own!==generation)return;classes.value=cs;if(!current.value){members.value=[];tasks.value=[];return}const [ms,ts]=await Promise.all([teaching.members(id.value),teaching.tasks({includeAssignments:true})]);const scoped=ts.filter(t=>String(t.classId)===id.value);const details=await Promise.all(scoped.map(t=>Array.isArray(t.assignments)?t:teaching.task(t.id)));if(own!==generation)return;members.value=ms;tasks.value=details.sort((a,b)=>String(a.deadline||'').localeCompare(String(b.deadline||'')))}catch(e){if(own===generation)error.value=e.response?.data?.message||e.message||'读取失败，请重试'}finally{if(own===generation)loading.value=false}}
async function act(action,message,after){if(busy.value)return;busy.value=true;actionError.value='';try{await action();after?.();await load();feedback.value=message}catch(e){actionError.value=e.response?.data?.message||e.message||'操作失败，请重试'}finally{busy.value=false}}
function confirm(text,action){actionError.value='';confirmation.value={text,action}}
async function copyInvite(){try{await navigator.clipboard.writeText(current.value.inviteCode);feedback.value='邀请码已复制'}catch{actionError.value='复制失败，请手动复制上方邀请码'}}
watch(id,()=>{tab.value='members';search.value='';page.value=1;confirmation.value=null;editing.value=false;feedback.value='';actionError.value='';load()},{immediate:true})
</script>
