<template><AppLayout><main class="live-teaching-report teaching-portal">
<RouterLink :to="back" class="back">← 返回来源页面</RouterLink><header><div><h1>教学任务报告</h1><p>查看学生原始回答、评分依据，并发布具体的训练反馈。</p></div><button :disabled="loading" @click="load">刷新报告</button></header>
<section v-if="loading" class="live-loading" role="status"><span/><span/><span/><p>正在读取完整报告…</p></section><section v-else-if="error" class="notice error" role="alert"><h2>报告暂时无法加载</h2><p>{{error}}</p><button @click="load">重新加载</button></section>
<template v-else-if="data"><section class="live-panel report-intro"><div><span class="status-tag" :class="data.report.trainingContext?.state==='INVALID'?'warning':'positive'">{{data.report.trainingContext?.state==='INVALID'?'未计入任务有效次数':'原始训练报告'}}</span><p v-if="data.report.trainingContext" class="report-task-context">{{data.report.trainingContext.studentName}} · {{data.report.trainingContext.className}} · {{data.report.trainingContext.taskTitle}}</p><p v-if="data.report.trainingContext?.failureReason">{{data.report.trainingContext.failureReason}}</p><h2>{{data.report.jobName}}</h2><p>{{String(data.report.endTime||'').replace('T',' ')}}</p><p class="report-summary">{{hasAnswers?(data.report.summary||'本次报告未提供综合评语，请结合评分依据与原始问答复盘。'):'本次未形成可评价回答，暂不判断能力表现。请查看原始过程，并根据任务要求安排补练。'}}</p></div><dl v-if="hasAnswers" class="report-grades"><div><dt>训练目标匹配度</dt><dd>{{data.report.overallMatchScore==null?'—':Number(data.report.overallMatchScore).toFixed(1)+'%'}}<small>{{data.report.displayLevel||'尚未提供'}}</small></dd></div><div><dt>基础综合评分</dt><dd>{{data.report.totalScore??'—'}}<small>/ 100</small></dd></div></dl></section>
<section v-if="!hasAnswers" class="notice" role="status"><h2>训练过程待补全</h2><p>未作答与能力不足分别处理。本次保留原始问答和教师点评，不显示能力分布、优势或薄弱项。</p></section>
<div v-if="hasAnswers" class="report-findings"><section v-for="[key,label] in [['strengths','表现优势'],['weaknesses','薄弱表现'],['suggestions','下一步训练建议']]" :key="key" class="live-panel"><h2>{{label}}</h2><ul v-if="data.report[key]?.length"><li v-for="(text,i) in data.report[key]" :key="i">{{text}}</li></ul><p v-else class="report-unavailable">原报告未提供该项内容。</p></section></div>
<section v-if="hasAnswers" class="live-panel"><header><div><h2>模块评分与依据</h2><p>展示原始模块分，满分 100。目标匹配度采用百分比，单独展示。</p></div></header><p class="chart-caption">方案来源：{{data.report.trainingContext?.scorePlan?.source==='TEACHER_TASK'?'教师统一方案':'旧版默认方案'}} · 算法：{{data.report.trainingContext?.provenance?.ruleVersion||'历史未记录'}}。低分有效训练仍可计入次数，能力目标另行查看。</p><div v-if="scores.length" class="report-scorebars" role="img" :aria-label="scores.map(d=>d.name+' '+d.score+'分').join('，')"><div v-for="(d,i) in scores" :key="i"><span>{{d.name}}</span><div class="bar-track"><span :style="{width:Math.min(100,Math.max(0,Number(d.score)||0))+'%'}"/></div><strong>{{d.score==null?'未提供':Number(d.score).toFixed(1)}}</strong></div></div><div class="table-scroll"><table><thead><tr><th>维度</th><th>原始评分</th><th>目标分 / 权重</th><th>目标差距</th><th>依据与建议</th></tr></thead><tbody><tr v-for="(d,i) in scores" :key="i"><td>{{d.name}}</td><td>{{d.score!==null&&Number.isFinite(Number(d.score))?Number(d.score).toFixed(1):'未提供'}}</td><td>{{d.target==null?'未提供':d.target}} / {{d.weight==null?'未提供':(d.weight*100).toFixed(0)+'%'}}</td><td>{{d.gap==null?'未提供':d.gap}} 分</td><td>{{d.evidence||d.explanation||'原报告未提供说明'}}<p v-if="d.suggestion">改进建议：{{d.suggestion}}</p><small v-if="d.source">评分来源：{{d.source==='AI'?'AI 评分':d.source==='RULE'?'规则评分':d.source}}</small></td></tr></tbody></table></div><p v-if="!scores.length" class="live-empty">原报告未提供可视化评分，原始问答与教师点评仍可查看。</p></section>
<div class="report-evidence-grid"><section class="live-panel"><header><div><h2>原始问答</h2><p>按训练轮次保留问题、追问与学生回答。</p></div><span>{{data.messages.length}} 条记录</span></header><div class="report-conversation"><article v-for="m in data.messages" :key="m.id" :class="m.role==='CANDIDATE'?'candidate':'interviewer'"><header><strong>{{m.role==='CANDIDATE'?m.msgType==='SKIPPED'?'学生跳过':'学生回答':m.msgType==='FOLLOWUP'?'面试追问':'训练问题'}}</strong><small>第 {{m.roundNo}} 轮</small></header><p>{{m.content}}</p></article><p v-if="!data.messages.length" class="live-empty">原报告未提供问答记录。</p></div></section><section class="live-panel"><TeachingFeedback :report-id="route.params.id" can-review/></section></div></template>
<ExpressionReport v-if="data" :data="data.report.expressions" :start-time="data.report.startTime" />
</main></AppLayout></template>
<script setup>
import {computed,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import '../../assets/styles/teaching-live.css'
import AppLayout from '../../components/layout/AppLayout.vue'
import TeachingFeedback from '../../components/teacher/TeachingFeedback.vue'
import ExpressionReport from '../../components/interview/ExpressionReport.vue'
import {teaching} from '../../services/teachingApi'
import {reportEvidence} from '../../services/teachingWorkspace.js'
import {safeTeacherReturn} from '../../services/teacherContext'
const route=useRoute(),data=ref(null),loading=ref(false),error=ref(''),back=computed(()=>safeTeacherReturn(route.query.returnTo)||'/teacher/reviews'),scores=computed(()=>data.value?.report.moduleScores?.length?data.value.report.moduleScores.map(m=>({name:m.moduleName||m.moduleCode,score:m.rawScore,evidence:m.evidence,suggestion:m.suggestion,source:m.scoreSource,target:m.targetScore,weight:m.baseWeight,gap:m.gapScore})):data.value?.report.dimensions?.map(d=>({...d,name:d.dimension}))||[])
const hasAnswers=computed(()=>reportEvidence(data.value))
async function load(){data.value=null;loading.value=true;error.value='';try{data.value=await teaching.report(route.params.id)}catch(e){error.value=e.response?.data?.message||e.message}finally{loading.value=false}}
watch(()=>route.params.id,load,{immediate:true})
</script>
<style scoped>
.live-teaching-report>.live-panel{margin-bottom:24px}.report-intro{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(300px,1fr);gap:32px}.report-intro h2{font-size:25px;margin:14px 0 8px}.report-summary{margin-top:20px;max-width:65ch}.report-grades{display:grid;grid-template-columns:1fr 1fr;gap:24px;padding-left:32px;border-left:1px solid var(--neutral-200);align-self:center}.report-grades dt{font-size:14px;color:var(--neutral-600)}.report-grades dd{font-size:30px;font-weight:600;margin:14px 0 0;font-variant-numeric:tabular-nums}.report-grades small{display:block;font-size:13px;font-weight:400;margin-top:8px}.report-findings{display:grid;grid-template-columns:1fr 1fr 1fr;gap:20px;margin-bottom:24px}.report-findings ul{padding-left:20px;margin-top:16px}.report-findings li{padding:6px 0;line-height:1.85;color:var(--neutral-700)}.report-unavailable{padding:28px 0}.report-scorebars{display:grid;grid-template-columns:1fr 1fr;gap:24px 40px;margin:28px 0}.report-scorebars>div{display:grid;grid-template-columns:120px minmax(50px,1fr) 44px;gap:14px;align-items:center}.report-evidence-grid{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(0,1fr);gap:24px}.report-conversation article{padding:20px 0;border-bottom:1px solid var(--neutral-200)}.report-conversation article:last-child{border-bottom:0}.report-conversation article>header{display:flex;justify-content:space-between;gap:16px;margin-bottom:12px}.report-conversation .candidate{background:#f4faf7;margin:12px -8px;padding:20px 16px;border:0;border-radius:8px}.report-conversation p{white-space:pre-wrap;overflow-wrap:anywhere;color:var(--neutral-700)}.report-evidence-grid :deep(.teaching-feedback){padding:0;border-top:0}.report-evidence-grid :deep(.teaching-feedback h2){margin-bottom:16px}.report-evidence-grid :deep(.teaching-feedback form){margin-top:24px;border-top:1px solid var(--neutral-200);padding-top:24px}.report-evidence-grid :deep(.teaching-feedback textarea){min-height:150px;border-radius:8px;background:var(--neutral-50)}
@media(max-width:1000px){.report-findings{grid-template-columns:1fr}.report-intro{grid-template-columns:1fr}.report-grades{padding:24px 0 0;border-left:0;border-top:1px solid var(--neutral-200)}.report-scorebars{grid-template-columns:1fr}.report-evidence-grid{grid-template-columns:1fr}}@media(max-width:600px){.report-scorebars>div{grid-template-columns:100px minmax(30px,1fr) 40px;gap:10px}.report-grades{gap:16px}.report-grades dd{font-size:27px}}
</style>
