<template>
<div class="teacher-analytics-route"><LiveTeacherAnalytics v-if="route.query.demo!=='1'"/><AppLayout v-else><main class="analytics-page">
 <div class="analytics-notice"><span>{{demo?'演示模式 · 复用已有班级与训练记录，目标80为演示配置。示例时间：2026年10月3日。':'分析统计接口尚未接入，真实数据暂不可用。'}}</span><button class="analytics-link" @click="set({demo:demo?undefined:'1'})">{{demo?'切换真实数据':'查看演示效果'}}</button></div>
 <header class="analytics-header"><div><h1>数据分析</h1><p>从更长时间和更大范围观察训练趋势、班级差异与能力结构</p></div><div><button @click="definitionsOpen=true">指标说明</button><button class="analytics-primary" :disabled="!demo||!!error||!!ctx.error||!scoped.students.length" @click="exportOpen=true">导出分析</button></div></header>
 <nav class="analytics-tabs" aria-label="分析类型"><button v-for="t in tabs" :key="t.id" :aria-current="tab===t.id?'page':undefined" :class="{active:tab===t.id}" @click="set({tab:t.id,roleId:undefined})">{{t.name}}</button></nav>
 <form class="analytics-filters" @submit.prevent>
  <label>时间范围<select aria-label="时间范围" :value="ctx.period" @change="set({timeRange:$event.target.value})"><option value="30d">近30天</option><option value="90d">近90天</option><option value="semester">本学期</option><option value="custom">自定义</option></select></label>
  <template v-if="ctx.period==='custom'"><label>开始日期<input type="date" aria-label="开始日期" :value="q.from||ctx.from" @change="set({from:$event.target.value})"/></label><label>结束日期<input type="date" aria-label="结束日期" :max="today" :value="q.to||ctx.to" @change="set({to:$event.target.value})"/></label></template>
  <details class="analytics-class-picker"><summary>班级：{{ctx.classIds.length?ctx.classIds.length+'个班级':'全部班级'}}</summary><fieldset><legend>{{tab==='classes'?'选择2–4个班级进行对比':'统计班级范围'}}</legend><label v-for="c in classDefinitions" :key="c.id"><input type="checkbox" :checked="ctx.classIds.includes(c.id)" :disabled="tab==='classes'&&ctx.classIds.length>=4&&!ctx.classIds.includes(c.id)" @change="toggleClass(c.id)"/>{{c.name}}</label><button type="button" @click="set({classIds:undefined})">全部班级</button></fieldset></details>
  <label>年级<select aria-label="年级" :value="q.grade||''" @change="set({grade:$event.target.value})"><option value="">全部年级</option><option>2025级</option></select></label><label>专业<select aria-label="专业" :value="q.major||''" @change="set({major:$event.target.value})"><option value="">全部专业</option><option>软件工程</option></select></label>
  <label v-if="tab==='intervention'">训练类型<select aria-label="训练类型" :value="q.trainingType||''" @change="set({trainingType:$event.target.value})"><option value="">全部</option><option value="ABILITY">能力专项</option><option value="POSITION">岗位专项</option><option value="COMPREHENSIVE">综合训练</option></select></label>
  <label v-if="tab==='overview'||tab==='intervention'">{{q.trainingType==='POSITION'?'对应岗位能力':'对应通用能力'}}<select aria-label="通用能力" :value="ability.id" @change="set({abilityId:$event.target.value})"><option v-for="a in selectableAbilities" :key="a.id" :value="a.id">{{a.name}}</option></select></label>
  <label v-if="tab==='roles'">岗位方向<select aria-label="岗位方向" :value="q.roleId||''" @change="set({roleId:$event.target.value})"><option value="">全部岗位</option><option v-for="r in roleDistribution" :key="r.name">{{r.name}}</option></select></label>
 </form>
 <div class="analytics-context"><span>{{ctx.from}} ～ {{ctx.to}} · 当前有效学生{{scoped.students.length}}人</span><button class="analytics-link" @click="set({classIds:undefined,grade:undefined,major:undefined,roleId:undefined})">重置范围</button></div>
 <p v-if="ctx.error" role="alert" class="analytics-empty">{{ctx.error}}</p><section v-else-if="error" class="analytics-empty" role="alert"><p>{{error}}</p><button @click="load">重试加载</button></section><p v-else-if="loading" class="analytics-empty" role="status">正在加载分析数据…</p><p v-else-if="!demo" class="analytics-empty">暂无授权的分析数据。可切换演示模式查看页面与交互。</p><p v-else-if="!scoped.students.length" class="analytics-empty">没有可分析的班级数据，请调整筛选范围。</p>
 <template v-else>
  <div v-if="tab==='overview'" class="analytics-grid">
   <section><h2>训练覆盖趋势</h2><p>每周至少1次有效训练的学生 / 当前有效学生。分母采用当前名单，未还原历史入班状态。</p><AnalyticsChart :points="trend" :series="[{key:'coverage',name:'训练覆盖率'}]" percent label="每周训练覆盖率" @select="openRecords"/></section>
   <section><h2>有效训练量趋势</h2><p>按有效训练记录来源统计；最后一周可能未满周。</p><AnalyticsChart :points="trend" :series="sourceSeries" stack label="每周有效训练量" @select="openRecords"/></section>
   <section><h2>到期任务按期完成率</h2><p>按期完成的分配人次 / 对应周已到期且完成时间可确认的分配人次。</p><AnalyticsChart :points="trend" :series="[{key:'onTime',name:'按期完成率'}]" percent label="每周到期任务按期完成率" @select="openTasks"/><p v-if="overallExecution.unknown" class="analytics-warning">{{overallExecution.unknown}}条已完成分配缺少完成时间，未纳入完成率。</p></section>
   <section><h2>{{ability.name}}目标达成趋势</h2><p>先按学生生成当前能力值，再计算达到目标的比例。仅使用最大同版本样本组，版本切换断线。</p><AnalyticsChart :points="trend" :series="[{key:'achievement',name:'目标达成率'}]" percent sample label="通用能力目标达成率" @select="openRecords"/></section>
  </div>
  <template v-if="tab==='classes'"><p v-if="comparison.length<2||comparison.length>4" class="analytics-empty">请选择2–4个班级进行对比。</p><div v-else class="analytics-grid">
   <section><h2>班级训练参与率</h2><p>所选周期有有效训练的学生占比，不按高低排名。</p><div v-for="c in comparison" :key="c.id" class="analytics-bar-row"><RouterLink :to="classLink(c)">{{c.name}}</RouterLink><div class="analytics-track"><i :style="{width:(c.participation||0)+'%'}"/></div><span>{{fmt(c.participation)}}%</span></div><div class="analytics-table-scroll"><table><thead><tr><th>班级</th><th>有效学生</th><th>人均有效训练</th></tr></thead><tbody><tr v-for="c in comparison" :key="c.id"><td>{{c.name}}</td><td>{{c.n}}人</td><td>{{fmt(c.frequency)}}次</td></tr></tbody></table></div></section>
   <section><h2>班级任务执行结构</h2><p>已到期的分配人次；手动结束的任务不纳入到期统计。</p><div v-for="c in comparison" :key="c.id" class="analytics-execution"><RouterLink :to="classLink(c)">{{c.name}}</RouterLink><ExecutionBar :stats="c.execution"/><small v-if="c.execution.unknown">另有{{c.execution.unknown}}条完成时间缺失</small></div></section>
   <section><h2>通用能力目标差距矩阵</h2><p>当前平均值－目标平均值。学生等权，缺失目标不补值。</p><div class="analytics-table-scroll"><table><thead><tr><th>班级</th><th v-for="a in common" :key="a.id">{{a.name}}</th></tr></thead><tbody><tr v-for="c in comparison" :key="c.id"><td><RouterLink :to="classLink(c)">{{c.name}}</RouterLink></td><td v-for="a in c.abilities" :key="a.id" :title="sampleNote(a)">{{signed(a.gap)}}<small>{{a.n}}人 · {{a.version||'暂无版本'}}</small></td></tr></tbody></table></div></section>
   <section><h2>自主 / 教师任务训练结构</h2><p>有效训练记录的来源比例，同时保留记录数。</p><div v-for="c in comparison" :key="c.id" class="analytics-execution"><strong>{{c.name}}</strong><SourceBar :self="c.self" :teacher="c.teacherTask"/></div></section>
  </div></template>
  <div v-if="tab==='intervention'" class="analytics-grid">
   <section><h2>训练来源变化</h2><p>仅描述有效记录来源比例；训练类型仅筛选教师任务执行及前后比较。</p><AnalyticsChart :points="sourceTrend" :series="sourceSeries" stack percent label="训练来源比例变化" @select="openRecords"/></section>
   <section><h2>到期任务执行结构</h2><ExecutionBar :stats="intervention.execution"/><p v-if="intervention.execution.unknown" class="analytics-warning">另有{{intervention.execution.unknown}}条已完成分配缺少完成时间，未参与比例计算。</p></section>
   <section><h2>任务完成前后可比表现</h2><p>任务开始前最近一次与完成后14天内最近一次对应能力评分，同岗位、模型与版本；每位学生取最近完成任务。</p><p>完成人数{{intervention.completed}} · 同口径可比人数{{intervention.n}}<span v-if="intervention.excluded"> · 其他版本{{intervention.excluded}}人未混合</span></p><p v-if="intervention.n<5" class="analytics-empty">暂无足够数据生成聚合差值（至少5人）。</p><template v-else><dl class="analytics-values"><dt>完成前可比值</dt><dd>{{fmt(intervention.before)}}</dd><dt>完成后可比值</dt><dd>{{fmt(intervention.after)}}</dd><dt>前后统计差值</dt><dd>{{signed(intervention.diff)}}</dd></dl><p>{{intervention.version}}</p><p v-if="intervention.n<10" class="analytics-warning">样本较少，仅供参考</p></template><p class="analytics-warning">该变化为任务完成前后可比训练记录的统计差值，不代表任务本身造成该变化。</p></section>
   <section><h2>后续表现变化分布</h2><p>沿用D03规则，需要观察窗口内至少6条可比记录；两次评分差值不直接判定成长状态。</p><dl class="analytics-values"><template v-for="(label,key) in outcomeLabels" :key="key"><dt>{{label}}</dt><dd>{{intervention.outcomes[key]}}人</dd></template></dl><p>同版本可比组{{intervention.n}}人；数据不足包含无前后配对、其他版本及历史记录不足。</p></section>
   <section class="analytics-wide"><div class="analytics-section-head"><h2>相关训练任务</h2><button class="analytics-link" @click="openTasks()">查看全部任务 →</button></div><div v-if="relatedTasks.length" class="analytics-table-scroll"><table><thead><tr><th>任务</th><th>班级</th><th>截止时间</th><th>当前已完成分配</th><th>可比人数</th><th>后续变化</th><th>操作</th></tr></thead><tbody><tr v-for="t in relatedTasks" :key="t.id"><td>{{t.title}}</td><td>{{classDefinitions.find(c=>c.id===t.classId)?.name}}</td><td>{{t.deadline?.slice(0,10)}}</td><td>{{(t.executions||[]).filter(e=>e.completionStatus==='COMPLETED'&&scoped.students.some(s=>s.id===e.studentId)).length}}</td><td>{{t.analytics.n}}人</td><td>提升{{t.analytics.outcomes.improved}} / 稳定{{t.analytics.outcomes.stable}} / 下降{{t.analytics.outcomes.declined}} / 不足{{t.analytics.outcomes.insufficient}}</td><td><RouterLink :to="taskLink(t)">查看任务 →</RouterLink></td></tr></tbody></table></div><p v-else class="analytics-empty">所选范围暂无教师训练任务。</p></section>
  </div>
  <div v-if="tab==='roles'" class="analytics-grid">
   <section><h2>目标岗位分布</h2><p>当前有效学生的目标岗位人数分布，非热门岗位排行。</p><div v-for="r in (showAllRoles?roleDistribution:roleDistribution.slice(0,5))" :key="r.name" class="analytics-bar-row"><button class="analytics-link" @click="set({roleId:r.name})">{{r.name}}</button><div class="analytics-track"><i :style="{width:r.ratio+'%'}"/></div><span>{{r.count}}人</span></div><p v-if="roleDistribution.length>5&&!showAllRoles">其他：{{roleDistribution.slice(5).reduce((n,r)=>n+r.count,0)}}人</p><button v-if="roleDistribution.length>5" @click="showAllRoles=!showAllRoles">{{showAllRoles?'收起':'展开全部岗位'}}</button><RouterLink :to="studentsLink()">查看相关学生 →</RouterLink></section>
   <section><h2>通用能力整体差距{{q.roleId?' · '+q.roleId:''}}</h2><AbilityTable :rows="roleAbilities"/><p>仅聚合同一通用评分版本的学生，演示目标80；不足5人不展示聚合值。</p></section>
   <section><h2>岗位专业能力结构</h2><p v-if="!q.roleId" class="analytics-empty">请选择具体岗位，再查看该岗位专业能力。</p><template v-else><AbilityTable :rows="professional"/><p>现有记录仅提供“专业知识 / 岗位实践”，未提供Java基础等细项及岗位目标，不能补造差距。</p><RouterLink :to="studentsLink(q.roleId)">查看该岗位学生 →</RouterLink></template></section>
   <section><h2>岗位 × 通用能力差距矩阵</h2><div class="analytics-table-scroll"><table><thead><tr><th>岗位方向</th><th v-for="a in common" :key="a.id">{{a.name}}</th></tr></thead><tbody><tr v-for="r in roleMatrix" :key="r.name"><td><RouterLink :to="studentsLink(r.name)">{{r.name}}</RouterLink></td><td v-for="a in r.abilities" :key="a.id" :title="sampleNote(a)">{{signed(a.gap)}}<small>{{a.n}}人</small></td></tr></tbody></table></div></section>
  </div>
 </template>
 <TeacherDrawer :open="definitionsOpen" title="指标与计算口径" @close="definitionsOpen=false"><p>指标定义版本：{{metricsVersion}}</p><dl><template v-for="d in definitions" :key="d[0]"><dt>{{d[0]}}</dt><dd>{{d[1]}}</dd></template></dl><p>所有分析仅反映统计关联。真实班级权限、目标配置和指标应由后端统一返回；当前演示不代表生产授权。</p></TeacherDrawer>
 <TeacherDrawer :open="exportOpen" title="导出分析数据" class="analytics-export" @close="exportOpen=false"><p>{{tabs.find(t=>t.id===tab).name}} · {{ctx.from}}～{{ctx.to}}</p><p>{{scopeLabel}}</p><form class="analytics-export-form" @submit.prevent="download"><label>导出范围<select v-model="exportScope"><option value="view">当前分析视图</option><option value="tab">当前Tab全部数据</option><option value="scope">当前筛选范围数据</option></select></label><p>{{exportScope==='view'?'保留当前Tab及能力、岗位和训练类型选择。':exportScope==='tab'?'导出当前Tab的全部能力、岗位和训练类型，不改变公共筛选。':'导出四个Tab的汇总，保留公共时间、班级、年级和专业筛选。'}}</p><label>文件格式<select v-model="exportFormat"><option value="xlsx">Excel (.xlsx)</option><option value="csv">CSV (.csv)</option></select></label><fieldset><legend>包含内容</legend><label><input v-model="includeSummary" type="checkbox"/>汇总数据</label><label><input v-model="includeDetails" type="checkbox"/>明细数据</label><p>指标说明、筛选与版本信息始终附带。图表图片和PDF导出尚未提供。</p></fieldset><label>文件名<input v-model="fileName" required maxlength="100"/></label><p v-if="exportError" role="alert">{{exportError}}</p><p v-if="exportSuccess" role="status">文件已生成并开始下载。</p><button class="analytics-primary" :disabled="generating||(!includeSummary&&!includeDetails)">{{generating?'正在生成…':'导出文件'}}</button></form></TeacherDrawer>
</main></AppLayout></div>
</template>
<script setup>
import LiveTeacherAnalytics from './LiveTeacherAnalytics.vue'
import {normalizeTeacherQuery,teacherContext,safeTeacherReturn} from '../../services/teacherContext.js'
import {computed,ref,watch,h,defineComponent} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import AppLayout from '../../components/layout/AppLayout.vue'
import TeacherDrawer from '../../components/teacher/TeacherDrawer.vue'
import AnalyticsChart from '../../components/teacher/AnalyticsChart.vue'
import {analyticsDataset,contextFor,scopeData,trends,classComparison,interventions,aggregate,common,classDefinitions,metricsVersion,ratio,dueRows,executionStats} from '../../services/analytics.js'
import {abilityDefinitions} from '../../services/studentCenter.js'
import {downloadAnalytics} from '../../services/analyticsExport.js'
import '../../assets/styles/analytics.css'
const route=useRoute(),router=useRouter(),q=computed(()=>normalizeTeacherQuery(route.query)),demo=computed(()=>q.value.demo==='1'),tabs=[{id:'overview',name:'趋势总览'},{id:'classes',name:'班级对比'},{id:'intervention',name:'训练与干预'},{id:'roles',name:'岗位与能力结构'}]
const tab=computed(()=>tabs.some(t=>t.id===q.value.tab)?q.value.tab:'overview'),data=ref({students:[],records:[],tasks:[],now:Date.now()}),error=ref(''),loading=ref(false)
function load(){loading.value=true;error.value='';try{data.value=analyticsDataset(demo.value)}catch(e){error.value='数据加载失败：'+e.message}finally{loading.value=false}}
watch(demo,load,{immediate:true})
const ctx=computed(()=>contextFor(q.value,data.value.now)),today=computed(()=>new Date(data.value.now+8*3600000).toISOString().slice(0,10)),scoped=computed(()=>ctx.value.error?{...data.value,students:[],records:[],tasks:[]}:scopeData(data.value,ctx.value)),selectableAbilities=computed(()=>tab.value==='intervention'&&q.value.trainingType==='POSITION'?abilityDefinitions.filter(a=>a.scope==='role'):common),ability=computed(()=>selectableAbilities.value.find(a=>a.id===q.value.abilityId||a.name===q.value.ability)||selectableAbilities.value[0])
function set(values){const query={...q.value,...values};if('classIds' in values){delete query.classId;delete query.class}if('timeRange' in values){delete query.period;delete query.from;delete query.to;delete query.analyticsFrom;delete query.analyticsTo}router.replace({path:'/teacher/analytics',query})}
function toggleClass(id){let ids=[...ctx.value.classIds];ids=ids.includes(id)?ids.filter(v=>v!==id):ids.concat(id);set({classIds:ids.join(',')||undefined})}
const trend=computed(()=>ctx.value.error?[]:trends(scoped.value,ctx.value,ability.value)),sourceSeries=[{key:'self',name:'学生自主训练'},{key:'teacherTask',name:'教师任务训练'}],sourceTrend=computed(()=>trend.value.map(p=>({...p,self:ratio(p.self,p.self+p.teacherTask),teacherTask:ratio(p.teacherTask,p.self+p.teacherTask)})))
const comparison=computed(()=>classComparison(scoped.value,ctx.value,ctx.value.classIds.length?ctx.value.classIds:classDefinitions.filter(c=>scoped.value.students.some(s=>s.classId===c.id)).map(c=>c.id)))
const overallExecution=computed(()=>executionStats(dueRows(scoped.value,ctx.value)))
const intervention=computed(()=>interventions(scoped.value,ctx.value,ability.value,q.value.trainingType)),outcomeLabels={improved:'有效提升',stable:'基本稳定',declined:'下降',insufficient:'数据不足'}
const relatedTasks=computed(()=>intervention.value.tasks.filter(t=>Date.parse(t.startTime)<=ctx.value.end&&Date.parse(t.deadline)>=ctx.value.start).map(t=>({...t,analytics:interventions({...scoped.value,tasks:[t]},ctx.value,ability.value,q.value.trainingType)})))
const roleDistribution=computed(()=>[...new Set(scoped.value.students.map(s=>s.position||'未设置'))].map(name=>({name,count:scoped.value.students.filter(s=>(s.position||'未设置')===name).length,ratio:ratio(scoped.value.students.filter(s=>(s.position||'未设置')===name).length,scoped.value.students.length)}))),showAllRoles=ref(false)
const roleData=name=>({...scoped.value,students:scoped.value.students.filter(s=>!name||s.position===name),records:scoped.value.records.filter(r=>!name||r.position===name)})
const roleAbilities=computed(()=>common.map(a=>aggregate(roleData(q.value.roleId),a))),roleMatrix=computed(()=>roleDistribution.value.map(r=>({...r,abilities:common.map(a=>aggregate(roleData(r.name),a))})))
const professional=computed(()=>abilityDefinitions.filter(a=>a.scope==='role').map(a=>aggregate(roleData(q.value.roleId),a)))
const fmt=v=>Number.isFinite(v)?v.toFixed(1):'数据不足',signed=v=>Number.isFinite(v)?(v>0?'+':'')+v.toFixed(1):'数据不足',sampleNote=a=>`${a.n}人 · ${a.version||'暂无可比版本'}${a.n<10?' · 样本较少':''}${a.excluded?' · 排除其他版本'+a.excluded+'人':''}`
const returnTo=computed(()=>route.fullPath),baseQuery=()=>({grade:ctx.value.grade||undefined,major:ctx.value.major||undefined,analyticsActive:'1',demo:demo.value?'1':undefined,returnTo:returnTo.value,analyticsFrom:ctx.value.from,analyticsTo:ctx.value.to,classIds:ctx.value.classIds.join(',')||undefined})
function openRecords(p){router.push({path:'/teacher/training-records',query:{...baseQuery(),insights:'1',from:p?.date||ctx.value.from,to:p?.to||ctx.value.to,class:ctx.value.classIds.length===1?classDefinitions.find(c=>c.id===ctx.value.classIds[0])?.name:undefined}})}
function openTasks(p){router.push({path:'/teacher/tasks',query:{...baseQuery(),from:p?.date||ctx.value.from,to:p?.to||ctx.value.to,type:q.value.trainingType,ability:q.value.trainingType==='ABILITY'?ability.value.name:undefined,analyticsDue:'1'}})}
const classLink=c=>({path:'/teacher/classes/'+c.id,query:{...baseQuery(),tab:'overview'}}),taskLink=t=>({path:'/teacher/tasks/'+t.id,query:baseQuery()}),studentsLink=role=>({path:'/teacher/students',query:{...baseQuery(),position:role||q.value.roleId,analyticsActive:'1',classId:ctx.value.classIds.length===1?ctx.value.classIds[0]:undefined}})
const ExecutionBar=defineComponent({props:['stats'],setup:p=>()=>h('div',{class:'analytics-execution-bar'},[p.stats.total?h('div',{class:'analytics-stack'},['onTime','late','unfinished'].map((k,i)=>h('span',{style:{width:ratio(p.stats[k],p.stats.total)+'%',background:['#177b57','#bd7428','#b54f48'][i]},title:['按期完成','逾期完成','未完成'][i]+'：'+p.stats[k]},p.stats[k]?Math.round(ratio(p.stats[k],p.stats.total))+'%':''))):h('p','暂无可统计的已到期分配'),h('p',`按期完成 ${p.stats.onTime} · 逾期完成 ${p.stats.late} · 未完成 ${p.stats.unfinished}（分配人次）`)])})
const SourceBar=defineComponent({props:['self','teacher'],setup:p=>()=>h('div',[p.self+p.teacher?h('div',{class:'analytics-stack'},[h('span',{style:{width:ratio(p.self,p.self+p.teacher)+'%',background:'#177b57'}},Math.round(ratio(p.self,p.self+p.teacher))+'%'),h('span',{style:{width:ratio(p.teacher,p.self+p.teacher)+'%',background:'#9ddfc3',color:'#173d30'}},Math.round(ratio(p.teacher,p.self+p.teacher))+'%')]):h('p','暂无有效训练记录'),h('p',`自主 ${p.self}次 · 教师任务 ${p.teacher}次`)])})
const AbilityTable=defineComponent({props:['rows'],setup:p=>()=>h('div',{class:'analytics-table-scroll'},h('table',[h('thead',h('tr',['能力','当前均值','目标均值','差距','样本'].map(t=>h('th',t)))),h('tbody',p.rows.map(a=>h('tr',[h('td',a.ability),h('td',fmt(a.current)),h('td',a.target===null?'未配置或不足':fmt(a.target)),h('td',signed(a.gap)),h('td',{title:sampleNote(a)},sampleNote(a))])))]))})
const definitionsOpen=ref(false),exportOpen=ref(false),exportScope=ref('view'),exportFormat=ref('xlsx'),includeSummary=ref(true),includeDetails=ref(false),fileName=ref(''),generating=ref(false),exportError=ref(''),exportSuccess=ref(false)
const definitions=[['有效训练','复用已有有效记录标记；总评分需为0–100，完成时间有效。缺失不补0。'],['训练覆盖 / 人均次数','覆盖学生去重；分母为当前有效班级成员，停用账号不纳入。'],['当前能力值','所选时间范围截至统计时点，当前连续岗位和模型阶段最近最多3次有效能力评分平均。'],['能力聚合','学生等权；当前值与目标来自同一批学生。不同版本分组，展示最大样本组并说明排除数。'],['目标达成率','达到已配置目标人数 / 同版本且有能力和目标的学生数。演示通用目标80，真实目标不回退。'],['样本阈值','能力聚合少于5人停止显示；5–9人提示样本较少。单个学生当前值可有1–3条记录。'],['到期任务执行','所选范围截止时间已到期的任务分配；手动结束排除。完成时间缺失单独提示，不参与比例。'],['前后比较','任务开始前 / 完成后14天内最近一次同岗位、模型、版本评分。不同模型不混合，无因果推断。'],['后续变化','复用D03：至少6条记录，前3次与最近3次均值差±3；最近3次严格下降且累计下降≥5优先为持续下降。']]
const scopeLabel=computed(()=>`${ctx.value.classIds.map(id=>classDefinitions.find(c=>c.id===id)?.name||id).join('、')||'全部班级'} · ${q.value.grade||'全部年级'} · ${q.value.major||'全部专业'}`)
watch(exportOpen,open=>{if(open){fileName.value=`OfferPilot_${tabs.find(t=>t.id===tab.value).name}_${ctx.value.from}_${ctx.value.to}`;exportError.value='';exportSuccess.value=false}})
async function download(){generating.value=true;exportError.value='';exportSuccess.value=false;try{await downloadAnalytics({format:exportFormat.value,fileName:fileName.value,scope:exportScope.value,tab:tab.value,data:scoped.value,context:ctx.value,ability:ability.value,type:q.value.trainingType,role:q.value.roleId,summary:includeSummary.value,details:includeDetails.value,definitions,scopeLabel:scopeLabel.value});exportSuccess.value=true}catch(e){exportError.value='导出失败：'+e.message}finally{generating.value=false}}
</script>
