<template><AppLayout><main class="teacher-account teaching-portal"><h1>教师个人中心</h1><p>管理账号资料与安全设置。</p><p v-if="loading" role="status">正在加载账号…</p><p v-if="error" role="alert">{{error}} <button @click="load">重试</button></p><template v-if="me"><section class="live-panel account-profile"><h2>账号信息</h2><dl><dt>用户名</dt><dd>{{me.username||'未提供'}}</dd><dt>身份</dt><dd>{{me.role==='ADMIN'?'管理员':'教师'}}</dd><dt>邮箱</dt><dd>{{me.email||'未绑定'}}</dd></dl></section><section class="live-panel account-edit"><h2>个人资料</h2><p>修改昵称后，教学页和点评署名会同步更新。</p><form @submit.prevent="save"><label for="teacher-nickname">昵称</label><input id="teacher-nickname" v-model.trim="nickname" maxlength="30" required/><button :disabled="saving">{{saving?'正在保存…':'保存昵称'}}</button><p v-if="success" role="status">昵称已更新。</p></form></section></template><RouterLink to="/teacher/settings">账号安全与密码设置 →</RouterLink></main></AppLayout></template>
<script setup>
import '../../assets/styles/teaching-live.css'
import {ref,onMounted} from 'vue'
import AppLayout from '../../components/layout/AppLayout.vue'
import {getMe,updateProfile} from '../../api'
import {useUserStore} from '../../store/user'
const me=ref(null),nickname=ref(''),loading=ref(false),saving=ref(false),error=ref(''),success=ref(false),store=useUserStore()
async function load(){loading.value=true;error.value='';try{me.value=await getMe();nickname.value=me.value.nickname||''}catch(e){error.value='账号读取失败，请重试。'}finally{loading.value=false}}
async function save(){saving.value=true;error.value='';success.value=false;try{await updateProfile({nickname:nickname.value});me.value={...me.value,nickname:nickname.value};store.syncProfile(me.value);success.value=true}catch(e){error.value=e.message||'保存失败，请重试。'}finally{saving.value=false}}
onMounted(load)
</script>
<style scoped>.teacher-account{max-width:900px;margin:auto;padding:32px 24px;color:#111827;font-size:14px}.teacher-account h1{font-size:28px;margin-bottom:20px}.teacher-account p{line-height:1.8;color:#526159;margin:16px 0}.teacher-account dl{display:grid;grid-template-columns:100px 1fr;gap:20px;margin:32px 0}.teacher-account dd{margin:0}.teacher-account form{display:grid;gap:16px;max-width:460px;margin-bottom:36px}.teacher-account input,.teacher-account button{font:inherit;padding:12px;border:1px solid #d4dbd7;border-radius:6px;min-height:44px}.teacher-account button{background:#2ab783;color:#102e22;cursor:pointer}.teacher-account a{color:#14704f}.teacher-account :focus-visible{outline:2px solid #177b57;outline-offset:3px}.teacher-account .live-panel{margin:24px 0;padding:28px}.teacher-account .live-panel h2{margin-bottom:12px}.teacher-account dl{margin:24px 0 8px}.teacher-account form{max-width:560px;margin:24px 0 0}.teacher-account button{background:var(--accent-500);color:var(--neutral-900);border-color:var(--accent-500);font-weight:600}.teacher-account p[role=alert]{padding:20px;background:#fef2f2;border:1px solid #fecaca;border-radius:12px}@media(max-width:600px){.teacher-account{padding:20px 0}.teacher-account .live-panel{padding:20px}}
</style>
