<template>
<TeachingReport v-if="route.query.demo!=='1'"/><AppLayout v-else><main class="teacher-report-detail">
 <RouterLink :to="back" class="report-back">← {{backLabel}}</RouterLink>
 <header><div><h1>训练报告</h1><p>{{demo?'演示模式 · 原始训练记录与本机教师点评，不写入真实系统。':'教师报告授权接口尚未接入。'}}</p></div><button @click="load">刷新报告</button></header>
 <p v-if="loading" class="report-empty" role="status">正在读取报告…</p><section v-else-if="error" class="report-empty" role="alert"><p>{{error}}</p><button @click="load">重试</button></section>
 <section v-else-if="!demo" class="report-empty"><h2>报告暂不可访问</h2><p>尚未提供教师报告权限与详情接口，无法读取其他用户的私有报告。</p></section>
 <section v-else-if="!record" class="report-empty"><h2>未找到报告</h2><p>该报告不存在、已归档或不属于当前班级名单。请返回来源页面重新选择。</p></section>
 <template v-else>
  <section class="report-identity"><h2>{{record.content}}</h2><p>{{student?.name}} · {{student?.number}} · {{student?.className}} · {{record.position}}</p><dl><dt>报告状态</dt><dd>{{statusLabel}}</dd><dt>训练完成</dt><dd>{{formatDate(record.completedAt)}}</dd><dt>训练形式</dt><dd>{{record.type}}</dd><dt>训练时长</dt><dd>{{record.duration||'未提供'}}</dd><dt>训练来源</dt><dd>{{record.source==='SELF'?'学生自主训练':'教师任务'}}</dd><dt>关联任务</dt><dd><RouterLink v-if="task" :to="taskLink">{{task.title}} →</RouterLink><span v-else>无关联任务</span></dd><dt>{{record.scoreScope?record.scoreScope+'评分':'本次报告评分'}}</dt><dd>{{record.valid&&Number.isFinite(record.score)?record.score.toFixed(1)+'/100':'评分无效或缺失'}}</dd><dt>评分口径</dt><dd>{{record.model||'未说明'}} / {{record.version||'未说明'}}</dd></dl><details><summary>查看来源标识</summary><p>训练记录：{{record.id}}</p><p>报告：{{record.reportId}}</p></details></section>
  <p v-if="status!=='READY'" class="report-empty" role="status">{{status==='GENERATING'?'报告正在生成，暂未提供可读取的完整结果。':status==='FAILED'?'报告生成失败或评分无效，请查看训练记录并重试读取。':'原报告不可访问，仅保留已有训练元信息。'}}</p>
  <template v-else>
   <section><h2>能力评分</h2><p v-if="!dimensions.length" class="report-empty">原报告未提供有效能力维度评分。</p><div v-else class="report-table"><table><thead><tr><th>能力</th><th>本次评分</th><th>原报告说明</th></tr></thead><tbody><tr v-for="a in dimensions" :key="a.name"><td>{{a.name}}</td><td>{{Number.isFinite(a.value)?a.value.toFixed(1)+'/100':'数据不足'}}</td><td>{{a.explanation||'原报告未提供说明'}}</td></tr></tbody></table></div><p>缺失维度不补0；单项任务结果不补造其他能力或综合评分。</p></section>
   <section><h2>逐题回答与评价</h2><p v-if="!questions.length" class="report-empty">当前报告未提供逐题问题、回答与评价原文。</p><article v-for="(item,i) in questions" :key="item.id||i" class="report-answer"><h3>{{i+1}}. {{item.question||item.prompt||'问题原文未提供'}}</h3><p><strong>学生回答：</strong>{{item.answer||'回答原文未提供'}}</p><p><strong>原报告评价：</strong>{{item.feedback||item.evaluation||'评价原文未提供'}}</p><p v-if="item.evidence"><strong>引用证据：</strong>{{item.evidence}}</p></article></section>
   <section><h2>可追溯表现证据</h2><p v-if="!evidence.length" class="report-empty">当前报告未提供可追溯的表现证据原文。评分不作为回答内容或能力原因的替代。</p><blockquote v-for="(e,i) in evidence" :key="i"><strong>{{e.kind==='positive'?'正向表现':'待改善表现'}} · {{e.abilityId}}</strong><p>{{e.text}}</p></blockquote></section>
   <section><h2>同口径历史记录</h2><p>仅比较同岗位、模型和版本的报告评分。变化不表示训练造成了能力提升。</p><div v-if="related.length" class="report-table"><table><thead><tr><th>完成时间</th><th>训练</th><th>报告评分</th><th>操作</th></tr></thead><tbody><tr v-for="r in related.slice(0,10)" :key="r.id"><td>{{formatDate(r.completedAt)}}</td><td>{{r.content}}</td><td>{{r.score.toFixed(1)}}</td><td><RouterLink :to="{path:'/teacher/reports/'+r.reportId,query:q}">查看报告</RouterLink></td></tr></tbody></table></div><p v-else class="report-empty">暂无其他同口径有效报告。</p></section>
  </template>
  <section><h2>教师点评</h2><p v-if="!record.reviewHistory.length">尚无教师点评。</p><article v-for="entry in record.reviewHistory" :key="entry.id" class="report-review"><p>{{entry.text}}</p><small>{{entry.author}} · {{formatDate(entry.at)}}</small></article><form v-if="status==='READY'" @submit.prevent="save"><label for="teacher-review">新增点评</label><textarea id="teacher-review" v-model="review" required maxlength="5000" rows="5" placeholder="结合已有评分和报告原文填写，不推测未提供的回答。"/><button :disabled="saving||!review.trim()">{{saving?'正在保存…':'保存演示点评'}}</button><p v-if="saved" role="status">点评已保存到本机演示资料；待点评状态已更新，真实报告未修改。</p><p v-if="saveError" role="alert">{{saveError}}</p></form></section>
 </template>
</main></AppLayout>
</template>
<script setup>
import TeachingReport from './TeachingReport.vue'
import {computed,ref,watch,nextTick} from 'vue'
import {useRoute} from 'vue-router'
import AppLayout from '../../components/layout/AppLayout.vue'
import {teacherDataset,saveReportReview} from '../../services/teacherData.js'
import {normalizeTeacherQuery,teacherContext,safeTeacherReturn} from '../../services/teacherContext.js'
const formatDate=value=>value?new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'未提供'
const route=useRoute(),q=computed(()=>normalizeTeacherQuery(route.query)),demo=computed(()=>q.value.demo==='1'),data=ref(null),loading=ref(false),error=ref(''),review=ref(''),saveError=ref(''),saved=ref(false),saving=ref(false)
async function load(){loading.value=true;error.value='';await nextTick();try{data.value=demo.value?teacherDataset():null}catch(e){error.value='报告读取失败：'+e.message}finally{loading.value=false}}
watch(()=>[route.params.id,demo.value],()=>{review.value='';saved.value=false;saveError.value='';load()},{immediate:true})
const record=computed(()=>data.value?.records.find(r=>r.reportId===route.params.id||r.id===route.params.id)),student=computed(()=>data.value?.students.find(s=>s.id===record.value?.studentId)),task=computed(()=>data.value?.tasks.find(t=>t.id===record.value?.taskId))
const status=computed(()=>record.value?.reportStatus||(record.value?.reportAvailable===false?'UNAVAILABLE':record.value?.valid?'READY':'FAILED')),statusLabel=computed(()=>({READY:'已生成',GENERATING:'生成中',FAILED:'生成失败',UNAVAILABLE:'不可访问'}[status.value]||'状态未说明'))
const back=computed(()=>safeTeacherReturn(q.value.returnTo)||{path:q.value.returnStudent?'/teacher/students/'+q.value.returnStudent:q.value.returnClass?'/teacher/classes/'+q.value.returnClass:'/teacher/training-records',query:{...teacherContext(q.value),returnTo:undefined}})
const backLabel=computed(()=>q.value.returnStudent?'返回学生详情':safeTeacherReturn(q.value.returnTo)?.startsWith('/teacher/reviews')?'返回待办中心':safeTeacherReturn(q.value.returnTo)?.startsWith('/teacher/tasks')?'返回任务详情':q.value.returnClass?'返回班级分析':!q.value.returnTo?'返回训练明细':'返回来源页面')
const taskLink=computed(()=>({path:'/teacher/tasks/'+task.value.id,query:{...teacherContext(q.value),returnTo:route.fullPath}}))
const dimensions=computed(()=>Object.entries({...record.value?.dimensions,...record.value?.roleDimensions}).map(([name,value])=>({name,value,explanation:record.value?.dimensionExplanations?.[name]})))
const questions=computed(()=>Array.isArray(record.value?.questions)?record.value.questions:[]),evidence=computed(()=>(record.value?.evidence||[]).filter(e=>e.trainingRecordId===record.value.id&&e.reportId===record.value.reportId&&e.abilityId&&['positive','improvement'].includes(e.kind)&&typeof e.text==='string'))
const related=computed(()=>(data.value?.records||[]).filter(r=>r.id!==record.value?.id&&r.studentId===record.value?.studentId&&r.valid&&Number.isFinite(r.score)&&r.position===record.value?.position&&r.model===record.value?.model&&r.version===record.value?.version).sort((a,b)=>Date.parse(b.completedAt)-Date.parse(a.completedAt)))
async function save(){saving.value=true;saveError.value='';try{saveReportReview(record.value.reportId,review.value);review.value='';await load();saved.value=true}catch(e){saveError.value='保存失败：'+e.message}finally{saving.value=false}}
</script>
<style scoped>
.teacher-report-detail{max-width:1200px;margin:auto;padding:28px 24px;color:#111827;font-size:14px}.teacher-report-detail header{display:flex;justify-content:space-between;align-items:center;gap:20px;margin:24px 0}.teacher-report-detail h1{font-size:28px}.teacher-report-detail h2{font-size:20px;margin:0 0 18px}.teacher-report-detail h3{font-size:16px}.teacher-report-detail p{line-height:1.8;margin:12px 0;color:#526159}.teacher-report-detail>section{padding:28px 0;border-top:1px solid #e3e7e5}.teacher-report-detail a{color:#14704f}.teacher-report-detail dl{display:grid;grid-template-columns:150px 1fr;gap:16px}.teacher-report-detail dd{margin:0;overflow-wrap:anywhere}.teacher-report-detail dt,small{color:#526159}.report-empty{padding:24px;background:#f6f9f7}.report-table{overflow:auto}.report-table table{border-collapse:collapse;width:100%;min-width:500px}.report-table :is(th,td){padding:16px 12px;border-bottom:1px solid #e3e7e5;text-align:left}.report-table th{background:#f6f9f7;font-weight:500}.teacher-report-detail button{font:inherit;min-height:44px;flex-shrink:0;padding:10px 18px;background:#2ab783;border:0;border-radius:6px;color:#102e22;cursor:pointer}.teacher-report-detail button:disabled{opacity:.55;cursor:not-allowed}.teacher-report-detail textarea{font:inherit;width:100%;padding:14px;border:1px solid #d4dbd7;border-radius:6px;margin:12px 0}.teacher-report-detail details summary{cursor:pointer;min-height:44px;padding:12px 0;color:#526159}.report-review,.report-answer{padding:20px 0;border-bottom:1px solid #e3e7e5}.teacher-report-detail blockquote{margin:20px 0;padding:20px;background:#f6f9f7}.teacher-report-detail :focus-visible{outline:2px solid #177b57;outline-offset:3px}@media(max-width:600px){.teacher-report-detail{padding:20px}.teacher-report-detail dl{grid-template-columns:100px 1fr;gap:14px}.teacher-report-detail header{align-items:start}.teacher-report-detail h1{font-size:24px}}
</style>
