// Local review interactions only; no API requests or business writes.
const missingStudents=Array.from({length:6},(_,i)=>({id:24+i,name:'未评分同学'+(i+1),number:'2501'+(25+i),count:0}));
const allStudents=[...students,...missingStudents];
let inputRange='all',reviewMode='normal';
function inputMatches(s){return inputRange==='all'||(inputRange==='0'?s.count===0:inputRange==='1'?s.count===1:inputRange==='2–4'?s.count>=2&&s.count<=4:s.count>=5)}
function renderInputList(){const rows=allStudents.filter(inputMatches);document.getElementById('input-list').innerHTML=`<div class="panel-head"><div><h2>${inputRange==='all'?'全部教学训练学生':inputRange+' 次训练的学生'}</h2><p>${rows.length} 人 · 频次按当前教学训练记录计算</p></div><button onclick="inputRange='all';renderInputList()">查看全部频次</button></div><div class="students">${rows.map(s=>`<div class="student"><span class="avatar">${s.name[0]}</span><div><b>${s.name}</b><p>${s.count} 次有效教学训练 · ${s.scores?'项目表达 '+s.scores[0]+' 分':'暂无可比评分'}</p></div><button onclick="inputEvidence(${s.id})">查看依据 →</button></div>`).join('')}</div>`}
function inputEvidence(id){if(id<24)return studentEvidence(id);const s=missingStudents[id-24];evidence(s.name+' · 记录覆盖','近30天：0 次有效教学训练，暂无可比评分。<br>这是示例名单；不能据此判断其自主训练情况或能力水平。')}
const inputPanel=document.createElement('section');inputPanel.id='input-list';inputPanel.className='panel wide linked-list';document.getElementById('input').append(inputPanel);
document.getElementById('frequency').innerHTML=[['0',s=>s.count===0],['1',s=>s.count===1],['2–4',s=>s.count>=2&&s.count<=4],['5+',s=>s.count>=5]].map(([key,test])=>{const n=allStudents.filter(test).length;return `<button class="bar-row" onclick="inputRange='${key}';renderInputList()"><span>${key} 次</span><div class="track"><i style="width:${n/30*100}%"></i></div><b>${n} 人</b></button>`}).join('');renderInputList();
const paired=students.slice(0,12).map((s,i)=>({...s,before:60+i%11,after:69+i%11}));
const pairedTable=document.createElement('div');pairedTable.className='table-wrap paired-table';pairedTable.innerHTML=`<h3>配对学生与评分依据</h3><table><thead><tr><th>学生</th><th>训练前</th><th>训练后</th><th>变化</th><th>依据</th></tr></thead><tbody>${paired.map(s=>`<tr><td>${s.name}</td><td>${s.before}</td><td>${s.after}</td><td>+${s.after-s.before}</td><td><button onclick="pairedEvidence(${s.id})">查看前后依据</button></td></tr>`).join('')}</tbody></table>`;document.getElementById('paired').append(pairedTable);
function pairedEvidence(id){const s=paired.find(s=>s.id===id);evidence(s.name+' · 前后配对依据',`训练前：2026-09-08，${s.before} 分。<br>训练后：2026-09-28，${s.after} 分。<br>同岗位：后端开发；同维度：项目表达；同评价方案：v2。<br><br>以上为配对报告演示，不代表真实评价，也不表示训练造成了变化。`)}
// Derive summary bars from the same paired rows displayed below.
document.querySelectorAll('#paired .bar-row').forEach((row,i)=>{const key=i?'after':'before',mean=Math.round(paired.reduce((sum,s)=>sum+s[key],0)/paired.length);row.querySelector('i').style.width=mean+'%';row.querySelector('b').textContent=mean+' 分'});
function reviewState(mode){reviewMode=mode;selected.clear();matrixPage=1;enter(0);const banner=document.getElementById('state-banner'),state=document.getElementById('ability-state'),content=document.getElementById('ability-content');banner.hidden=mode==='normal'||mode==='many';content.hidden=mode==='small'||mode==='missing';state.hidden=!content.hidden;const text={small:'仅 3 名可比评分学生，未达到 5 人汇总要求。班级均值与分布暂不展示。',missing:'已有教学训练记录，但暂无可比评分。次数与参与数据仍可查看。',partial:'4 份评分明细读取失败，当前覆盖不完整。不能将读取失败归为未评分。'};banner.textContent=text[mode]||'';state.innerHTML=mode==='small'?'<h2>样本不足，先查看个人证据</h2><p>保留3名已读取学生的报告入口，不据此推断全班短板。</p><div>'+students.slice(0,3).map(s=>`<button onclick="studentEvidence(${s.id})">${s.name} · 查看依据</button>`).join(' ')+'</div>':'<h2>等待可比评分</h2><p>训练次数不代替能力表现。报告准备就绪后再展开诊断。</p><button onclick="tab(\'input\')">查看教学训练投入</button>';
document.querySelectorAll('#overview,#follow').forEach(view=>{let cover=view.querySelector('.view-state');if(!cover){cover=document.createElement('div');cover.className='view-state';view.prepend(cover)}cover.hidden=mode==='normal'||mode==='many';cover.textContent=mode==='partial'?'评分读取未完成，当前暂停展示能力结论与前后变化。':'评分覆盖不足，暂不生成班级能力结论或前后比较。';[...view.children].filter(c=>c!==cover).forEach(c=>c.hidden=!(mode==='normal'||mode==='many'))});
if(mode==='partial'){content.hidden=true;state.hidden=false;state.innerHTML='<h2>部分评分读取失败</h2><p>暂停能力诊断，避免用不完整样本给出班级判断。</p><button onclick="reviewState(\'normal\');document.getElementById(\'review-state\').value=\'normal\'">重试读取（演示成功）</button>';}
const extras=Array.from({length:17},(_,i)=>'扩展教学班 '+String(i+1).padStart(2,'0'));document.getElementById('class-options').innerHTML=[...classes.map(c=>c.name),...(mode==='many'?extras:[])].map(name=>`<option value="${name}">`).join('');if(mode==='many')notice('已加入17个示例班级，可在顶部输入名称搜索切换');}
const originalPickClass=pickClass;pickClass=function(value){if(value.startsWith('扩展教学班 ')){selected.clear();enter(2);document.getElementById('class-picker').value=value;document.getElementById('class-name').textContent=value;document.getElementById('class-subtitle').textContent='2026 秋季 · 示例教学班 · 暂无教学训练记录'}else originalPickClass(value)};
