const fs=require('fs'),path=require('path');const {Resvg}=require('C:/Users/31318/.codex/skills/image-to-svg/node_modules/@resvg/resvg-js');
const dir=__dirname;for(const folder of ['svg','png','source'])fs.mkdirSync(path.join(dir,folder),{recursive:true});
const phase4=path.join(dir,'../../explorations/stage-04-01A'),phase5=path.join(dir,'../../explorations/stage-05-wordmark/A-bold-v2');
let audit=[];const save=(p,s)=>fs.writeFileSync(path.join(dir,p),s);
function asset(name,s,widths){const outline=new Resvg(s,{font:{loadSystemFonts:true}}).toString();if(/<text\b|<image\b|data:|<script|<foreignObject|<filter|href=/i.test(outline))throw Error('Invalid '+name);save('svg/'+name+'.svg',outline);const a=new Resvg(s).render().pixels,b=new Resvg(outline).render().pixels;let diff=0;for(let i=0;i<a.length;i++)if(a[i]!==b[i])diff++;audit.push({name,paths:(outline.match(/<path\b/g)||[]).length,text:false,raster:false,pixelChannelDifferences:diff});for(let w of widths)save(`png/${name}-${w}.png`,new Resvg(outline,{fitTo:{mode:'width',value:w}}).render().asPng());return outline;}
const colors={green:'#10b981',black:'#000000',white:'#ffffff'};
for(const kind of ['symbol','micro']){const raw=fs.readFileSync(path.join(phase4,kind==='symbol'?'baseline.svg':'micro.svg'),'utf8');for(const [id,color]of Object.entries(colors))asset(`${kind}-${id}`,raw.replaceAll('#000',color),kind==='micro'?[16,24,32]:[32,64,128,256,512]);}
for(const kind of ['cn','en','bilingual']){let raw=fs.readFileSync(path.join(phase5,`A-${kind}.svg`),'utf8');save(`source/${kind}-editable.svg`,raw);for(const id of Object.keys(colors)){let s=id==='green'?raw:raw.replace(/fill="#[0-9a-fA-F]{3,6}"/g,`fill="${colors[id]}"`);asset(`lockup-${kind}-${id}`,s,[360,720]);}}
const symbol=fs.readFileSync(path.join(phase4,'baseline.svg'),'utf8').match(/<g[^>]*>[\s\S]*?<\/g>/)[0].replaceAll('#000','#fff');
const app=`<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024"><rect width="1024" height="1024" fill="#10b981"/><g transform="translate(224 224) scale(${576/624})">${symbol}</g></svg>`;asset('app-icon-square',app,[192,512,1024]);
save('audit.json',JSON.stringify(audit,null,2));console.log(JSON.stringify({assets:audit.length,pathOnly:audit.every(a=>!a.text&&!a.raster),maxPixelDiff:Math.max(...audit.map(a=>a.pixelChannelDifferences))}));
const embed=(name,x,y,w)=>{let s=fs.readFileSync(path.join(dir,'svg',name+'.svg'),'utf8');let view=s.match(/viewBox="([^"]+)"/)[1].split(/\s+/).map(Number);return `<g transform="translate(${x} ${y}) scale(${w/view[2]})">${s.replace(/<svg[^>]*>/,'').replace('</svg>','')}</g>`;};
const text=(x,y,t,size=18)=>`<text x="${x}" y="${y}" font-family="Microsoft YaHei" font-size="${size}" fill="#24382e">${t}</text>`;
let board=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="820" viewBox="0 0 1200 820"><rect width="1200" height="820" fill="#f6f8f6"/>${text(55,65,'智面幻境 · 01A × A Bold 交付预览',29)}${text(55,102,'纯路径 SVG｜绿色 #10B981｜标准主体与 16 px 补偿版',16)}<rect x="55" y="140" width="1090" height="255" rx="14" fill="white"/>${embed('lockup-cn-green',85,206,325)}${embed('lockup-en-green',445,206,325)}${embed('lockup-bilingual-green',825,206,270)}${text(85,360,'中文主组合')}${text(445,360,'英文独立组合')}${text(825,360,'双语组合')}<rect x="55" y="425" width="340" height="250" rx="14" fill="white"/>${embed('symbol-black',158,460,130)}${text(85,645,'单色黑 · 印刷与中性背景')}<rect x="430" y="425" width="340" height="250" rx="14" fill="#10251d"/>${embed('symbol-white',535,460,130)}<text x="465" y="645" fill="white" font-family="Microsoft YaHei" font-size="18">白色反白 · 深色背景</text><rect x="805" y="425" width="340" height="250" rx="14" fill="#fff"/>${embed('app-icon-square',889,447,166)}${text(835,645,'应用图标 · 方形源图')}${text(55,724,'安全区：符号高度 H 的 1/4；16–24 px 使用补偿版，32 px 及以上使用标准主体。',17)}${text(55,760,'最小尺寸建议：中文组合宽 180 px；英文宽 185 px；双语宽 210 px。',17)}${text(55,794,'交付候选 · 未替换产品界面 · 应用图标保留方形源图，由平台处理圆角。',15)}</svg>`;
save('delivery-board.svg',board);save('delivery-board.png',new Resvg(board).render().asPng());
