const{chromium}=require('C:/Users/31318/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});const results=[],errors=[];const out=__dirname;
for(const config of [{name:'landing',url:'/',width:1440},{name:'login',url:'/login',width:1440},{name:'register',url:'/register',width:1440},{name:'forgot',url:'/forgot-password',width:1440},{name:'login-mobile',url:'/login',width:390},{name:'home-desktop',url:'/home',width:1440,role:'STUDENT'},{name:'home-360',url:'/home',width:360,role:'STUDENT'},{name:'home-390',url:'/home',width:390,role:'STUDENT',dpr:2},{name:'home-430',url:'/home',width:430,role:'STUDENT',dpr:3},{name:'teacher',url:'/teacher/dashboard?demo=1',width:1440,role:'TEACHER'}]){
const c=await b.newContext({viewport:{width:config.width,height:950},deviceScaleFactor:config.dpr||1});const p=await c.newPage();p.on('pageerror',e=>errors.push({name:config.name,error:e.message}));
if(config.role)await p.addInitScript(role=>{localStorage.setItem('token','brand-preview-only');localStorage.setItem('role',role)},config.role);
await p.route('**/api/**',r=>{if(!new URL(r.request().url()).pathname.startsWith('/api/'))return r.continue();return r.fulfill({json:{code:200,data:r.request().url().includes('/user/profile')?{username:'品牌预览',role:config.role}:r.request().url().includes('/dashboard/overview')?{summary:{},recentInterviews:[],trend:[],nextAction:{},latestInsight:null}:[]}})});
await p.goto('http://127.0.0.1:5185'+config.url);await p.locator('img.brand-logo-image').first().waitFor({state:'attached',timeout:20000});await p.waitForTimeout(500);let info=await p.locator('img.brand-logo-image').evaluateAll(imgs=>imgs.map(i=>({src:i.currentSrc,loaded:i.complete&&i.naturalWidth>0,width:i.getBoundingClientRect().width,height:i.getBoundingClientRect().height,x:i.getBoundingClientRect().x,y:i.getBoundingClientRect().y})));
const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);await p.screenshot({path:path.join(out,config.name+'.png')});results.push({...config,logos:info,overflow});assert(info.length>0,config.name+' missing brand');assert(info.every(i=>i.loaded&&i.width>0),config.name+' unloaded logo');assert(!overflow,config.name+' overflow');await c.close();}
const c=await b.newContext();const p=await c.newPage();const r=await p.request.get('http://127.0.0.1:5185/favicon.svg');assert.equal(r.status(),200);let svg=await r.text();assert(!/<text|<image/.test(svg));results.push({faviconHttp:200,pathOnly:true});
fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({results,errors,backend:'API responses intercepted for layout-only checks'},null,2));await b.close();assert.equal(errors.length,0,JSON.stringify(errors));console.log('PASS '+results.length+' brand scene checks; no overflow or page errors.');})().catch(e=>{console.error(e);process.exit(1)});
