import {abilityDefinitions} from './studentCenter.js'
import {trends,classComparison,interventions,aggregate,common,classDefinitions,metricsVersion} from './analytics.js'
const xml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]))
const safe=v=>typeof v==='string'&&/^[=+@\-\t\r]/.test(v)?"'"+v:v
export const csv=rows=>'\ufeff'+rows.map(row=>row.map(v=>'"'+String(safe(v)??'').replaceAll('"','""')+'"').join(',')).join('\r\n')
const encoder=new TextEncoder()
// Stored ZIP entries avoid a compression dependency for these small analysis workbooks.
function zip(files){const local=[],central=[];let offset=0;const bytes=(n,length)=>{const a=new Uint8Array(length),d=new DataView(a.buffer);length===2?d.setUint16(0,n,true):d.setUint32(0,n,true);return a};const join=xs=>{const r=new Uint8Array(xs.reduce((n,x)=>n+x.length,0));let i=0;for(const x of xs){r.set(x,i);i+=x.length}return r};const crc=data=>{let c=0xffffffff;for(const b of data){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
 for(const [name,text] of Object.entries(files)){const n=encoder.encode(name),d=encoder.encode(text),c=crc(d);const header=join([bytes(0x04034b50,4),bytes(20,2),bytes(0,2),bytes(0,2),bytes(0,2),bytes(0,2),bytes(c,4),bytes(d.length,4),bytes(d.length,4),bytes(n.length,2),bytes(0,2),n]);local.push(header,d);central.push(join([bytes(0x02014b50,4),bytes(20,2),bytes(20,2),bytes(0,2),bytes(0,2),bytes(0,2),bytes(0,2),bytes(c,4),bytes(d.length,4),bytes(d.length,4),bytes(n.length,2),bytes(0,2),bytes(0,2),bytes(0,2),bytes(0,2),bytes(0,4),bytes(offset,4),n]));offset+=header.length+d.length}
 const directory=join(central);return join([...local,directory,bytes(0x06054b50,4),bytes(0,2),bytes(0,2),bytes(central.length,2),bytes(central.length,2),bytes(directory.length,4),bytes(offset,4),bytes(0,2)])}
export function workbook(rows){const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';const sheet=`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="${ns}"><sheetData>${rows.map((row,i)=>`<row r="${i+1}">${row.map((value,j)=>{let n=j+1,col='';while(n){n--;col=String.fromCharCode(65+n%26)+col;n=Math.floor(n/26)}const ref=col+(i+1);return typeof value==='number'&&Number.isFinite(value)?`<c r="${ref}"><v>${value}</v></c>`:`<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xml(safe(value))}</t></is></c>`}).join('')}</row>`).join('')}</sheetData></worksheet>`;return zip({'[Content_Types].xml':'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>','_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml':`<workbook xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="分析数据" sheetId="1" r:id="rId1"/></sheets></workbook>`,'xl/_rels/workbook.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>','xl/worksheets/sheet1.xml':sheet})}
export function exportRows(o){const {data,context:c}=o,all=o.scope==='scope',full=o.scope!=='view',rows=[['OfferPilot 分析数据'],['数据类型',data.source==='demo'?'演示数据':'真实数据'],['范围',o.scope],['当前Tab',o.tab],['局部筛选',o.scope==='view'?[o.ability.name,o.role||'全部岗位',o.type||'全部训练类型'].join(' · '):'全部能力、岗位与训练类型'],['筛选',o.scopeLabel],['开始日期',c.from],['结束日期',c.to],['生成时间',new Date().toLocaleString('sv-SE',{timeZone:'Asia/Shanghai'})+' +08:00'],['指标版本',metricsVersion],['评分版本',...new Set(data.records.map(r=>r.model+'/'+r.version))],[]];const abilityRows=d=>common.map(a=>aggregate(d,a)).map(a=>[a.ability,a.current,a.target,a.gap,a.n,a.version,a.excluded]);
 if(o.summary){
 if(all||o.tab==='overview')for(const a of(full?common:[o.ability])){rows.push(['趋势总览',a.name],['周开始','周结束','覆盖率%','自主次数','任务次数','按期完成率%','目标达成率%','可比人数','评分版本']);for(const p of trends(data,c,a))rows.push([p.date,p.to,p.coverage,p.self,p.teacherTask,p.onTime,p.achievement,p.n,p.version]);rows.push([])}
 if(all||o.tab==='classes'){rows.push(['班级对比'],['班级','有效学生','参与率%','人均有效次数','按期完成','逾期完成','未完成','时间缺失']);for(const x of classComparison(data,c,c.classIds.length?c.classIds:classDefinitions.map(k=>k.id))){rows.push([x.name,x.n,x.participation,x.frequency,x.execution.onTime,x.execution.late,x.execution.unfinished,x.execution.unknown]);rows.push(['训练来源','自主次数','教师任务次数'],[x.name,x.self,x.teacherTask]);rows.push(['能力','当前','目标','差距','样本','版本','其他版本排除']);rows.push(...x.abilities.map(a=>[a.ability,a.current,a.target,a.gap,a.n,a.version,a.excluded]))}rows.push([])}
 if(all||o.tab==='intervention')for(const a of(full?abilityDefinitions:[o.ability])){const x=interventions(data,c,a,full?'':o.type);rows.push(['训练与干预',a.name],['到期分配','按期完成','逾期完成','未完成','时间缺失'],[x.execution.total,x.execution.onTime,x.execution.late,x.execution.unfinished,x.execution.unknown],['完成学生','可比学生','前值','后值','差值','版本','提升','稳定','下降','数据不足'],[x.completed,x.n,x.before,x.after,x.diff,x.version,x.outcomes.improved,x.outcomes.stable,x.outcomes.declined,x.outcomes.insufficient],['相关任务','任务ID','班级','开始时间','截止时间']);for(const t of x.tasks.filter(t=>Date.parse(t.startTime)<=c.end&&Date.parse(t.deadline)>=c.start))rows.push([t.title,t.id,t.classId,t.startTime,t.deadline]);rows.push([])}
 if(all||o.tab==='roles'){rows.push(['岗位分布'],['岗位','人数']);for(const name of new Set(data.students.map(s=>s.position)))rows.push([name,data.students.filter(s=>s.position===name).length]);rows.push(['通用能力','当前','目标','差距','样本','版本','其他版本排除']);rows.push(...abilityRows(full||!o.role?data:{...data,students:data.students.filter(s=>s.position===o.role),records:data.records.filter(r=>r.position===o.role)}));rows.push(['岗位×通用能力矩阵','能力','当前','目标','差距','样本','版本','其他版本排除']);for(const name of new Set(data.students.map(s=>s.position))){const own={...data,students:data.students.filter(s=>s.position===name),records:data.records.filter(r=>r.position===name)};for(const a of common){const v=aggregate(own,a);rows.push([name,v.ability,v.current,v.target,v.gap,v.n,v.version,v.excluded])}if(full||name===o.role){rows.push(['岗位专业能力',name]);for(const a of abilityDefinitions.filter(a=>a.scope==='role')){const v=aggregate(own,a);rows.push([name,v.ability,v.current,v.target,v.gap,v.n,v.version,v.excluded])}}}rows.push([])}
 }
 if(o.details){rows.push(['有效训练明细'],['记录ID','学生ID','班级','完成时间','来源','岗位','报告评分','模型','版本','通用模型',...abilityDefinitions.map(a=>a.name)]);rows.push(...data.records.filter(r=>o.scope!=='view'||!o.role||r.position===o.role).map(r=>[r.id,r.studentId,r.classId,r.completedAt,r.source,r.position,r.score,r.model,r.version,r.commonVersion,...abilityDefinitions.map(a=>(a.scope==='common'?r.dimensions:r.roleDimensions)?.[a.name])]));rows.push([]);if(all||o.tab==='intervention'){const comparison=interventions(data,c,o.ability,full?'':o.type);rows.push(['前后可比记录明细'],['学生ID','任务ID','前记录ID','后记录ID','前时间','后时间','前值','后值','模型版本'],...comparison.pairs.map(p=>[p.studentId,p.taskId,p.beforeRecordId,p.afterRecordId,p.beforeAt,p.afterAt,p.before,p.after,p.version]),[]);rows.push(['任务分配明细'],['任务ID','任务名称','学生ID','截止时间','完成状态','完成时间']);for(const t of data.tasks.filter(t=>full||!o.type||t.type===o.type))for(const e of t.executions||[])if(data.students.some(s=>s.id===e.studentId))rows.push([t.id,t.title,e.studentId,t.deadline,e.completionStatus,e.completedAt])}}
 rows.push(['指标说明'],...o.definitions,['说明','前后变化为统计关联，不代表任务造成变化。空单元格表示数据不足或目标缺失，不代表0。']);return rows}
export async function downloadAnalytics(options){const rows=exportRows(options),xlsx=options.format==='xlsx',blob=new Blob([xlsx?workbook(rows):csv(rows)],{type:xlsx?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(options.fileName.replace(/[\\/:*?"<>|]/g,'_').replace(/\.(xlsx|csv)$/i,'')||'OfferPilot_分析数据')+'.'+options.format;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
